### ISSUE TITLE
Global Classes can't contain Image

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#103]
The following code gives a memory acces violation:

#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

Global FOO:=New FooGlob() 'IS NOT OK

Class FooGlob
 Field img:Image
 Method New()
 	img=New Image (64,64)
 End
End

Function Main()
	Local FOOB:=New FooGlob() 'IS OK
	Print "test"
End

**Comment by blitz-research** [comment]
No, in general globals can't be initialized with 'complex' objects like images, because globals are initialized before the app even begins, at which point stuff like OpenGL/SDL etc haven't even been initialized yet (this stuff is initialized by New AppInstance).
