### ISSUE TITLE
Semanting... Caught signal:Memory access violation

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#106]
If we use struct or class with string plus operator - we got "memory access violation", and there is no additional info and so on.
I'm using v1.0.91.

Test code:
```
Method Test:String()
	Local t:=New CodeType
	Return "t: "+t     ' <---- ERROR IS HERE
End
......
Struct CodeType
	Field kind:String
	Field ident:String
	Field expr:String
	Field args:CodeType[]	
End
```

I tried to add operator To into CodeType struct - have no effect.
```
Operator To:String()
	Return ident
End
```

**Comment by blitz-research** [comment]
Can't reproduce - can you post a 'runnable' example if it's still happening?

**Comment by engor** [comment]
Worked fine in v1.1.02.
