### ISSUE TITLE
mac os sierra - ide latest version don't start

### ISSUE THREAD

**Issue by gcmartijn** [blitz-research/monkey2#107]
H!

I saw the news today, so I downloaded the latest zip files at git.
cd downloads/monkey2-master/scripts
./rebuildall2go.sh

that creates a downloads/monkey2-master/Monkey2 (Macos)
(like the other version before)

but if I launch it, the program try to start for 1ms and closes without a error...

din't test the ./rebuildall.sh

**Comment by blitz-research** [comment]
I think I mentioned this on the blog, but ted2go is a 'submodule' and github doesn't include submodules when you download a zip (grrr....).

You'll need to use a proper git client to download the repos if you want ted2go. Or of course you can build it separately from the ted2go repos.

**Comment by gcmartijn** [comment]
I did read your message, but don't understand it haha. don't know what a 'submodule' is and because of the text ./rebuildall2go.sh

where can I find that 'submodule' , can I download it and add it as a module ?
maybe you can upload it as a module ?
And yes i'm one of that people that don't use a git client on all my computers.

**Comment by blitz-research** [comment]
The ted2go repos is here (should add it to 'files' page)....

https://github.com/engor/Ted2Go

You can download this as a zip manually copy it into monkey2/src.

A submodule is really just a 'pointer' to a particular branch or 'version'
inside this repos.
