### ISSUE TITLE
Random (rnd) gives wrong output.

### ISSUE THREAD

**Issue by Pakz001** [blitz-research/monkey2#110]
I tried to use the Rnd Command and with the default use where it gives between 0 and 1 output in the first few runs it gives output outside that range.

Here is the example where I found this. Pressing the f1 the first few times it is outside 0/1.
https://github.com/Pakz001/Monkey2examples/blob/master/Beginners%20-%20Rnd.monkey2

**Comment by blitz-research** [comment]
Seems to be working OK now.
