### ISSUE TITLE
Seems that using num lock does not change the keycodes.

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#112]
More info http://monkey2.monkey-x.com/forums/topic/few-small-ted2-bugs/page/2/#post-5239

**Comment by blitz-research** [comment]
It shouldn't as keycodes represent the 'physical' location of keys, eg:
there is only a single keycode for the '1' key, not a keycode for '1' and a
separate keycode for 'shift 1' (which is '!' here).

As far as I can see, fixing this involves manually checking for
'numlock-off + 8' as an alias for 'up' in TextView, and so on with other
keypad keys.




On Sun, Nov 20, 2016 at 7:05 AM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
Thanks!
