### ISSUE TITLE
Ted2 needs an icon

### ISSUE THREAD

**Issue by therevills** [blitz-research/monkey2#115]
Looks a bit sad without one :(

**Comment by therevills** [comment]
So is Ted2 getting an icon? :)

Ted2Go which comes with MX2 v1.1.01 still is missing a runtime icon: https://www.dropbox.com/s/0j51u31iyv3b39l/Screenshot%202017-01-12%2018.15.17.png?dl=0

**Comment by blitz-research** [comment]
It has one on windows/macos, doesn't it? Dunno how to do it linux...

**Comment by wrldwzrd89** [comment]
The sad fact is, Linux iconography isn't exactly consistent from distro to distro. So it's kind of difficult to make a "universal" Linux icon. At least macOS and Windows icons use well-known formats.

**Comment by therevills** [comment]
Did you see the screen shot? The exe has an icon, but when running it the there is just the default icon in the task bar.

**Comment by wrldwzrd89** [comment]
macOS has the exact same issue. The app has an icon, but it doesn't show in the Dock while it's running.

**Comment by chriscamacho** [comment]
every distro I've used, uses the same **standard**, place a desktop file in /usr/share/applications/ then you will have the specified icon in the menu and should with most desktops offer it as a default when making a launcher... 

if you want to install per user without root privileges use ~/.local/share/applications/ (where ~ is the home directory)

**Comment by chriscamacho** [comment]
if you need to do it at runtime you can set the _NET_WM_ICON property on x11 but having done it myself I wouldn't recommend it... you'd probably be better off using https://wiki.libsdl.org/SDL_SetWindowIcon as that might work on Mac as well?
