### ISSUE TITLE
Monkey2 apps fails to run on Windows XP 32bit

### ISSUE THREAD

**Issue by therevills** [blitz-research/monkey2#116]
Tested on the an old Celeron, Ted2 and MonkeyRoids fails to start with the same error:

> The procedure entry point CancelIoEx could not be located in the dynamic link library KERNEL32.dll

OS: Windows XP SP2 32bit
CPU: Intel Celeron E1200
RAM: 2GB
GPU: Intel GMA3100
DX: 9c

**Comment by blitz-research** [comment]
Windows XP is not officially supported, but if you can find any WinXP fixes I'll add them.
