### ISSUE TITLE
Conditional returns

### ISSUE THREAD

**Issue by jondecker76** [blitz-research/monkey2#12]
There must be a Return statement in the main body of a Method or an error is returned "Error: Missing Return Statement"

Consider the following
`
Method test(val:bool)
  if(val)
    Return True
  else
    Return False
  endif
end
`
since the returns are nested in an if statement, the error is triggered.  Surely this should be allowed?

**Comment by blitz-research** [comment]
Yes, mx2 should be a bit smarter about what's reachable or not - will work on this.

**Comment by blitz-research** [comment]
Fixed (for this case anyway).
