### ISSUE TITLE
Debug-captured objects don't report third type-hierarchy

### ISSUE THREAD

**Issue by ImmutableOctet** [blitz-research/monkey2#125]
I'm not sure how viable this is as far as the current reflection system goes, but the original Ted (And most other IDEs) used to show the underlying types behind an object, not just the observable type.

Here's an example:

```
Function Main:Void()
	Local first:= New Y()
	Local second:= Cast<X>(first)
	
	first.a = 10
	first.b = "Test"
	
	DebugStop()
	
	Print("Done.")
End

Class X
	Field a:Int
End

Class Y Extends X
	Field b:String
End
```

In Monkey 1, IDEs would read not only the fields involved, but what types they belong to. In this example, Ted 1 would report that 'a' belongs to 'X' and 'b' belongs to 'Y'.

Demonstration:
![ted1_vs_ted2_typeinfo](https://cloud.githubusercontent.com/assets/3187882/20842233/23963402-b874-11e6-8a7f-cef0ecaf7a8f.png)

Is this currently possible? If so, can I ask @engor about adding this to Ted2Go?

**Comment by blitz-research** [comment]
Ok, added [blah] above each set of class fields, so you get:

[default.X]
a:Int=10
[default.Y]
b:String="Test"
