### ISSUE TITLE
Most of the keyboard shortcuts are broken in Ted2 and Ted2Go

### ISSUE THREAD

**Issue by ImmutableOctet** [blitz-research/monkey2#126]
As the title states, the most recent versions of Ted2 and Ted2Go don't seem to be registering keyboard inputs to save, open files, or close documents. You can test this errant behavior by simply trying to save a file with CTRL+S.

Something to note is that CTRL+Z still works, but basically everything else doesn't.

I'm using the latest version of Monkey 2 (v1.1.02), on Windows 10. I've tried rebuilding modules, the compiler, Ted2, and Ted2Go, and this problem still persists with both editors.

**Comment by wrldwzrd89** [comment]
I can confirm that I too have this issue, on a Mac running Ted2Go.

**Comment by ImmutableOctet** [comment]
Fixed as of commit 36f26d397e2a3be2a8828851e14b64f6681627b4.
