### ISSUE TITLE
End Property

### ISSUE THREAD

**Issue by arpie42** [blitz-research/monkey2#127]
'End Class', 'End Method'... etc are fine.  'End Property' doesn't appear to be valid syntax.  For example, the following :
```
1 Class Everything
2   Property TheAnswer:Int()
3     Return 42
4   End Property
5 End Class

```
Gives the parsing error on line 4 :
> Error : Expecting end of line

**Comment by chriscamacho** [comment]
although some might think overly verbose (so keep optional) I think this adds greatly to readability a dozen nested ends can be as bad as a dozen nested } but at least if you know what they are ending you can better keep track of them!

**Comment by blitz-research** [comment]
Done.
