### ISSUE TITLE
Request: More flexibility for EOL chars and line wrapping

### ISSUE THREAD

**Issue by arpie42** [blitz-research/monkey2#130]
This is really two requests in one, but they both are intended to improve flexibility for code layout, allowing for what I consider to be tidier, more readable source code.

1. Can we have an alternative EOL character, such as a semicolon, as in MonkeyX (Monkey1?), so I can put multiple short commands on one line.  Sometimes I find this is useful, such as :

`Property thing:Int(); Return _thing; End`

2. This is sort of the exact opposite of 1.  Can the parser be made more tolerant of long commands being broken onto several lines?

For example, I like to use chaining methods (is that the right term?), like this :
```
MyObj.Make()
   .AddProperty1("big")
   .SetColor("brightblue")
   .WiggleToes()
```

Or, if I am constructing a heirarchy of objects, it is useful to be able to split long lines, such as :

`New MyObject(New Parameter1Thing(New Blahblah()), New Parameter2Thing("long string of config data"))`

Which could look much nicer like this :
```
New MyObject(
   New Parameter1Thing(New Blahblah()),
   New Parameter2Thing(
       "long string of config data"
   )
)
```

Of course, code layout and style is open to all sorts of conflicting opinion but there is nothing wrong with flexibility!

I think what I am specifically asking for is to update the parser to :
- recognise a line end character other than CR/LF (semicolon would seem a sensible candidate)
- ignore line breaks following an opening brace [this already works]
- ignore line breaks following a comma [any comma?  or just in parameter lists?]
- ignore line breaks preceding a dot operator [or perhaps after a dot operator?  Or both?]
- ignore line breaks preceding a closing brace

I suppose an alternative to those various 'ignore line break' rules might be to introduce a line wrap character?  Such as '\\' as in unix scripts?  But that could get ugly.  Does this already exist and I just don't know what it is?

Can anybody suggest any other improvements along this line?  In my experience, parsers are often tricky beasts to get right and Mark is probably reluctant to risk messing with it more often than necessary... so lets get it right once then stop.

**Comment by blitz-research** [comment]
Wont fix - I'm find with EOL rules as they are for now.
