### ISSUE TITLE
Mojo lighting issue when spanning monitors.

### ISSUE THREAD

**Issue by RichardBetson** [blitz-research/monkey2#132]
It seems when I  have two monitors (multi-monitor setup) and resize the window to encompass both lighting on the second monitor falls apart. It appears if lights have an issue on the second monitor. Non-lighted images seem to draw OK.

I have an image of the issue in this thread on Monkey 2's site.
http://monkey2.monkey-x.com/forums/topic/mojo-lighting-issue-when-spanning-monitors/#post-5788

**Comment by blitz-research** [comment]
Fixed!?!?
