### ISSUE TITLE
Varptr issue with Chipmunk

### ISSUE THREAD

**Issue by peterigz** [blitz-research/monkey2#135]
This might be revealing a bug in Monkey with pointers in general or in the way extern libs are used, but when using cpSpaceBBQuery in chipmunk, the UserData field in cpShape doesn't seem to work, as in the casting isn't retrieving the data and ending in a memory access error. According to the debugger the correct class has been cast but it crashes anyway. Here's some test code (I'm on Windows 10 btw):
	
	#Import "<std>"
	#Import "<mojo>"
	#Import "<chipmunk>"
	
	#Import "chipmunkdebugger"
	
	Using std..
	Using mojo..
	Using chipmunk..
	
	Struct somedata
		Field value:Int
	End
	
	Class HelloChipmunk Extends Window
	
		Field space:cpSpace
		Field ground:cpShape
		
		Field ballBody:cpBody
		Field ballShape:cpShape
	
		Field ballBody2:cpBody
		Field ballShape2:cpShape
	
		Field polyBody:cpBody
		Field polyShape:cpShape
		
		Field something:String = "App String"
		
		Field debugger:=New ChipmunkDebugger
		
		Method New()
		
			ClearColor=Color.Black
	
			'Create a new space and set its gravity to 100
			'		
			space=cpSpaceNew()
			space.Gravity=cpv( 0,1000 )
			
			Local data:=New MyClass
			
			Local body:= cpBodyNewStatic()
			body.Position = cpv(100,100)
			space.AddBody(body)
			Local shape:= cpBoxShapeNew(body, 50, 50, 0.0)
			shape.Friction = 1
			shape.UserData = Varptr(data)
			space.AddShape(shape)
			TestCallBack(Varptr(data))
	
		End
	
		Method OnRender( canvas:Canvas ) Override
		
			App.RequestRender()
		
			Const timeStep:=1.0/60.0
			
			space.StepTime( timeStep )
			
	'		Local rot:=ballBody.Rotation
	'		Local pos:=ballBody.Position
	'		Local vel:=ballBody.Velocity
	'		Print "ball rot="+ATan2( rot.y,rot.x )+", pos.x="+pos.x+", pos.y="+pos.y+", vel.x="+vel.x+", vel.y="+vel.y
	
			Local spacefilter:=cpShapeFilterNew(ULong(0), UInt(1), UInt(1) )
			
			Local Test:=Self
	
			cpSpaceBBQuery(space, cpBBNew(0,0,640,480), spacefilter, CallBack, Varptr Test)
			
			canvas.Translate( Width/2, Height/2 )
			
			debugger.DebugDraw( canvas,space )
		End
		
		Function TestCallBack(d:Void Ptr)
			'Sanity Check!
			Local data:=Cast<MyClass Ptr>(d)[0]
			Print data.Test
		End
		
		Function CallBack:Void(shape:cpShape, p:Void Ptr)
			Local whatsthis:=cpShapeGetUserData(shape)
			Local data:=Cast<MyClass Ptr>(whatsthis)[1]
			Local app:=Cast<HelloChipmunk Ptr>(p)[0]
			DebugStop()
			If data
				Print app.something
					Print data.Test
			End
		End
		
		Method Cleanup()	'Yeah, right!
			cpShapeFree( ballShape )
			cpBodyFree( ballBody )
			cpShapeFree( ground )
			cpSpaceFree( space )
		End
	
	End
	
	Class MyClass
		Field Test:String = "Something in myclass"
	End
	
	Function Main()
	
		New AppInstance
		
		New HelloChipmunk
		
		App.Run()
	End

**Comment by chriscamacho** [comment]
On Linux (64 bit) if I add

`Print data.Test`

immediately after

`Local data:=New MyClass`

While this isn't really a solution, I thought it might possibly give a clue...

**Comment by blitz-research** [comment]
I don't like the look of "shape.UserData=Varptr( data )" in the ctor. This
sets UserData to the address of a local variable, but locals are garbage
once they go out of scope, which is once ctor returns in this case.

Also, is "Cast<MyClass Ptr>( whatsthis )[1]" right? Shouldn't that just be
[0]? Wont matter though as there's still the 'local' problem above.

**Comment by peterigz** [comment]
Sorry the [1] was left in by mistake as I was experimenting, should be [0]

Ok the local makes sense now I think about it, that came about because I was trying to pass in a pointer to "Self" but self is not a valid variable reference, which is why I tried putting it in a local first but of course that's going out of scope (obvious now I think about it lol). So if I'm trying to pass a pointer to Self what's the best way of doing that?

...

I just answered my own question by putting a field in my class that references itself and that does work, I don't no how wacky that is but I guess I do similar things in javascript... :) Thanks.

**Comment by blitz-research** [comment]
> I just answered my own question by putting a field in my class that
references itself

Clever, but be careful there's something else referencing the class object
too, eg: put it in a global or on a stack or something.

The fundamental issue here is how to bind an mx2 object to a native object,
and it's a tricky one that I'm sure I'll be revisiting soon!
