### ISSUE TITLE
Feature req: add App.SystemLanguage

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#136]
Making international products we need to know locale of device app is running on.
So will be good to have property App.**SystemLanguage:String**, that will return locale.
Value can be '**en-US**' or simple two letter '**en**'.

For reference: there is a list of all [langs in unity3d](https://docs.unity3d.com/ScriptReference/SystemLanguage.html), but I preffer to use just a string value.

**Comment by blitz-research** [comment]
I generally agree, but I think this should be in 'std' instead so it can be used with console apps too.
