### ISSUE TITLE
DPI aware support for Ted

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#137]
In Windows10 with 4K monitor Ted and I suspect all monkey2 windowed apps will run at half res resulting in blurry display.

**Comment by nitrologic** [comment]
I am currently working on fix for MaxIDE involving a change to a manifest and a MaxGUI global zoom multiplier.

**Comment by wrldwzrd89** [comment]
The Mac build of the IDE needs this same fix.

**Comment by blitz-research** [comment]
Not happening here - anyone else?

Ted2 and Ted2go are both working OK on Mac with hdpi emulation enabled, ie:
fonts/images are all shown at actual pixel size, not 2x or anything weird.

I don't have a hdpi screen so I can't test ' for real', but someone did
report I had fixed their hdpi problems a while back.

**Comment by blitz-research** [comment]
Mac build of Ted2 and Ted2go both working OK on Mac here.

**Comment by nitrologic** [comment]
I need a $70 cable (display port little to big) to test with my MacBook which may be too old for 4K

**Comment by blitz-research** [comment]
I used this: https://www.tekrevue.com/tip/hidpi-mode-os-x/

It enables a 'fake' hdpi mode in display prefs.

**Comment by nitrologic** [comment]
For reference my recent BlitzMax commit seems to be working well with Windows 10.

https://github.com/blitz-research/blitzmax/commit/366ef478d55932cadefc4369ff6d1fe6d2aaa355

new thread here:

http://www.blitzbasic.com/Community/posts.php?topic=107680#1334890
