### ISSUE TITLE
docs for protected methods: building problem

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#139]
if you add a #rem monkeydoc to a protected method it will appear in it's class description page but will not have a foldable "chapter" for it's name nor a dedicated page.
for example OnRender cannot be found by searching as it doesn't have a "chapter" line in the foldable table of content.
And it does not have a dedicated page. That's why the link to OnRender on the mojo main page is not working.

**Comment by blitz-research** [comment]
Nice find!

Just pushed some makedocs fixes to develop branch, including one for this issue. Only rebuilt windows mx2cc though - you'll need to updatemx2cc if you're on macods/linux.
