### ISSUE TITLE
Bug in KeyboardDevice

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#140]
Ted2(Go) crashed when we typed some non-latin chars.
There is a russian 'э' char on the button with English apostrophe char  in my keyboard.
When I typed э instead of ' I got an IDE crash.
[See the link](https://yadi.sk/i/EqIfMoix3CAZnJ)

**Comment by blitz-research** [comment]
Ok, I just tried pasting the above 'backwards E' into a new untitled mojo app and, somwhat to my surprise, it worked fine! I pasted the char into the drawtext line, eg:

canvas.DrawText( "Hello World: э!",Width/2,Height/2,.5,.5 )

It showed up in the IDE and also when I ran the app. Also survived a quit/reload.

Can you try just pasting the char into the IDE, ie: does it only happen when you actually type the char?

I'm using ted2go here too...default theme.

**Comment by engor** [comment]
Paste work - it's not evolving keyboard device.
Try to pass 'э' directly into KeyboardDevice.KeyName () method that produce a crash.
I can't see screenshot above, insert new link
http://monkey2.monkey-x.com/wp-content/uploads/2017/02/chars_crash.png

**Comment by blitz-research** [comment]
Ok, potential fix now pushed to develop branch, basically just added array checking to KeyboardDevice.

The problem appears to be that SDL is converting 'э' to an invalid keyboard code - not sure why/how though and it may mean the 'э' key is unusable with KeyDown, KeyUp.

I can't test it myself as I don't have a russian keyboard - if it's still broken can you have a poke around and see what I got wrong?

**Comment by engor** [comment]
I just tested. It works correctly now.
So, I close issue.
