### ISSUE TITLE
Improved fullscreen support

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#141]
Could the default behavior of the new BeginFullScreen command match the desktop resolution and NOT the window dimensions.

As alternative the documentation could include solution for achieving such behavior.

**Comment by nitrologic** [comment]
When I use parameters with BeginFullScreen I am unable to hard code say 1920,1080,60 and get the window res.

Without parameters my 3840x2160 proudces 2561 x 1441 display, or that is what  display.Viewport.Width is reporting for the canvas passed to OnRender.

**Comment by blitz-research** [comment]
> Could the default behavior of the new BeginFullScreen command match the desktop resolution and NOT the window dimensions.

It should theoretically - source:

	Method BeginFullscreen()
		SDL_SetWindowFullscreen( _sdlWindow,SDL_WINDOW_FULLSCREEN_DESKTOP )
	End

...and SDL docs:

https://wiki.libsdl.org/SDL_SetWindowFullscreen

> When I use parameters with BeginFullScreen I am unable to hard code say 1920,1080,60 and get the window res.

Does your monitor support it? Perhaps HDR monitors only suppoprt HDR? Just a guess, but again the mx2 BeginFullScreen code looks OK to me - pretty simply anyway. Perhaps try taking out the SDL_GetClosestDisplayMode (probably shouldn't be in there anyway, better to just fail)? It's working fine here, but perhaps it's broken on your config?

Monkey2 does indeed still need EnumDisplayModes etc, but with multi-monitors, HDR monitors etc. I'm not looking forward to it!

**Comment by nitrologic** [comment]
It seems like a minefield.

		Local closest:SDL_DisplayMode
		SDL_GetDesktopDisplayMode( 0, Varptr closest)
		
		Print "mode:" + closest.w + "," + closest.h

For me this reports 2560,1440 (LIES) which is perhaps (just guessing) my native resolution but adjusted for DPI.

**Comment by nitrologic** [comment]
Confirmed, if I tell Windows 10 Display Settings to 100% zoom instead of 150 SDL_GetDesktopDisplayMode reports correct resolution. I think Ted2 will look much sharper too if this was addressed.

**Comment by blitz-research** [comment]
So what do I do?!?

**Comment by chriscamacho** [comment]
http://www.glfw.org/docs/latest/monitor_guide.html

much simpler to use...

**Comment by nitrologic** [comment]
Umm wait? 

You can increase Windows10 display zoom to reproduce the issue, fonts should get bigger but under SDL2 / mojo the native resolution of the Window gets lowered and the fonts get fuzzier.

Once I get my head around the maxfudge and the weirdhack and the mousescale and the undocumented HighDPI window flag I am hoping I can come up with helpful suggestion or a test implementation.

**Comment by blitz-research** [comment]
...how does that help exactly?

**Comment by nitrologic** [comment]
Closed until helpful suggestion or a test implementation can be provided.

**Comment by blitz-research** [comment]
Yeah, might be an idea to wait. Dealing with hdpi on mac was easier with
mac 'coz it has a really cool 'hdpi emulator' video driver, not so on PC.

But I'm leaving this open...

**Comment by chriscamacho** [comment]
using glfw as a backend would make things much simpler SDL is a successive band aid on top band aid - inefficient and not particularly easy to use.

**Comment by blitz-research** [comment]
> using glfw as a backend would make things much simpler SDL is a
successive band aid on top band aid - inefficient and not particularly easy
to use.

The solution to this particular issue is likely to involve a few lines of
code (if that, it may only require a manifest file), not a major rewrite of
a critical subsystem of monkey2.

I'm not sure what your beef is with SDL, but I have found it to be an
excellent API that is very easy to use and does what I need it to do really
well. Why throw away perfectly good, functional code?

Perhaps start a new 'feature request' issue for this? I'm unlikely to go
for it, but if you want to discuss glfw further, this issue is NOT the
place for it - we're trying to fix a dpi problem here, please don't hijack
issues for personal agenda stuff.

**Comment by chriscamacho** [comment]
This isn't a personal agenda, I'm simply suggesting a simpler solution, porting from sdl is near trivial, and it handles modern issues with a site more ease, I find it sad you have to resort to accusations (its not the first time I've had the brunt of your poor attitude) and its clear that from thas, I'm better off not involved with this project.
