### ISSUE TITLE
LoadImage is not working when image is passed in some function/method

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#147]
discussed in this topic: http://monkey2.monkey-x.com/forums/topic/function-variable-pointer/

#Import "<std>"
#Import "<mojo>"
Using std..
Using mojo..

#Import "assets/"

Class MyWindow Extends Window
	Field myImage:Image

	Method New(title:String="Simple mojo app",width:Int=640,height:Int=480,flags:WindowFlags=Null)
		Super.New(title,width,height,flags)
		MyImageLoading(myImage)
	End

	Method OnRender( canvas:Canvas ) Override
		App.RequestRender()
		If myImage Then
			canvas.DrawImage(myImage,50,50)
		Else
			Print "Nope, no image"
		Endif
	End
	
	Method MyImageLoading(img:Image)
		img=Image.Load("asset::test.jpg")
	End

End

Function Main()
	New AppInstance
	New MyWindow
	App.Run()
End

**Comment by blitz-research** [comment]
This is expected behaviour - functions parameters are not passed 'by reference' so when you assign to 'img' inside 'MyImageLoading' you are only assigning to a local variable which disappears when the function returns.

**Comment by abakobo** [comment]
ok but there's something i don't get. I thought classes where reference based (compared to structs) and thus passed by reference each time.. So I thought that it was Image.Load that was a kind of local variable like in the following example.
In this example, it IS modified (by reference I suppose) except if it is assigned to a local.

#Import "<std>"

Using std..

Class foo

	Field str:String

	Method New()
		str="default" 
	End

End

Function Main()

	Local f:=New foo()
	
	Print f.str
	modify(f)
	Print f.str 'has been modified (by reference?)
	modify2(f)
	Print f.str 'has not been modified (back to last modif (mod)
	
End

Function modify(f:foo)
	f.str="mod"
End

Function modify2(f:foo)
	Local f2:=New foo()
	f2.str="mod2"
	f=f2
	Print f.str 'is now pointing to f2?
End

**Comment by abakobo** [comment]
and in this with an image it is also modified (by reference?)

Thanks anyway and I hope I don't bother you with this..

#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

Class MyWindow Extends Window

	Field im:Image	
	Field canv:Canvas

	Method New( title:String="Simple mojo app",width:Int=640,height:Int=480,flags:WindowFlags=Null )
		Super.New( title,width,height,flags )
		im=New Image (400,400)
	End

	Method OnRender( canvas:Canvas ) Override
		
		DrawThings(im)
		canvas.DrawImage (im,50,50)
	
	End
	
End

Function DrawThings(img:Image)

		Local canv:Canvas
		canv=New Canvas (img)
		
		canv.Clear (Color.White)
		canv.Color=Color.Black
		canv.DrawText( "Hello World!",10,10 )
		canv.Flush()
End

Function Main()
	New AppInstance
	New MyWindow
	App.Run()
End

**Comment by blitz-research** [comment]
Yes, that will do what you expect.

When a function is called, all parameters are copied. However, in the case
of objects and arrays (ie: 'reference types') this only involves copying a
reference to the object/array which is very fast (ie: it's just copying a
pointer).

Physically, this generally just means the reference is 'pushed on the
stack' for use by the function, but it does also mean that the function
ends up using it's own copy of the reference, so modifying it will not have
any effect outside the function.

Some languages do allow a function to modify variables outside the function
via marking parameters as 'out' or 'inout' or 'var'. However, this then
means that the function MUST be called with a variable (or array element,
which is a kind of variable) for that parameter, ie: you can't use just
pass 'New Image' or 'x+y' as these are not variables.

Monkey2 does not support 'inout', 'out', or 'var' parameters, although it
may in future.
