### ISSUE TITLE
Image pointer/Varptr Image not working together

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#148]
I know it's a bit silly to want to use pointer to reference base object.. but

Namespace myapp

#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

Class MyWindow Extends Window

	Field im1:Image
	Field imPtr:Image Ptr

	Method New( title:String="Simple mojo app",width:Int=640,height:Int=480,flags:WindowFlags=Null )
		Super.New( title,width,height,flags )
		im1=New Image (50,50)
		imPtr=Varptr im1
	End

	Method OnRender( canvas:Canvas ) Override
	
		App.RequestRender()
		canvas.DrawText( "pointer to image's reference Image Ptr/Varptr Image problem",Width/2,Height/2,.5,.5 )
	End
	
End

Function Main()

	New AppInstance
	
	New MyWindow
	
	App.Run()
End

**Comment by blitz-research** [comment]
Fix commited to develop branch.
