### ISSUE TITLE
fails to initialize variables outside classes and functions. 

### ISSUE THREAD

**Issue by legionnairex3** [blitz-research/monkey2#154]
On windows this code should print Pi for all 3 prints but it prints 0 for pii:
`
Namespace myapp
 
#Import "<std>"
 
Using std..
 
Global pii := Pi
 
Function Main()
 
	 
	Print pii 'prints 0
	
	Print Pi 'Prints Pi
	
	Const Piii := Pi
	
	Print Piii 'Prints Pi
	
End
`

**Comment by coconcode** [comment]
It looks like at the time of assignment at the global scope, no Pi value was previously set.

By looking at the generated cpp files, it seems like the essential functions that these sort of initilizations take place are actually run at the time of the main function.
`mx2_std_main();mx2_std_main();`
