### ISSUE TITLE
readme.md link to i686-6.2.0-posix-dwarf-rt_v5-rev1.exe is dead

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#156]

**Comment by blitz-research** [comment]
No idea what this means! Could you clarify?

**Comment by abakobo** [comment]
this link in the windows installation notes is dead (in main readme.md file):
http://monkey2.monkey-x.com/mak/get-file?file=i686-6.2.0-posix-dwarf-rt_v5-rev1.exe

from

> ***** Building monkey2 on Windows *****

1) Install the mingw-64 compiler. There is a self-extracting archive of mingw-64 that has been tested with monkey2 here:

http://monkey2.monkey-x.com/mak/get-file?file=i686-6.2.0-posix-dwarf-rt_v5-rev1.exe

If you install this to the monkey2 'devtools' directory, the following steps should 'just work'.

> 

installing from sourceforge is not convenient at all compared to the installer that was provided at the time of mingw5.4. I suppose the problem arrived with the version change (5.4>6.2)
This could be a hassle for newcomers.

**Comment by blitz-research** [comment]
Fixed in develop branch, not in master yet.
