### ISSUE TITLE
DrawPrimitives() references "texCoords" where it should reference "colors"

### ISSUE THREAD

**Issue by Difference** [blitz-research/monkey2#157]
DrawPrimitives() casts "texCoords" to cp and not "colors" like it should.

The error is in canvas.monkey2 

Local cp:=Cast<UInt Ptr>( Cast<UByte Ptr>( texCoords )+i*colorsPitch ) should probably be:

Local cp:=Cast<UInt Ptr>( Cast<UByte Ptr>( colors )+i*colorsPitch )

**Comment by Difference** [comment]
Also: The docs says color UINT color is in RGBA format. 
It seems they are in ARGB format: Red is $ffff0000 , green ff00ff00 , blue $ff0000ff

**Comment by blitz-research** [comment]
Oops, nice find on the colors pointer front, fix pushed to develop branch.

'RGBA format' is sort of a standard that means R,G,B,A are stored in memory as bytes sequentially in that order, eg: if you have a UByte ptr p, then p[0]=red, p[1]=green, p[2]=blue, p[3]=alpha.

However, x86, arm etc are little endian, meaning bytes are loaded/stored 'low byte first' when loaded as a 4 byte int in one 'hit' so colors need to be stored 'back to front' if you want to load them as an int in one operation.

Either RGBA or ABGR is kind of right IMO, but I'll stick with RGBA.
