### ISSUE TITLE
PixMap->Image bug

### ISSUE THREAD

**Issue by jondecker76** [blitz-research/monkey2#16]
See http://monkey2.monkey-x.com/forums/topic/pixmap-image-bug/

received error:  Invalidate PixelFormat
{{!DEBUG!}}

**Comment by jondecker76** [comment]
`

Namespace myapp

#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

Class MyWindow Extends Window

	Method OnRender( canvas:Canvas ) Override
	    global i:Int
	   	
	   	Local pm:=New Pixmap(640, 480, PixelFormat.RGB24)
	   	pm.Clear(New Color(Rnd(0,255),Rnd(0,255),Rnd(0,255),1))
	   	Local img:=New Image(pm,TextureFlags.Dynamic)
	   	
	   	canvas.DrawImage(img,0,0)
	   	
		App.RequestRender()
	End
	
End

Function Main()

	New AppInstance
	
	New MyWindow
	
	App.Run()
End

`

**Comment by blitz-research** [comment]
Fixed.
