### ISSUE TITLE
Strings with umlauts not correctly handled in buffers and streams

### ISSUE THREAD

**Issue by Blitzbat** [blitz-research/monkey2#164]
I have figured out some strange behaviour when writing and reading strings with umlauts.
After reading there are characters missing. In the example it's the dot.

Local buffer := New DataBuffer(1024)
Local stream := New DataStream(buffer)
	
stream.WriteSizedString("Überhaupt kein problem.")
stream.Seek(0)
Print(stream.ReadSizedString())

**Comment by blitz-research** [comment]
Thanks for that - it was a bug in databuffer.monkey2 in the std modules.

I have pushed a fix to the develop branch.
