### ISSUE TITLE
Should to produce one more mouse event at ActivateWindow event

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#165]
When our window lost focus and we click on any view inside of that window - our click event eaten by window got focus event and no one view clicked here.

Other desktop gui apps got focus and send click event to child views.

**Comment by blitz-research** [comment]
You're right, and it appears to be an SDL 'feature'. I'm sure this used to work too, wonder if they broke it at some point? I have asked here, which is apprently the new sdl 'newsgroup':

https://discourse.libsdl.org/t/no-sdl-mousedown-when-sdl-window-activated/22791

**Comment by blitz-research** [comment]
Fixed.
