### ISSUE TITLE
Bugs: BeginFullscreen method of mojo.app Window class

### ISSUE THREAD

**Issue by ghost** [blitz-research/monkey2#168]
In the following method:

	Method BeginFullscreen( width:Int,height:Int,hertz:Int )
		Local mode:SDL_DisplayMode
		mode.w=Width
		mode.h=Height
		mode.refresh_rate=hertz
		Local closest:SDL_DisplayMode
		SDL_GetClosestDisplayMode( 0,Varptr mode,Varptr closest )
		SDL_SetWindowDisplayMode( _sdlWindow,Varptr closest )
		SDL_SetWindowFullscreen( _sdlWindow,SDL_WINDOW_FULLSCREEN )
	End

the following lines are incorrect:

mode.w=Width
mode.h=Height

Should be:

mode.w=width
mode.h=height

... to match the case of the passed-in parameters.

**Comment by blitz-research** [comment]
ahh...yes...hmm...oops.

Fixed in develop branch - and docs for BeginFullscreen/EndFullscreen made properly public.
