### ISSUE TITLE
Empty Select causes Error

### ISSUE THREAD

**Issue by Difference** [blitz-research/monkey2#173]
Select without any Case statements causes an "Internal mx2cc build error". Although there is no reason for a Select without Case, this should probably not throw an error. (Was found it whilst temporarily remming out some Case statements. Code to reprodue below (MacOS, MX2 1.04)

> Function Main()
	Local a:Int
	Select a
'		Case 0
'			Print "ok"	
	End Select 
	Print "Done"	
	
End

**Comment by blitz-research** [comment]
Fixed in develop branch.
