### ISSUE TITLE
Pi and TwoPi cannot be assigned to a constant in Windows

### ISSUE THREAD

**Issue by noroads2015** [blitz-research/monkey2#174]
For some reason, Pi and TwoPi cannot be assigned to another constant when compiling for windows.  Tried on the latest development version.
`Const PiAgain:Float = Pi
Const Tau:Float = TwoPi

Const ThisWorks:Double = 3.1415926535897931
Const SoDoesThis:Float = ThisWorks

Function Main()
	Print Pi
	Print PiAgain
	Print TwoPi
	Print Tau

	Print ThisWorks
	Print SoDoesThis
End function`

**Comment by blitz-research** [comment]
Should be fixed now.
