### ISSUE TITLE
GetFileType AssetsDir() vs assets::

### ISSUE THREAD

**Issue by Difference** [blitz-research/monkey2#175]
This is a reminder of the issue described here: http://monkey2.monkey-x.com/forums/topic/fileexists-for-all-targets/

> Is there a way to check if a file exists (on all targets) ?

I’ve been trying GetFileType(“asset::myfile.txt”)<> FileType.None , but I don’t think I’m getting correct results.

> Try: GetFileType( AssetsDir()+”myfile.txt” )

There’s a bit of a mismatch between ‘stream paths’ and ‘filesystem paths’ at the moment, ie: ‘asset::’ only works when opening a stream, but things like GetFileType, GetFileTime etc work with filesystem paths. It should probably work everywhere (where possible – assets aren’t always stored in the filesystem) but there are other issues with filesystem paths and soft/hard links that also need to be dealt with. Feel free to add an issue referencing this post though.

**Comment by blitz-research** [comment]
This should be mostly fixed now, but don't forget assets doesn't map to a filesystem dir on android so it wont work there.
