### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#176]
On Mac this code

```
#Import "<mojo>"	
Using mojo..
Function Main()
Local flags:=WindowFlags.HighDPI
flags+=WindowFlags.Resizable
end

```
produces this 

> Mx2cc version 1.1.04
> 
> ***** Building app '/Users/simon/blitz-research/monkey2/tmp/untitled1.monkey2' *****
> 
> Parsing...
> Semanting...
> Caught signal:Memory access violation

**Comment by blitz-research** [comment]
Fixed.
