### ISSUE TITLE
adding floats to integers gives odds results

### ISSUE THREAD

**Issue by legionnairex3** [blitz-research/monkey2#178]
this should give the result of 0 for both examples but it doesn't.
``Namespace` myapp

#Import "<std>"

Using std..

Function Main()

	Local v:Vec2i =  New Vec2i
	v.x += .1
	Print v.x
	Local y:int
	y += .1
	Print y	
	
End``

**Comment by blitz-research** [comment]
Works OK here.

**Comment by legionnairex3** [comment]
Still fails on OS X . It fails on my MacBook.

I get this results:
-1163695568
-1163695568

**Comment by blitz-research** [comment]
Working fine here on macos 10.2 and monkey2-v1.1.05b

**Comment by legionnairex3** [comment]
I haven’t updated to the latest download. I’ll let you know when I do.

**Comment by blitz-research** [comment]
I think it's a string->double bug in the compiler that was recently fixed.
