### ISSUE TITLE
Ted2 Scripts broken for posix environments

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#18]
The following mod to mainwindow.monkey2[1330] gets scripts running in Ted2 in non-Windows environments.

```
#If __HOSTOS__="windows"
		script+=".bat"
#Else If __HOSTOS__="macos"
		script="/bin/bash -l "+script+".sh"
#Else
		script="/bin/bash -l -c "+script+".sh"
#Endif
		Local cmd:=script
```

**Comment by blitz-research** [comment]
What does -c do?

**Comment by blitz-research** [comment]
(and -l for that matter).

**Comment by nitrologic** [comment]
Yup, sorry I have been so brief. If you run ted from Mac or Linux you will find the script menu does not work.

The above allows scripts to call other scripts with environment variables shared correctly.

**Comment by blitz-research** [comment]
Yes, just occured to me I may not have even tried scripts on macos/linux - testing now...

**Comment by blitz-research** [comment]
Fixed.
