### ISSUE TITLE
files still contain monkey2-monkey-x.com refs.

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#183]
the following files still have monkey2.monkey-x.com as official DNS:

\bin\env_windows.txt
\README.TXT
\modules\jni\module.json
\modules\libc\module.json
\modules\litehtml\module.json
\modules\miniz\module.json
\modules\mojo\module.json
\modules\mojox\module.json
\modules\monkey\module.json
\modules\openal\module.json
\modules\reflection\module.json
\modules\sdl2-mixer\module.json
\modules\sdl2\module.json
\modules\stb-image-write\module.json
\modules\stb-image\module.json
\modules\stb-truetype\module.json
\modules\stb-vorbis\module.json
\modules\std\module.json
\modules\theoraplayer\module.json
\modules\monkey\docs\language\loop-statements.md
\src\ted2go\README.md
\modules\monkey\docs\sdks.md
\src\ted2\helpactions.monkey2
\src\ted2go\action\HelpActions.monkey2
\modules\mojox\tests\assets\mainwindow.monkey2
\src\ted2\modulemanager.monkey2
\src\ted2go\product\ModuleManager.monkey2
\modules\mojox\tests\assets\about.html
\src\ted2go\assets\about.html
\src\ted2go\assets\aboutTed2Go.html
\docs\index.html

**Comment by blitz-research** [comment]
Thanks!
