### ISSUE TITLE
'Image.Load' should have a texture-flags argument.

### ISSUE THREAD

**Issue by ImmutableOctet** [blitz-research/monkey2#184]
The current version of 'Image.Load' does not allow the caller to specify texture flags, like 'Mipmap', or 'WrapS'/'WrapT'.

**Comment by ImmutableOctet** [comment]
Somewhat related; why is 'TextureFlags.Filter' forced on when creating an 'Image' object?

**Comment by blitz-research** [comment]
This is based on the assumption that most people want it on by default.

**Comment by ImmutableOctet** [comment]
Yeah, but a lot of people don't. This was one of the most common problems with Monkey 1; people wanted to be able to toggle filtering, and Mojo 2 made that a lot simpler.

I just read through all of the source for managing textures and resources just to make my own version to get around this. Being able to specify the flags I want would have been a lot simpler, and I know somebody else is going to have to jump through hoops like I just did.

**Comment by blitz-research** [comment]
Is there a feature request or something here? flags param for Image.Load
perhaps?

**Comment by blitz-research** [comment]
Actually, I do think you're right in general, should be easier to control
image texture flags.

How about:

* The textureFlags param for image constructors defaults to
TextureFlags.FilterMipmap (ie: 'smooth' images) but can be directly
overridden by user. Currently, the textureFlags param is munged a bit.

* Image.Load has a textureFlags paramater added to it before existing
shader param. This may break some existing code, but its worth it IMO for
the sake of consistency.

* Texture.Flags remains read/write just in case.

**Comment by ImmutableOctet** [comment]
Yep, that's exactly what I was thinking. You could also make a compatibility overload for 'Image.Load' that's just:

> Function Load:Image(path:String, shader:Shader)
>       Return Load(path,, shader)
> End

That overload would call the main version (Taking path, flags, and shader), using the default argument for flags.
