### ISSUE TITLE
error in a #import line have troublesome behaviour

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#187]
When there's some kind of error in an #import line and you press F5 it will:

-If in the main file and no compilation/products are there it doesn't send a specific error, just fails with a generic notification. (it can be very long to find the error)
-If in another file it gives an error but no filename, no line number. (it can be very long to find the error)
-If in the main file and if the project has alredy been compiled once it will give no error, won't compile anything but will run the executable (it should return an error and run nothing IMO)

I've had the problem while I had deleted the last " character involuntarily. It took me quite a while to find what happened.
#Import "myfile.monkey2"  ---> #Import "myfile.monkey2

**Comment by blitz-research** [comment]
Preprocessor error reporting should now be greatly improved.
