### ISSUE TITLE
sdl2 missing Advapi32.lib when using visual studio

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#188]
to fix link issue on some toolchains the following line can  be added to sdl2/makefile_windows.monkey2

#import "<libadvapi32.a>"

**Comment by blitz-research** [comment]
Having trouble reproducing this.

Can you build/run the sdl2test banana?

**Comment by nitrologic** [comment]
I think it was maybe vsynth banana. The sdl2 library was using win32 registry calls to enumerate available audio devices which needed advapi32 lib to link with vc++. Will investigate further.

**Comment by blitz-research** [comment]
Maybe SDL_mixer module then?

**Comment by blitz-research** [comment]
Weird, vsynth working here, although I had to #include <algorithm> at the top of audiopipe.h for std::min, std::max.
