### ISSUE TITLE
mojo3d limited to 1920 display width

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#192]
The mojo3d demos give weird results when run at 4K (I'm on a 4K TV with desktop set to 1920 x 1080):

https://ibb.co/g4f64a

This image comes from changing ducks demo to:

`Method New( title:String="Simple mojo app",width:Int=3840,height:Int=2160,flags:WindowFlags=WindowFlags.Fullscreen )
`
Seems to limit widths to 1920 (height looks fine) -- thought it was limiting to desktop width, but I can lower desktop to 720p and fullscreen 1080p display works fine, so it's not that, just appears to be hard 1920 width limit.

**Comment by blitz-research** [comment]
Possible fix pushed to develop branch - note: you'll need to rebuildmx2cc before you can update latest modules in develop.

Can't test the fix myself so can you let me know if it works?

**Comment by DruggedBunny** [comment]
Hi Mark, sorry for delay (this was 5 days ago?!)...

It hasn't worked, unfortunately! Still looks exactly per the screenshot.

I've tested by taking a copy of my existing Monkey2-v1.1.05b, copying all of develop over it and deleting the ducks build/product folders before running.

What was changed? Might give me a clue where to look... assume some shader somewhere would be most likely candidate?

**Comment by DruggedBunny** [comment]
I missed rebuildmx2cc and remembered just after posting the above -- so, just did that on the above setup, re-deleted products/build and still same result. Not sure if this fully covers the conditions you're expecting, though?

EDIT: For clarity, thought I may have misunderstood the rebuild stuff. Just took my 1.1.05b again, ran rebuildmx2cc FIRST, then deleted the two ducks folders and tried again -- same result.

**Comment by DruggedBunny** [comment]
I've fixed this for my specific use-case by simply amending deferredrenderer.monkey2 -- it was the WIDTH and HEIGHT consts at the start. Assume these were meant to be temporary:

```
Namespace mojo3d.graphics

Private

Const WIDTH:=3840 ' Was 1920
Const HEIGHT:=2160 ' Was 1080
Const MRT_COLOR_FORMAT:=PixelFormat.RGBA8'RGBA32F

```
Not sure what the 'general case' fix would be (assume just grabbing device res), but this makes 4k ducks work...

There's another hard-coded 1920/1080 in canvas.monkey2 -> BeginLighting(), but I think that may have been fixed already in relation to a separate lighting bug (?). I didn't have to touch that, just found it along with this via Agent Ransack...

**Comment by blitz-research** [comment]
Nice find, but this is already fixed in the develop branch:

https://github.com/blitz-research/monkey2/blob/develop/modules/mojo3d/graphics/deferredrenderer.monkey2

Mojo3d hasn't been added to master branch yet so you must be using the original release?

Note that monkey2 repos defaults to 'master' branch in the 'code' tab above, you need to manually switch it to develop branch.

**Comment by DruggedBunny** [comment]
Yeah, I'm using the itch.io release here... just rebuilt with that renderer version and it's working great in 4k -- closed!
