### ISSUE TITLE
Mojo3d apps spontaniously closing on itself.

### ISSUE THREAD

**Issue by Pakz001** [blitz-research/monkey2#193]
I do not know how this happens yet but I have had this happen a dozen time or so already. I was working on something and monkey would just close the app(not ted) There is no message or anything.

It was happening with this file : ( No time to uncomment bit by bit and test if it happens yet )

https://github.com/Pakz001/Monkey2-3D/blob/master/Example%20-%20Random%20map%20mesh.monkey2

**Comment by blitz-research** [comment]
Can't get it to crash (windows 10) but please do not use _scene.Models - it's undocumented and (therefore)  internal. 

Will be adding an 'Internal' access to mx2cc soon...

**Comment by blitz-research** [comment]
Can't reproduce.
