### ISSUE TITLE
Module Manager broken

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#198]
The module manager for monkey2 currently uses a monkey-x.com domain name which can no longer be resolved.

**Comment by Hezkore** [comment]
You should really be using Ted2Go instead of Ted2.
Ted2Go points to the correct domain.
_(Mark still needs to fix this)_

**Comment by blitz-research** [comment]
Both Ted2 and Ted2go are working here - source code looks fine and I just
tested by deleting/installing portmidi.

**Comment by blitz-research** [comment]
You may still be using master branch? Haven't updated this for a while,
will do after 1.1.06 is out.

**Comment by nitrologic** [comment]
Check source and yes it has been fixed. Run ./rebuildall2go.sh again on linux and still broken. 

Checking and common.sh looks like it is the problem. 

Perhaps encoding mx2cc version in build path is an OK idea but prone to errors?

**Comment by nitrologic** [comment]
Closed this issue, wasting others time here with my own confusion.

**Comment by nitrologic** [comment]
I elected the master branch at work assuming it would be more stable / bug
free rather than being used for release snapshots.

You may want to consider calling it release and making the develop branch
default if master is not going to get bug fixes between releases.
