### ISSUE TITLE
Mojo build error on Linux: no match for operator 

### ISSUE THREAD

**Issue by RichardBetson** [blitz-research/monkey2#2]
Monkey2 build fails on compiling the mojo module. I get the following errors on Linux Mint 17.2:

/```
home/moonbasealpha/Programming/monkey2/modules/monkey/native/bbmonkey.h:21:7: error: no match for ▒operator> (operand types are ▒t_std_geom_Vec2_1i and ▒t_std_geom_Vec2_1i)
/home/moonbasealpha/Programming/monkey2/modules/monkey/native/bbmonkey.h:22:10: error: no match for ▒operator> (operand types are ▒t_std_geom_Vec2_1i and ▒t_std_geom_Vec2_1i)

/home/moonbasealpha/Programming/monkey2/modules/monkey/native/bbmonkey.h:21:7: error: no match for ▒operator> (operand types are ▒t_std_geom_Rect_1i and ▒t_std_geom_Rect_1i)
/home/moonbasealpha/Programming/monkey2/modules/monkey/native/bbmonkey.h:22:10: error: no match for ▒operator> (operand types are ▒t_std_geom_Rect_1i and ▒t_std_geom_Rect_1i)
```/

**Comment by RichardBetson** [comment]
Added to above. Listed here in case you did not notice.

/home/moonbasealpha/Programming/monkey2/modules/monkey/native/bbmonkey.h:21:7: error: no match for ▒operator> (operand types are ▒t_std_geom_Rect_1i and ▒t_std_geom_Rect_1i)
/home/moonbasealpha/Programming/monkey2/modules/monkey/native/bbmonkey.h:22:10: error: no match for ▒operator> (operand types are ▒t_std_geom_Rect_1i and ▒t_std_geom_Rect_1i)

**Comment by blitz-research** [comment]
Can you post sample sample code or something?

The chances of me being able to fix a bug based purely on error messages are approximately 3.7%.

**Comment by RichardBetson** [comment]
"The chances of me being able to fix a bug based purely on error messages are approximately 3.7%."
LOL! Pure gold!

**Comment by RichardBetson** [comment]
Looks like the latest build is working. So I guess it's fixed. :) BTW this was an error in building MX2 modules so there is no code I really could have posted.
