### ISSUE TITLE
unimplemented generi

### ISSUE THREAD

**Issue by legionnairex3** [blitz-research/monkey2#20]
`Function Main()
	Local v1:Collision = New HitBox(new PVector2D(7,56),30,40,50,48)
	Local v2:Collision = New HitCircle(new PVector2D(28,17),10,15,20)
	v1.Render()
	v2.Render()
End function			
 
Class PVector2D
	Field x:Float
	Field y:Float
	
	Method New()
	End Method
	
	Method New(x:Float,y:Float)
		Self.x = x
		Self.y = y
	End Method
	
	Method Set:Void(x:Float,y:Float)
		Self.x = x
		Self.y = y
	End Method
End Class
 
 
 
Class Collision Abstract
	Field pos:PVector2D
	Field off:PVector2D
	
	Method New()
		off = New PVector2D
	End Method
	
	Method Set:Void(pos:PVector2D,ox:Float,oy:Float,width:Float,height:Float) Abstract
	Method Set:Void(pos:PVector2D,ox:Float,oy:Float,radius:Float) Abstract
	Method Collided:Bool(col:Collision) Abstract
	Method Render() Abstract
	
End Class
 
 
Class HitBox Extends Collision
	Field width:Float
	Field height:Float
  
  	Method New()
  	
  	End Method
  
	Method New(p:PVector2D,x:Float,y:Float,width:Float,height:Float)     
		Set(p,x,y,width,height)
	End Method
  
	Method Set:Void(pos:PVector2D,ox:Float,oy:Float,width:float,height:float) Override
		Self.pos = pos
		off.Set(ox,oy)
		Self.width = width
		Self.height = height
	End Method
  
  Method Collided:Bool(bx:Collision) Override
  		Local box := cast<HitBox>(bx)
    	Local b1x1:Float = pos.x + off.x
    	Local b1y1:Float = pos.y + off.y
    	Local b1x2:Float = pos.x + width
    	Local b1y2:Float = pos.y + height
    	Local b2x1:Float = box.pos.x + box.off.x
    	Local b2y1:Float = box.pos.y + box.off.y
    	Local b2x2:Float = box.pos.x + box.width
    	Local b2y2:Float = box.pos.y + box.height
    	If b1x1 > b2x2 Return False
    	If b1x2 < b2x1 Return False
    	If b1y1 > b2y2 Return False
    	If b1y2 < b2y1 Return False 
    Return True
  End Method
    
  Method Render:Void() Override
	Print pos.y
 End Method
  
End Class
 
 
Class HitCircle Extends Collision
	
	Field radius:Float
	
	Method New(pos:PVector2D,ox:Float,oy:Float,radius:Float)
		Set(pos,ox,oy,radius)
	End Method
	
	Method Set(pos:PVector2D,ox:Float,oy:Float,radius:Float=0) Override
		Self.pos = pos
		off.Set(ox,oy)
		Self.radius = radius
    End Method
    
	Method Collided:Bool(bx:Collision) Override
  		Local box := Cast<HitBox>(bx)
		If box Then Return Rectangle(box)
		Local cir := Cast<HitCircle>(bx)
		If cir Then Return Circle(cir) 
		Return False
	End Method
  
	Method Circle:Bool(cir:HitCircle)
  		Local totRadius:Float
  		Local vx:Float = pos.x - cir.pos.x
  		Local vy:Float = pos.y - cir.pos.y
  		totRadius = Self.radius+cir.radius
  			
  		If (vx*vx+vy*vy) < totRadius*totRadius Return True
  		Return false
	End Method
  
	Method Rectangle:Bool(rect:HitBox)
  		Local vx:Float = rect.width/2
  		Local vy:Float = rect.height/2
		Local radius:Float = Sqrt(vx*vx + vy*vy) 
		Local totRadius := Self.radius + radius
		Local nx:Float = pos.x - rect.pos.x 
		Local ny:Float = pos.y - rect.pos.y
		If totRadius*totRadius < (nx*nx + ny*ny) Return False
		Return True
	End Method
	
	Method Render:void() Override
		Print pos.x
	End Method
End Class`

the above code translate with MX2 but fail to compile with the c compiler. apparently is due to the un implemented abstract method in the extended classes. Mx2 is not able to find errors with abstract methods that have the same name but different parameters and are not implemented in the extended classes.

**Comment by blitz-research** [comment]
Should be fixed now.
