### ISSUE TITLE
mojo3d: No light if ShadowsEnabled = False before rendering

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#200]
Not fully determined the circumstances, but if I call `light.ShadowsEnabled = False` before rendering anything (see light setup below), it renders without light being cast on the cubes, just using ambient light, I believe.

Run this to see it, then tap space to enable shadows (and lighting!), then tap again to turn shadows off -- the 'non-shadowed' lighting works now.

```

#Import "<std>"
#Import "<mojo>"
#Import "<mojo3d>"

Using std..
Using mojo..
Using mojo3d..

' ----------------------------------------
' Application name...
' ----------------------------------------

Global AppName:String = "My 3D Game"

' ----------------------------------------

Function CreateCube:Model (color:Color = Color.Aluminum)

	Local cube:Model
	Local cubemesh:Mesh
	Local cubematerial:Material

	cubemesh		= Mesh.CreateBox (New Boxf (-0.5, 0.5, 0.5, 0.5, -0.5, -0.5))
	cubematerial	= New PbrMaterial (color)
	
	cube = New Model (cubemesh, cubematerial)

	Return cube
			
End

Class Game Extends Window
	
	' Basic 3D scene requirements...
	
	Field scene:Scene
	Field camera:Camera
	Field light:Light

	Field cubes:Stack<Model>
	
	Method New (title:String, width:Int, height:Int, flags:WindowFlags)
		
		Super.New (title, width, height, flags)
		
		scene 	= Scene.GetCurrent ()

			scene.ClearColor = New Color (16 / 256.0, 32 / 256.0, 128 / 256.0)
			
		camera	= New Camera

		light	= New Light

			light.Move (-50, 50, 0)
			light.Rotate (0, 90, 0)

			light.ShadowsEnabled = False
					
		cubes = New Stack<Model>
		
			For Local loop:Int = 1 To 1000
				
				Local cube:Model = CreateCube (New Color (Rnd (0.4, 1.0), Rnd (0.4, 1.0), Rnd (0.4, 1.0)))
	
				cube.Move (Rnd (-100, 100), Rnd (-100, 100), Rnd (-100, 100))
				
				cubes.Push (cube)
				
			Next
		
	End
	
	Method ProcessInput:Void ()

		If Keyboard.KeyHit (Key.Space)
				light.ShadowsEnabled = Not light.ShadowsEnabled
		Endif
		
		If Keyboard.KeyHit (Key.Escape) Then App.Terminate ()

		If Keyboard.KeyDown (Key.A)
				camera.Move (0.0, 0.0, 0.5)
		End

		If Keyboard.KeyDown (Key.Z)
				camera.Move (0.0, 0.0, -0.5)
		End

		If Keyboard.KeyDown (Key.Left)
				camera.Rotate (0.0, 1.0, 0.0, True)
		End
						
		If Keyboard.KeyDown (Key.Right)
				camera.Rotate (0.0, -1.0, 0.0, True)
		End

		If Keyboard.KeyDown (Key.Up)
				camera.Rotate (1.0, 0.0, 0.0, True)
		End
						
		If Keyboard.KeyDown (Key.Down)
				camera.Rotate (-1.0, 0.0, 0.0, True)
		End								
									
	End
	
	Method OnRender (canvas:Canvas) Override

		ProcessInput ()
		
		For Local cube:Model = Eachin cubes
			cube.Rotate (1.0, 2.0, 4.0)
		Next
		
		scene.Render (canvas, camera)
		
		RequestRender ()
		
	End
	
End

Function Main ()

	' Windowed mode...
	
	Local width:Int			= 1920
	Local height:Int		= 1080
	Local flags:WindowFlags	= WindowFlags.Fullscreen
	
	New AppInstance
	
	New Game (AppName, width, height, flags)
	
	App.Run ()
		
End

```
(Was comparing against same code in Blitz3D, as it was running really, really slowly in mojo3d, while Blitz3D was blazingly fast... then slowly realised it was all those shadows being cast via a thousand cubes! Runs perfect without, duh... )

**Comment by blitz-research** [comment]
It seems to be working here, nice demo too!

Are you using the latest version in develop? I notice you're still using
radians and the latest version uses degrees (mojo3d only) so you should
probably update.

Also, bit of a tip:

If Keyboard.KeyHit (Key.Space) light.ShadowsEnabled=Not light.ShdowsEnabled

light.ShadowsEnabled is kind of hacked in right now but it should still
work!

**Comment by DruggedBunny** [comment]
Ah, that does indeed work in dev -- I'll just start using develop now.

Ted2Go looks a lot nicer now, too. (Still needs Cut, Copy, Paste outside the main menus though! And Save/Save As icons... )

EDIT: Updated above code with Not light.ShadowsEnabled and fixed camera control. (The effect of the last Rotate param seems different now, was left off before -- seems different to Blitz3D TurnEntity's `,global` param effect.) Manually changed scene Cls colour, but everything looks kinda washed out, which I guess is just a product of the new materials that needs to be messed about with.

Getting fun, though!
