### ISSUE TITLE
Can't load .fbx or .blend models

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#206]
So far I haven't managed to load a single .fbx or .blend file -- by way of example, these free sets include .fbx:

https://devilsgarage.itch.io/3d-low-poly-game-assets-unity-superpowers-html5-racing-car-sport
https://emerald-eel-entertainment.itch.io/low-poly-foliage-pack-001

The .dae and .obj files load, although the .obj models look like Plasticine when loaded! The .dae models are fine.

I've tried maybe half a dozen each of .fbx and .blends now.

The result of Model.Load here is:

`aiImportFile failed: path=I:/SpiderOak/DevTools/Monkey2/Source/fbxtest.products/Windows/assets/car_sedan.fbx
`

This _assimp-based_ 3D viewer loads them fine:

[Open3Mod (Binaries)](http://open3mod.com/)
[Open3Mod (Git)](https://github.com/acgessler/open3mod)

Unpack example zips above into an assets folder and run this:

```
#Import "<std>"
#Import "<mojo3d>"
#Import "<mojo3d-loaders>"

#Import "assets/"

Using std..
Using mojo..
Using mojo3d..

' ----------------------------------------
' Application name...
' ----------------------------------------
 
Global AppName:String = "3d"

Function CenterModel:Void (model:Model, scale:Float)

	' Not bulletproof!
	
	model.Mesh.FitVertices (New Boxf (-10000, 0, -10000, 10000, scale, 10000), True)
	model.Position = Null
	
End

Class Game Extends Window

	Const SHIFT_BOOST:Float = 5.0
		
	' Basic 3D scene requirements...
	
	Field scene:Scene
	Field camera:Camera
	Field light:Light
 
 	Field camera_boost:Float = 1.0
 	
	Field car:Model

	Method New (title:String, width:Int, height:Int, flags:WindowFlags)
		
		Super.New (title, width, height, flags)
		
		scene = Scene.GetCurrent ()
		
			scene.ClearColor = New Color (0.1, 0.2, 0.75)
			
		camera = New Camera
 
			' Camera settings...
			
			camera.Near	= 0.1
			camera.Fov	= 60
		
			' Camera position...
			
			camera.Move (0, 5, -10)

		light = New Light
		
			light.Move (-50, 20, -50)
			light.ShadowsEnabled = False
			
'		car = Model.Load ("asset::car_sedan.fbx") ' Nope!
		car = Model.Load ("asset::car_sedan.dae") ' Yep!

'			CenterModel (car, 5)
	End
	
	Method UpdateGame:Void ()
		
	End
	
	Method OnRender (canvas:Canvas) Override
 
	 	ProcessInput ()
 		UpdateGame ()
 
 		RequestRender ()
	
		' Render scene to canvas (passed to OnRender by mojo), from camera...
		
		scene.Render (canvas, camera)
 
		' Tell app to draw frame when ready...
		
	End
	
	Method ProcessInput:Void ()

		If Keyboard.KeyHit (Key.Space) Then light.ShadowsEnabled = Not light.ShadowsEnabled

		If Keyboard.KeyDown (Key.LeftShift)
			camera_boost = SHIFT_BOOST
		Else
			camera_boost = 1.0
		Endif
		
		If Keyboard.KeyHit (Key.Escape) Then App.Terminate ()
		
		If Keyboard.KeyDown (Key.A)
			camera.Move (0.0, 0.0, 0.1 * camera_boost)
		Endif
 
		If Keyboard.KeyDown (Key.Z)
			camera.Move (0.0, 0.0, -0.1 * camera_boost)
		Endif
 
		If Keyboard.KeyDown (Key.Left)
			camera.Rotate (0.0, 1.0, 0.0)
		Endif
 
		If Keyboard.KeyDown (Key.Right)
			camera.Rotate (0.0, -1.0, 0.0)
		Endif
 
		If Keyboard.KeyDown (Key.Up)
			camera.Rotate (1.0, 0.0, 0.0, True)
		Endif
 
		If Keyboard.KeyDown (Key.Down)
			camera.Rotate (-1.0, 0.0, 0.0, true)
		Endif

	End

End
 
Function Main ()
 
	' Windowed mode...
	
	Local width:Int			= 640
	Local height:Int		= 480
	Local flags:WindowFlags	= WindowFlags.Center

	New AppInstance
	
	New Game (AppName, width, height, flags)
	
	App.Run ()
		
End

```

**OFF TOPIC:**

Had fun spawning 1000s of these (.dae) cars today, playing with ShadowsEnabled on/off to test speed, testing loading each copy separately versus single_model.Copy () -- which makes a huge difference -- but I notice it does slow a lot even with shadows off after a few thousand.

I thought the copy version might be using instancing (guess so?), but even with basic cubes it gets slow long before Blitz3D (which can be using separate CreateCubes for each), in low-to-mid 4-figure numbers.

Is it maybe just the case that frustum culling isn't yet implemented?

Also, any danger of an infinite plane like Blitz3D's? No other engine seems to support this -- I believe it was a nasty hack, but even if it were called NASTY_DEBUG_Plane, it would be great for demos. My 10,000 x 1 x 10,000 cube ground looked a real mess with shadows on :(

Cough... [Blitz3D PlaneModel](https://github.com/blitz-research/blitz3d/blob/master/blitz3d/planemodel.cpp)

**Comment by DruggedBunny** [comment]
Just tried latest after seeing addition of assimp loaders -- the fbx files in the low poly cars pack above loaded perfectly, though some other FBXs caused the same error, ie. `aiImportFile failed: path=[blah]cabrio.fbx`

However, I managed to add `aiGetErrorString` into assimp.bmx (woo!) and it then gives this:

```
FBX-DOM unsupported, old format version, supported are only FBX 2011, FBX 2012 and FBX 2013
```

So, seems to be working fine, and the failing models are just an older unsupported FBX format, so that at least explains that.

Blender models seem to load fine, at least in terms of meshes. Haven't seen any textures, but I don't think they get loaded by default (?) -- not sure if they have to be saved/applied separately, if they're part of the .blend file, etc? (Think so.)

However, decent models without textures look pretty cool!

![blendedhomer](https://user-images.githubusercontent.com/1781537/29687459-72a2eb5a-8914-11e7-9a09-558c53ece598.jpg)

So far, all .blends have consistently needed a model.Rotate (90, 0, 0) to show the right way up, so might be worth considering auto-correcting these on load. Everything else seems to load the right way up.

Ooh (90-degree-rotated .blend again)...

![gazvolga](https://user-images.githubusercontent.com/1781537/29688035-40acabe8-8916-11e7-8e5d-84f9b61e50b0.jpg)

FBX seems to load textures automatically (I even edited this one to partially pink):

![candycar](https://user-images.githubusercontent.com/1781537/29688261-050ac826-8917-11e7-88fc-673f75549eb3.jpg)

I think .blend is more of an overall 3D scene file, though, so maybe not ideal trying to load models direct from those...

Would consider fixed!

**Comment by DoctorWhoof** [comment]
I've only successfully loaded .obj files without materials so far... good to know about the FBX version, it would be great to get those error strings!

**Comment by DruggedBunny** [comment]
@DoctorWhoof -- this is how I got the error strings:

**1)** Add this to the very end of _modules\assimp\assimp.monkey2_

`Function aiGetErrorString:CString( )
`

(I think I had to rebuild modules after that -- pretty sure I just rebuilt them all, even though it takes forever! Not looked up how to just rebuild one module.)

**2)** Call it just after loading a model, like so:

```
result = Model.Load ("asset::blah.whatever")

Print assimp.aiGetErrorString ()
```

Oh, and you'd need to be running the _develop_ branch, at this point anyway, for fbx/blend support.

**Comment by blitz-research** [comment]
> So far, all .blends have consistently needed a model.Rotate (90, 0, 0) 

Models should be facing away from the camera by default when loaded, ie: you should be looking 'up their bum'. Does this achieve that?

> Function aiGetErrorString:CString( )

I didn't even know this existed! Will add this and auto print an assimp error message when assimp loader fails.

**Comment by DruggedBunny** [comment]
OK, might have to ditch this idea -- I did get my test models to mostly come out "up the bum" with `Rotate (90, 180, 0)`, but with further testing, the results aren't consistent.

What is consistent so far is that models with an obvious orientation (vehicles) never load up-the-bum by default, usually pointing straight down or across the screen!

My impression is that `Rotate (90, 180, 0)` is possibly right for models created in the ass-first orientation, but it's so hard to validate, especially since .blends can contain extensive scene/camera information, so that even loading a basic car model in Blender itself starts out with a dramatic low/45 degree angle.

_**I have noticed that textures are never loaded, not sure if this should happen automatically or not.**_

Wondering if Blender ought **not** to be treated as an actual model import format, since half the time it contains other scene information, such as backgrounds/container cubes for in-Blender rendering purposes, and sometimes has models separated out into parts that don't actually sit together by default (or sit in a big lump of meshes), etc, etc.

Loads of test models at [BlendSwap](https://www.blendswap.com/) after simple registration, with per-month download limits, but it seems .blend is far more appropriate for loading into Blender and then exporting as another format.

**Comment by blitz-research** [comment]
Thats cool, it's not too surprising really as there is no 'correct' orientation really.  I find 'up the bum' more logical because it means models are facing in the same direction as the camera, ie: +z=forward, -z=backward etc. But there's nothing stopping you writing a game where +x=forward, in which case models should be facing right instead of forward. So probably best to just leave it up to blender/assimp and user can rotate mesh or add a pivot if necessary.

Format-wise, the more the merrier I guess but some will be better supported than others. I suspect .blend has a reasonably complex format as its a full blown modeller format and probably has to manage modifier stacks and that sort of stuff, so I'm not surprised if its not 100% supported. Still, you'd expect textures to work? But if open3mod can't load textures (can it?) then assimp can't so we're hosed.

**Comment by DruggedBunny** [comment]
Yeah, I think you're right on all counts. Open3mod doesn't load the textures either... it looks like only .dae and .fbx actually load textures in assimp/o3mod! Nothing else has worked so far, weird. Maybe these ought to be the only 'recommended' assimp formats in the docs, otherwise you'll probably just hear the same thing over and over!
