### ISSUE TITLE
Bug: JSON parser crashes on \n \t etc.

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#208]
I have this json file.
```
{
    "ifn":"If v = Null\n\t${Cursor}\nEndif"
}
```
When I try to parse it by JsonObject.Parse() I get `Caught signal:Memory access violation`
If I replace \n with ~n I got ~n as is - two letters of text, not a break line symbol.

My temporary solution is replace \n\t by hand and parse resulting text:
`Local txt:=LoadString( jsonPath ).Replace( "\n","~n" ).Replace( "\t","~t" )`

**Comment by blitz-research** [comment]
As far as I can tell, the main problem here was json parser not recognizing
'\t' - fixed now in develop.

But the parser was also a bit quick to throw an exception I think - If it
didn't recognize an escape char following '\', it'd fail. I've made it a
bit more relaxed now, ie: if it doesn't recognize an escape code it'll just
leave the text alone (including '\').

Does this sound OK?


On Tue, Aug 22, 2017 at 7:40 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
Yes, it sound OK. :)
