### ISSUE TITLE
Ted2 Close Image Crash

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#21]
On MacOS when closing an open image Ted2 crashes here in imgdocument[90]

```
	If _image _image.Discard()
```

**Comment by blitz-research** [comment]
The problem was due to a GL call in a different thread.

Should be fixed now thanks to a complete rewrite of the fiber system.

**Comment by blitz-research** [comment]
...also, the new fiber system uses asm pinched from boost.

For raspberry pi fibers, you'll need to select the correct native/asm files (in modules/std/fiber) and #import them in native/fcontext.monkey2.

There *should* be asm suitable for Pi in there - if not we'll need to write our own!
