### ISSUE TITLE
Window Layouts (letterbox, etc.) don't seem to work with Mojo3D

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#211]
I get nothing rendered when I try any Layout other than "fill".
Thanks!

**Comment by blitz-research** [comment]
Letterbox layout is working here as long as I add an OnMeasure method, which views with letterbox/float layout should always implement.  Only views with fill Layout don't need to implement OnMeasure.

**Comment by DoctorWhoof** [comment]
Works fine with OnMeasure, forgot about that... thanks!
