### ISSUE TITLE
Structs in Select/Case gives error

### ISSUE THREAD

**Issue by noroads2015** [blitz-research/monkey2#216]
testing equality between Structs using If/Then works as expected, but using them in Select/Case throws a compiler error.
`
Namespace myapp

#Import "<std>"

Using std..

Struct Word
	Field _hi:Int
	Field _lo:Int
	
	Method New(num:Int)
		_hi = (num Shr 8) & $FF
		_lo = num & $FF
	End
End

Function Main()
	Local word1 := New Word($AABB)
	Local word2 := New Word($CCDD)
	Local word3 := New Word($CCDD)
	
	Print "If word1 = word2"
	If word1 = word2
		Print "equal"
	Else
		Print "not equal"
	End If
	
	Print "~nIf word3 = word2"
	If word3 = word2
		Print "equal"
	Else
		Print "not equal"
	End If
	
	Print "~nSelect word3"
	
' If statements work without error.  Uncomment the select statement to'
'see the error'
'	Select word3'
'		Case word1'
'			Print "word3 equals word1"'
'		Case word2'
'			Print "word3 equals word2"'
'		Default'
'			Print "word3 doesn't equal anything"'
'	End select'

End``
If you uncomment the Select/Case, you end up with this error
`Compiling...
Build error: System command 'g++ -c -std=c++11 -m32 -D_WIN32_WINNT=0x0603 -O3 -DNDEBUG -I"C:/Users/James/Monkey2-devel/monkey2/modules/" -I"C:/Users/James/Monkey2-devel/monkey2/modules/monkey/native" -I"C:/Users/James/Monkey2-devel/monkey2/tmp/" -o "C:/Users/James/Monkey2-devel/monkey2/tmp/untitled1.buildv1.1.07/windows_release/build/_1src_2untitled1_0untitled1.cpp.o" "C:/Users/James/Monkey2-devel/monkey2/tmp/untitled1.buildv1.1.07/windows_release/src/untitled1_untitled1.cpp"' failed.

g++ -c -std=c++11 -m32 -D_WIN32_WINNT=0x0603 -O3 -DNDEBUG -I"C:/Users/James/Monkey2-devel/monkey2/modules/" -I"C:/Users/James/Monkey2-devel/monkey2/modules/monkey/native" -I"C:/Users/James/Monkey2-devel/monkey2/tmp/" -o "C:/Users/James/Monkey2-devel/monkey2/tmp/untitled1.buildv1.1.07/windows_release/build/_1src_2untitled1_0untitled1.cpp.o" "C:/Users/James/Monkey2-devel/monkey2/tmp/untitled1.buildv1.1.07/windows_release/src/untitled1_untitled1.cpp"

C:/Users/James/Monkey2-devel/monkey2/tmp/untitled1.buildv1.1.07/windows_release/src/untitled1_untitled1.cpp: In function 'void bbMain()':

C:/Users/James/Monkey2-devel/monkey2/tmp/untitled1.buildv1.1.07/windows_release/src/untitled1_untitled1.cpp:29:13: error: no match for 'operator==' (operand types are 't_myapp_Word' and 't_myapp_Word')

   if(l_word3==l_word1){

      ~~~~~~~^~~~~~~~~

C:/Users/James/Monkey2-devel/monkey2/tmp/untitled1.buildv1.1.07/windows_release/src/untitled1_untitled1.cpp:31:19: error: no match for 'operator==' (operand types are 't_myapp_Word' and 't_myapp_Word')

   }else if(l_word3==l_word2){

            ~~~~~~~^~~~~~~~~



***** Fatal mx2cc error *****

Internal mx2cc build error`

Related thread on the M2 forums http://monkeycoder.co.nz/forums/topic/cant-use-color-in-selectcase-statement/

edit:sorry for the formatting issues.  Seems that github uses M2's comment character as formatting code.

**Comment by blitz-research** [comment]
Fixed in develop branch.
