### ISSUE TITLE
[Request] Mouse Double-Click (or button click counting)

### ISSUE THREAD

**Issue by chunkypixel** [blitz-research/monkey2#22]
For more advanced mouse scenarios I believe we will need the ability to count the number of mouse button clicks (I was interested in looking at adding a feature to Ted which allows you to double-click on a word and highlight it - great for copy/paste scenarios). Regardless potentially a wanted feature eventually.

SDL_MouseButtonEvent appears to have the ability to read this:
https://wiki.libsdl.org/SDL_MouseButtonEvent

**Comment by blitz-research** [comment]
Have added Click, DoubleClick and RightClick events, and MouseDown now has a 'Clicks' property if these aren't enough.

No way to poll for these yet, and I'm not sure if their should be.
