### ISSUE TITLE
Can't assign new material to loaded object

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#223]
If I load a  new object then assign a new material it does nothing:
```
Local mat :=  New PbrMaterial( True, False, False )
Local texture := New Texture( Pixmap.Load( "asset::default.png" ), TextureFlags.FilterMipmap )
mat.ColorTexture = texture

Local asteroid := Model.Load( "asset::asteroid.fbx" )
asteroid.Material = mat
```

However, creating a temporary model, copying its mesh to a box model, then assigning the material works:
```
Local mat :=  New PbrMaterial( True, False, False )
Local texture := New Texture( Pixmap.Load( "asset::default.png" ), TextureFlags.FilterMipmap )
mat.ColorTexture = texture

Local temp := Model.Load( "asset::asteroid.fbx" )
temp.Visible = False

asteroid = Model.CreateBox( New Boxf( -1,-1,-1,1,1,1 ), 1, 1, 1, mat  )
asteroid.Mesh = temp.Mesh
asteroid.Material = mat
```

**Comment by blitz-research** [comment]
Model has 2 material related propeties: Material and Materials[]

Material is the 'default' material for any triangles in the mesh with a
materialid outside the range of the Materials[] array.

The various model loaders all correctly initialize the Materials[] array,
so Material is never actually needed. So this should fix the problem:

asteroid.Materials=New Material[]( mat )

...or this...

asteroid.Materials=Null
asteroid.Material=mat

The idea here was to make it easier to handle single material meshes, eg:
you can have an empty Materials[] array and just use Material if you want.
This is what the CreateBox etc functions do.

But it's probably too confusing. Might be best to just stick with a
Materials[] array, and use an 'error' material if the mesh needs more
materials than are provided.

**Comment by DoctorWhoof** [comment]
Ah, understood. Having a simple materials array would work for me. Thanks!

**Comment by blitz-research** [comment]
If you only ever use Materials array, it should all work anyway.
