### ISSUE TITLE
SkyTexture overrides EnvTexture

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#224]
If I set just the env texture, it works;
```
Scene.EnvTexture = New Texture( Pixmap.Load( "asset::interior.png"), TextureFlags.Cubemap )
```

But If I also set the sky texture, the sky texture replaces the environment texture and is used in both places!
```
Scene.SkyTexture = New Texture( Pixmap.Load( "asset::stars.png"), TextureFlags.Cubemap )
Scene.EnvTexture = New Texture( Pixmap.Load( "asset::interior.png"), TextureFlags.Cubemap )
```

A typical use case for different Sky and Environment textures is a room where you can see the sky outside. The sky is the SkyTexture, but the reflection on the objects inside need a different texture that includes the room itself, so that the objects inside don't appear too bright.

It's nice that the env texture is set automatically from the sky, but that should only be the case if the env texture is null or the same as the sky.

**Comment by blitz-research** [comment]
Totally agree and its actually supposed to work this way - will investigate.

**Comment by blitz-research** [comment]
Ok, fix pushed to develop branch, it'll also be in the next release
hopefully later today. Material/Materials fix will have to wait for a bit.

**Comment by DoctorWhoof** [comment]
Seems to work now, thanks.
