### ISSUE TITLE
BigEndian  DataBuffer constructor bug

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#225]
the _swapEndian member of dataBuffer is always initialized as False

request - any chance of a PeekCString that reads null terminated strings?

**Comment by blitz-research** [comment]
Fixed, and PokeCString/PeekCString added.

**Comment by nitrologic** [comment]
Woot!

**Comment by blitz-research** [comment]
Actually, just looking at DataBuffer now and PokeString/PeekString already
use cstrings! Will have a think about this, but reverting
PokeCString/PeekCString for now.

**Comment by blitz-research** [comment]
Ok, we do still need PeekCString...!

**Comment by blitz-research** [comment]
Ok, PokeCString/PeekCString are back.

The difference between PokeString and PokeCString is that PokeString does
NOT append a null terminator  (so you need to deal with lengths on your
own). PokeString  assumes strings may contain \0 chars. Null is actually a
valid utf8/String character, but is not valid in CStrings (going by monkey2
terminology here).

Just stick with PokeCString and PeekCString and you'll be fine.

Forgot about all this crap...
