### ISSUE TITLE
[request] Add signal Rendered:Void( canvas:Canvas ) to mojox.View

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#227]
Use case:
Working on draggable tabs I need to render semi-transparent rect above the tabs parent to show users which areas allow to drop tab.

**Comment by engor** [comment]
Also using this signal we can grab rendered view into pixmap.

**Comment by engor** [comment]
Not urgent, I wrote simple extended class for first time.
```
Class DockingViewExt Extends DockingView
	Field Rendered:Void( canvas:Canvas )
	Protected
	Method OnRender( canvas:Canvas ) Override
		Super.OnRender( canvas )
		Rendered( canvas )
	End
End
```

**Comment by engor** [comment]
I have no luck this that. So if I'm the only who want it - ignore.

**Comment by blitz-research** [comment]
Not totally adverse to the idea, but not sure if this should be part of the existing OnRender process, which os only meant to be for rendering the view.
