### ISSUE TITLE
mojox requeststring 

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#228]
In following code pressing F1 then Escape key causes a Key.Escape KeyUp event to be delivered to mainwindow.

```
#Import "<std>"
#Import "<mojo>"
#Import "<mojox>"

Class AppWindow Extends mojo.app.Window
	Method RequestString()
		Local result:=mojox.RequestString("enter name","enter name escape will kill app")
	End

	Method OnKeyEvent(event:mojo.app.KeyEvent) Override
		If event.Type=mojo.app.EventType.KeyUp
			Print "KeyUp"
			Return			
		endif
		If event.Key=mojo.input.Key.F1
			New std.fiber.Fiber(RequestString)
		endif
	End
	
	Method OnRender(canvas:mojo.graphics.Canvas) Override
		canvas.DrawText("F1 - request string",0,0)
	end
End

Function Main()
	New mojo.app.AppInstance
	New AppWindow()
	mojo.app.App.Run()
End

```

**Comment by nitrologic** [comment]
Actually both Enter and Escape keys during request send KeyUp event to main window. 

Action on KeyDown for mojox buttons does provide spontaneous response but as mojox buttons wait for MouseUp they should/could wait for KeyUp also.

**Comment by blitz-research** [comment]
Use '3 backticks` (I think) to enclose code please!

**Comment by nitrologic** [comment]
I thought I fixed that after posting?

**Comment by blitz-research** [comment]
Ahh, sorry, using email so still looking at original post I guess.

**Comment by blitz-research** [comment]
Potential fix pushed: mojo now only sends keyups to same view as keydowns,
as problem was due to dialog closing between keydown/keyup.

**Comment by nitrologic** [comment]
Nearly. If you hold key down now so auto repeat happens (windows) you never get keyup event.

**Comment by blitz-research** [comment]
Attempt 2 pushed...

**Comment by nitrologic** [comment]
new version is awesome, thanks!
