### ISSUE TITLE
Importing "<mojo3d-physics>" causes Reflection to crash

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#229]
Steps:
- Open a source file that uses "reflection" (as little as "Typeof" should be enough)
- Import "mojo3d-physics"
- Build
- Crash!

The above steps cause a crash in 1.1.06 develop branch from September 15th, MacOS.
Confirmed on the "reflectiontest.monkey2" banana. The crash log is so long I won't even post it here.

**Comment by engor** [comment]
Also, adding `#Import "<reflection>"` in ted2go project causes build crash - `Fatal mx2cc error`.

**Comment by blitz-research** [comment]
Ok, in the process of getting these working.

One of the (several) issues with Ted2go is that Interface ITest in
ParserTest.smonkey2 has a property called bpp with void type. This should
(and will) be illegal so this will need to be fixed.

On Fri, Sep 22, 2017 at 2:51 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
Tx!

**Comment by blitz-research** [comment]
Oh, and I meant several issues with mx2 reflection, not ted2go!

**Comment by engor** [comment]
But you shown me the bad place in ted2go, so fixing it I can use reflection right know. :)

**Comment by blitz-research** [comment]
Well, maybe, there are probably more issues with reflection in there. In
particular, in debug mode it causes an 'object file too big' assembler
error I've never seen before! I'd hold off on trying to use reflection with
ted2go for a while yet.


On Fri, Sep 22, 2017 at 8:23 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
I wanted to know object type only by `Typeof( item ).Name` (to print and see what happen).
Without reflection it always gives me `Object`.
Now with reflection (in release mode), I got `mojo.app.View` for mojox.Label.
Kind of bug.

**Comment by blitz-research** [comment]
Oh yes, there's lots to be fixed! Actually, that should work and does here....

```
Local label:=new Label
Print Typeof( label )  'prints mojox.Label
```

Remember, Typeof( is the static type of an expression, so this will print mojox.View:

```
Local label:View=New Label
Print Typeof(label)
```

On Fri, Sep 22, 2017 at 8:57 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by blitz-research** [comment]
Should be fixed now, needed to turn off reflection of 'native' classes.

This might actually be possible eventually...
