### ISSUE TITLE
Image.Scale property not working with negative values

### ISSUE THREAD

**Issue by jondecker76** [blitz-research/monkey2#23]
Trying to use the Image.Scale property to mirror an image using negative values does not work.

Example code:
`
Namespace myapp

#Import "<std>"
#Import "<mojo>"
#Import "monkey2_64.png"

Using std..
Using mojo..

Class MyWindow Extends Window
	Field img:Image
	
	Method New()
		Super.New("Test",640,480)
		img=Image.Load("asset::monkey2_64.png")
	End
	
	Method OnRender( canvas:Canvas ) Override
		If Keyboard.KeyDown(Key.Space)
		  Print("Flipping image on X axis...")
		  img.Scale=New Vec2f(-1.0,1.0)
		Else
		  img.Scale=New Vec2f(1,1)
		Endif
		
		canvas.DrawImage(img,0,0)	
		App.RequestRender()
	End
	
End

Function Main()

	New AppInstance
	
	New MyWindow
	
	App.Run()
End
`

**Comment by blitz-research** [comment]
It's because the handle is 0,0 and the image is drawn at 0,0.

Try Drawimage( img,100,100 )...
