### ISSUE TITLE
Option for Anisotropic filtering is necessary

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#230]
I'm getting super blurry mipmapped textures when looking at textured polygons at an angle. Here's a test pattern image:
<img width="1392" alt="screen shot 2017-09-17 at 1 11 20 am" src="https://user-images.githubusercontent.com/6250116/30519246-ceb296dc-9b45-11e7-8e28-288631bf9d48.png">
Turning off mimapping makes it sharp, but flickers a lot:
<img width="1392" alt="screen shot 2017-09-17 at 1 13 08 am" src="https://user-images.githubusercontent.com/6250116/30519251-e6b509b8-9b45-11e7-8c81-7eaa03d4e385.png">

OpenGL seems to handle anisotropic filtering without problems, but I have no idea how to implement this: https://gamedev.stackexchange.com/questions/69374/how-to-achieve-anisotropic-filtering

Thanks!

**Comment by blitz-research** [comment]
Just in the process of implementing this, though it may not be too flexible
to start with.

Just curious though, how did you get the 'solid black' lighting? Did you
create a black envtexture? That's the only way I can think of doing it, and
I'm thinking of adding EnvColor to scene too, mainly so you can easily turn
it off env.

Show env be off by default? There's currently a default env texture, but
this could be black? Just worried it might be a bit tricky to setup.

**Comment by DoctorWhoof** [comment]
Yeah, I'm using a black texture map. I don't mind the default environment, I believe most people will like the more realistic looking default setting anyway. I only turned it off because most of my testing has been focused on non-photoreal stuff.

(I also used the same texture as emissive, and set the emissive factor to values above 1.0, for that extra bright, 80's feel).

Eventually I'm gonna try to create some non-photoreal materials/shaders, but since II'm not there yet, setting the environment to black works fine for now.

Thanks Mark!

**Comment by blitz-research** [comment]
Semi-fixed - anistropic is now forced to  max by default, see new anisotropic mojo3d test.

Also added an EnvColor mainly so you can set env to black easily but might be generally useful. So you can now get a 100% black, unlit scene  using:
```
scene.EnvColor=Color.Black
scene.ClearColor=Color.Black
scene.AmbientLight=Color.Black
```
