### ISSUE TITLE
mojo3d docs missing module.md

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#231]
If file module.md is added to modules/mojo3d/docs it seems to fix quick help in Ted2Go for PbrMaterial and company.

**Comment by blitz-research** [comment]
Is this 'F1' help? Seems to be working here - if I type 'PbrMaterial' into
an empty file and hit F1 once I get quick help in status bar, twice and I
get PbrMaterial docs in lower help pane.

It shoudn't need module.md anyway, that should be for optional module docs.

**Comment by nitrologic** [comment]
A previous update docs must have failed for some other reason, sorry for the bother.
