### ISSUE TITLE
Uniform "OcclusionTexture" names don't match

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#232]
In file pbrmaterial.monkey2, the line:
```Return Uniforms.GetTexture( "occlusion" )```
Should say:
```Return Uniforms.GetTexture( "OcclusionTexture" )```

Since it's named "m_OcclusionTexture" in shader. I kept getting errors from it when I use reflection to get the value from all of a PbrMaterial's properties.

**Comment by blitz-research** [comment]
Fixed in latest develop branch.
