### ISSUE TITLE
MojoX module: htmlview_test.monkey2: No output in "htmlview Demo" window.

### ISSUE THREAD

**Issue by TurkeyLurker** [blitz-research/monkey2#234]
C:/Monkey2/modules/mojox/tests/htmlview_test.monkey2 doesn't show any html output when you run the test.  The "About monkey2" and "About ted2go" both show html in Ted2Go 2.5.  Only failure is in htmlview_test.monkey2.

![htmlviewnowork](https://user-images.githubusercontent.com/30769581/30629710-5f55b072-9dab-11e7-8fb9-47d552eb6ef1.png)

**Comment by blitz-research** [comment]
Fixed - HtmlView.Go() path needs to be "asset::about.html".
