### ISSUE TITLE
[req] Bool-to-string conversion

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#236]
Is it possible to auto-convert bool into 'true' / 'false' inside of string expression?
```
Local b:=True
Print "b: "+b
```
This time we get: `Error : Value cannot be implicitly cast from type 'Bool' to type 'String'`

**Comment by DoctorWhoof** [comment]
Vote up!

**Comment by blitz-research** [comment]
No voting allowed: it's not a democracy!

**Comment by engor** [comment]
:)))

**Comment by blitz-research** [comment]
It'll probably happen eventually though...
