### ISSUE TITLE
Can't build Android modules

### ISSUE THREAD

**Issue by Mac767** [blitz-research/monkey2#237]
Hi,

since a few days I can no more build Android modules.
Error message:

Mx2cc version 1.1.08

***** Making module 'monkey' *****

Parsing...
Semanting...
Translating...
Compiling...
Build error: System command 'ndk-build' failed.

ndk-build

make: *** No rule to make target `jni/monkey_monkey.cpp', needed by `obj/local/armeabi-v7a/objs/mx2_monkey/monkey_monkey.o'.  Stop.

kind regards
Tobias

**Comment by blitz-research** [comment]
Can you try again, think I just forgot to commit a file.

**Comment by Mac767** [comment]
I can build android modules, again!
Thanks for the fast bug fix!
