### ISSUE TITLE
Reflection fails with Class Extensions and Enums

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#239]
My Serialization module is almost done! I can live without generics' reflection, but Class extensions (more important) and Enums (less important) would make my life much easier.

```
#Import "<std>"
#Import "<reflection>"

Using std..

Function Main()
	
	Local t := New Test
	For Local d := Eachin t.InstanceType.GetDecls()
		Print d	
	End
	
End


Class Test
	Field a:Int
	Field b:Int
	Field style:Style
	
	Method Get:Test()
		Return Self
	End
End


Class Test Extension
	'This is ignored
	Method Sum:Int()
		Return a+b
	End
End

'This is reflected as "Unknown"
Enum Style
	Light,
	Medium,
	Dark
End
```

**Comment by DoctorWhoof** [comment]
Sorry to keep asking for this, but I keep hitting this problem and it's becoming hard to circumvent it. Support for at least Properties in Class extensions would be very welcome for me right now!

Thanks!

**Comment by blitz-research** [comment]
I'll have to set aside some serious time for this so it'll be a while off yet sorry.

What are you trying to do exactly? There may be another approach, and besides I have no idea what exactly people are expecting here...

Not totally sure how useful property extensions are anyway as extensions can't add fields.

**Comment by DoctorWhoof** [comment]
Here's a little example. I have a Json.Serialize( v:Variant) extension. It takes any object and spits out its settable fields and properties. If I use it on a PbrMaterial, I get this:
```
{
	"Class":"mojo3d.PbrMaterial",
	"ColorFactor":{
		"A":1,
		"B":0.19215686619281769,
		"Class":"std.graphics.Color",
		"G":0.12941177189350128,
		"R":0.12941177189350128,
		"a":1,
		"b":0.19215686619281769,
		"g":0.12941177189350128,
		"r":0.12941177189350128
	},
	"ColorTexture":{
		"Class":"mojo.graphics.Texture"
	},
	"EmissiveFactor":{
		"A":1,
		"B":0,
		"Class":"std.graphics.Color",
		"G":0,
		"R":0,
		"a":1,
		"b":0,
		"g":0,
		"r":0
	},
	"EmissiveTexture":{
		"Class":"mojo.graphics.Texture"
	},
	"MetalnessFactor":0,
	"MetalnessTexture":{
		"Class":"mojo.graphics.Texture"
	},
	"NormalTexture":{
		"Class":"mojo.graphics.Texture"
	},
	"OcclusionTexture":{
		"Class":"mojo.graphics.Texture"
	},
	"RoughnessFactor":0.82139015197753906,
	"RoughnessTexture":{
		"Class":"mojo.graphics.Texture"
	}
}
```

I don't get any usable information from the textures, so I created a Texture manager that assigns names to the textures so you can retrieve them by name later. With that, I made a Texture extension that adds the "Name" property to textures, and the strings are stored not in the texture itself, but in the manager class.

But since the Reflection can't see the added property, I'm left with handling lots of "special case" classes whenever I need to extend things.

I can, of course, wrap everything in my own classes like "MyTexture", "MyMaterial", etc, but not only that adds a ton of work, I've been really trying to create general purpose modules (Serializer, MaterialLibrary, GameObjects, etc.) that simply use as much as possible the standard Monkey2 classes.

Anyway, I'm probably being dumb and there's a better way. But you can peek the WIP Serializer module here:https://github.com/DoctorWhoof/Serializer/blob/master/serializer.monkey2
The main file, a Json extension, is pretty self explanatory, and there are a couple simple test files.

**Comment by DoctorWhoof** [comment]
AH, I forgot to ask: Maybe a better solution is to extend all classes I need with "Serialize" and "Deserialize" methods?... anyway, I appreciate any feedback.

**Comment by blitz-research** [comment]
Ok, had a hack at this last night and made some pretty good progress.

Not sure what you were expecting but I decided to keep it as simple as for
now. Each extension is it's own type so you currently have to use
Typeinfo.GetTypes() to 'search' for extensions. This sounds a lot like how
c# does it I think:

https://stackoverflow.com/questions/299515/reflection-
to-identify-extension-methods

The Kind of an extension Typeinfo is "Blah Extension", eg: "Class
Extension", and the SuperType is the actual type the extension is for.

The Name is current just the SuperTypoe name with " Extension" suffix, but
this could change - best to just compare SuperType.

There's a little demo in src/mx2cc dir but note  have only really tested
with properties and methods so far. Will eventually get back into it but
other stuff is piling up and that'll have to do for now, have a play and
post impressions/bugs.

Still enums to go, urgh....

**Comment by DoctorWhoof** [comment]
You're too kind, Mark. Thanks! :-)
Gonna test it tonight...

**Comment by DoctorWhoof** [comment]
It looks like the changes will be good enough for me, but...
There's a giant compiler error (too big to post) when I import and reflect Mojo3D.

I added Mojo3D in this test (didn't actually do anything with it, just imported and reflected) and it causes the error. Commenting out Mojo3D lines works:
https://github.com/DoctorWhoof/Serializer/blob/master/tests/serialTest2.monkey2

(you need the Serializer repo, https://github.com/DoctorWhoof/Serializer)

Reflecting "std.." and "mojo.." compiles without problem, Mojo3D seems to be the only one causing trouble!

**Comment by DoctorWhoof** [comment]
This simpler example gives me the giant compiler error. Simply commenting out "#Reflect mojo3d.." passes.
```
Namespace myapp3d

#Import "<std>"
#Import "<mojo>"
#Import "<mojo3d>"

#Reflect mojo3d..

Using std..
Using mojo..
Using mojo3d..

Class MyWindow Extends Window
	
	Field _scene:Scene
	Field _camera:Camera
	Field _light:Light
	Field _donut:Model
	Field _material:PbrMaterial

	Method New( title:String="Simple mojo3d app",width:Int=640,height:Int=480,flags:WindowFlags=WindowFlags.Resizable )
		Super.New( title,width,height,flags )
		_scene=Scene.GetCurrent()
		_scene.ClearColor=Color.Black
		
		'create camera
		_camera=New Camera
		_camera.Near=.1
		_camera.Far=100
		_camera.Move( 0,10,-10 )
		_camera.AddComponent<FlyBehaviour>()
		
		'create light
		_light=New Light
		_light.Rotate( 45, 45, 0 )
		
		_material = New PbrMaterial( Color.Red, 0.1, 0.25 )
		_material.EmissiveFactor=New Color( 0,.25, 0 )
		
		_donut=Model.CreateTorus( 2,.5,48,24,_material )
		_donut.Move( 0,10,0 )
	End
	
	
	Method OnRender( canvas:Canvas ) Override
		RequestRender()
		_donut.Rotate( .2,.4,.6 )
		_scene.Update()
		_scene.Render( canvas,_camera )
		canvas.DrawText( "Width="+Width+", Height="+Height+", FPS="+App.FPS,0,0 )
	End
	
End

Function Main()
	New AppInstance
	New MyWindow
	App.Run()
End
```
Just to be sure, I removed all *buildv* folders from both the modules and my projects, and rebuilt Monkey2.

 Thanks!

**Comment by blitz-research** [comment]
Hey, just working on this and have it sort of sussed.

But I've just noticed v1.1.09 is printing very different type names for
'unreflected' types like Vec3f etc than 1.1.08 does. v1.1.09 prints 'void'
while 1.1.08 prints 'unknown@blah' - I have I broken something else here?

Which version have you been using? Have you stuck with 1.1.08 or been
updating to develop?

**Comment by blitz-research** [comment]
Ok, nevermind, just had little panic there, things are back to being merely
confusing...might need another day to get it working though.

**Comment by DoctorWhoof** [comment]
I've been using the latest dev branch and haven't seen 'unknown@blah' types in a while - I've even had added some code that checks for 'void' types a while ago. I don't think it's a result of the recent changes.
 
EDIT - I wasn't seeing those cases because I was checking for them and not printing anything out...

**Comment by DoctorWhoof** [comment]
Yay, working so much better now! I can get declarations in class extensions just fine! :-)
Haven't tried to serialize enums yet, but they seem to be working too. I need to go to bed.

Out of curiosity, is getting some sort of reflection for generics super hard? Impossible?
Just checking...

Feel free to close if you don't think it needs any more work.
Thanks!

**Comment by blitz-research** [comment]
The main problem with reflecting generics is that they generate a shed load
of data, esp. with types that contain other types. For every instance of
List<T> generated, there also need to be List<T>.Iterator and List<T>.Node
generated etc.

Both msvc and mingw compilers generate 'object file too large' style errors
when I try to reflect *everything* in just std alone. Msvc has a /bigobj
option, with mingw I think you're basically fubarred. Not sure what the
situation is on macos/linux but I doubt it's pretty.

So ultimately, reflection for generics will require more #Reflect fudgery
to limit the amount of data generated, perhaps you have to explicitly
#Reflect every generic instance type you want reflected? But that will have
to wait as I'm way behind on other stuff.

**Comment by DoctorWhoof** [comment]
No problem, thanks for the info!

**Comment by DoctorWhoof** [comment]
So sorry to bug you one more time.. I promise I'll stop after this one!

I couldn't figure out how to get the value of a field containing an Enum. It seems you need to cast the variant to get that, but what if I want to have a function that takes any variant as an input - in other words, I can feed it any Enum type? Can you cast to a TypeInfo?

This is probably less confusing: A function that would return the Enum's value as a string.
```
Function EnumValue:String( v:Variant )
	Local value := ""
	
	If v.Type.Kind = "Enum"
		'What do I do here?
	Else
		value = "Not an Enum!"
	End	

	Return value	
End
```

This is breaking my brain. Reflection is hard.

**Comment by blitz-research** [comment]
Good point, will look into it.

**Comment by blitz-research** [comment]
Ok, just finishing a fix now. Seems to work OK...

Use the Variant.EnumValue property to get the integer value of an enum
variant. Variant must be an enum or you'll get a runtime error.

Use the TypeInfo.MakeEnum:Variant( enumValue:Int ) method to create an enum
variant from an integer value. Again, TypeInfo must be an enum type.

I guess Method TypeInfo.MakeEnum could be Function Variant.FromEnumValue
instead, dunno. Let's go with MakeEnum for now.

See new enum test in reflection module...

> This is breaking my brain. Reflection is hard.

No kidding!
