### ISSUE TITLE
Fullscreen using Letterbox = blank screen

### ISSUE THREAD

**Issue by chunkypixel** [blitz-research/monkey2#24]
This might be a possible bug (appears confirmed by Pakz).

If you start with the window as Resizable then change to Fullscreen (F12) it renders ok, but if you start on Fullscreen it displays nothing.

Code here:
http://monkey2.monkey-x.com/forums/topic/bug-fullscreenresizable-blank-screen/#post-1833

**Comment by blitz-research** [comment]
You need to implement OnMeasure:Vec2i() when using "letterbox" layout.
