### ISSUE TITLE
mx2cc is hard coded to use modules/

### ISSUE THREAD

**Issue by therevills** [blitz-research/monkey2#240]
Trying to create a batch file so I dont have to copy my modules every time there is a new MX2 version:

echo off
set current_path=%cd%
echo "current_path = %current_path%"

cd %current_path%

For /F "tokens=1* delims==" %%A IN (makediddy2.properties) DO (
    IF "%%A"=="mx2cc_path" set mx2cc_path=%%B
)

echo "mx2cc_path   = %mx2cc_path%"

cd %mx2cc_path%
mx2cc_windows.exe makemods %current_path%\diddy2
pause

makedidd2.properties has the mx2cc_path:
mx2cc_path=E:\Dropbox\CodeMonkey\mx2\Monkey2-v1.1.07\bin

But with mx2cc the "makemods" command is hard coded to look in modules/ folder, which causes my script to fail.

`Local path:="modules/"+modid+"/"+modid+".monkey2"`

**Comment by blitz-research** [comment]
You can no use MX2_MODULE_DIRS in you env_blah.txt file, eg:

MX2_MODULE_DIRS=modules;modules_ext
