### ISSUE TITLE
mojox.GridView calculating cell frames wrong

### ISSUE THREAD

**Issue by seankarol** [blitz-research/monkey2#243]
It appears that mojox.GridView is measuring the cells frame y0 by _gridw rather than _gridh

https://github.com/blitz-research/monkey2/blob/c94af9e75387b7dd3063879788afae870f3f569b/modules/mojox/gridview.monkey2#L101

**Comment by blitz-research** [comment]
Complete correct, well spotted! Fixed in develop branch.
