### ISSUE TITLE
Can't run develop Ted2: "libgcc_s_dw2-1.dll is missing"

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#244]
I built develop about 2 days ago, but the end result is that Monkey2 (Windows).exe (well, ted2.exe) gives this error, which sounds like some sort of linking problem:

https://stackoverflow.com/questions/4702732/the-program-cant-start-because-libgcc-s-dw2-1-dll-is-missing

I noticed I had to change bin\env*.txt to point to devtools\i686-6.2.0-posix-dwarf-rt_v5-rev1 to build in the first place, as it was pointing to some other form of MinGW. Is that intentional/related?

Couple of other things:

1) Is devtools' Ted2 actually the latest Ted2Go or still the old one (can't test)? I've had problems adding and running ted2go to it before, not quite clear which it uses since both sets of source are included -- reads as if it's old ted2.
2) Is there an easier way to upgrade develop without having to rebuild the whole lot, as it takes somewhere around 30-45 minutes here, on a reasonably powerful PC! That's using rebuildall.bat, not sure if actually necessary? It doesn't seem to skip modules that are already built, which is what I'd expect -- does one of the other .bats do this?

**Comment by blitz-research** [comment]
Wha is the filesize of bin/ted2_windows/Ted2.exe? Are you sure this is the one causing the problem, ie: can you run it directly, or does the problem only happen when you run the launcher in the root dir.

PE Explorer is a great tool for examining EXEs to tell what dependancies they have. A quick look at Ted2.exe here suggests it's OK, but will keep looking.

What devtools' Ted2 do you mean? I don't have aTed2 in my devtools dir, only i686-6.2.0-posix-dwarf-rt_v5-rev1 and msever-v86c dirs.

**Comment by blitz-research** [comment]
As for slow rebuild times, you  could always try just updating modules after a git pull. This will probably work 70% of the time BUT if you do this, please try a rebuildall2go before posting any bug reports. Rebuilding all is really the only way to guarantee people have a stable version of the develop branch after an update, as literally anything couldv'e changed as this *is* development code! The compiler can change, core modules can change, env_windows.txt can change etc. git pull output can also give you hint here.

**Comment by DruggedBunny** [comment]
Yes, the error comes up if I run ted2.exe directly, so think it's that rather than the launcher.

Sorry, meant develop branch ted2 -- is that still the old pre-ted2go, ie if I want latest ted2go I should be downloading and installing that separately?
 
I'll give the rebuild modules thing a go, caveat noted!

I have been doing rebuild all every time until now, but it takes so long that I just don't have the will to test/tweak and then go through it all again (or even do it every time I download latest develop!), so will see how that goes.

Is the posix-dwarf thing still the recommended mingw for now? That threw me, because the env file was pointing to something else when I last downloaded develop and so it didn't even build initially.

**Comment by blitz-research** [comment]
> if I want latest ted2go I should be downloading and installing that separately?

ted2go is included in develop branch of monkey2 in the src dir:

https://github.com/blitz-research/monkey2/tree/develop/src

It is built by the 'rebuildall2go' script. Plain 'rebuildall' will build old/original ted2.

[edit]Both ted2 and ted2go are called Ted2.exe when built, which may be confusing you? Also, if you want 'bleeding edge' ted2go, then yes, you'll have to grab it from ted2go repos. However, the version in monkey2 is quite up to date.[/edit]

>Is the posix-dwarf thing still the recommended mingw for now? 

You should install the version of mingw found here...

http://monkeycoder.co.nz/monkey2-files/

...into your devtools dir and everything should just work (unless you've messed with env_windows.txt or something). The 'installer' will create a dir called i686-6.2.0-posix-dwarf-rt_v5-rev1 inside devtools. The   bin/env_windows.txt file adds this dir to PATH so mx2cc can find the correct gcc etc.

Pretty sure this is all covered in the README:

https://github.com/blitz-research/monkey2/blob/develop/README.TXT

Could you send me your bin/ted2_windows/Ted2.exe file somehow?

**Comment by DruggedBunny** [comment]
Thanks, Mark. I did have it all set up correctly before (was copying i686-6.2.0-posix-dwarf-rt_v5-rev1 from the itch.io releases into devtools), but somehow seems to have ended up out of whack.

I've just started from scratch and got it working right away. (And got smarter in placing devtools a level above the main folder, editing the env file to suit.)

1) Running rebuildall2go.bat got it working no problem;
2) Then, running updatemods.bat to test module re-build times did still build quite a few modules, but most were ready-to-go;
3) Running updatemods.bat again then successfully skipped all modules.

Not sure why a few weren't built in 2), though -- sdl-truetype, reflection, theoraplayer are a few that had to be built on the second run.

Anyway, it does look to be working as advertised, so I'm going to shut up now! Just seems to have been one of those things that crept out of line...

Close me! (Not sure if you see response if I close the issue directly?)

**Comment by blitz-research** [comment]
Glad you got it working. Is the original problem solved? Are you still
getting dll required messages?

You need at least 2 builds for the build cache to 'warm up'. If you sit
there typing 'updatemods' it should be pretty quick by about the 3rd build!

**Comment by DruggedBunny** [comment]
Yes, all working, no DLL message now!

Yep, looks like it should be fine when it comes to a few mods updating. Thanks again!
