### ISSUE TITLE
Commenting blocks via /* */

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#245]
What about adding `/* */` for commenting blocks?
* These combinations didn't used in mx2 yet.
* It's short and world-wide known.
* Easy to parse.
* It allow us to comment single line middle part:
```
Local arr:=New String[]( "one",
  "2",
  /*"five",*/
  "zero" )
```
We can't do it with `'` or `#Rem`.

**Comment by blitz-research** [comment]
Yeah, nah, not really a fan of comments in the middle of a line - never use them myself, and find them pretty ugly when I see them in 3rd party code (but that goes for 90% of c++). Plus, it just doesn't seem very monkey-ish...

Also note that a single ' works in your example anyway.
