### ISSUE TITLE
Shadows not working on latest dev branch?

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#246]
I have v1.1.08, built from dev branch about a day ago. Lights casting shadows don't seem to work in my files, or in any Banana example. On macOS High Sierra.

Thanks!

**Comment by blitz-research** [comment]
Oops, sorry, CastsShadow was defaulting to false for renderables - fixed in
develop branch.

**Comment by DoctorWhoof** [comment]
Works now. Thanks!
