### ISSUE TITLE
Boolean Variant always returns true

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#247]
In the code below, I can't figure out a way to obtain the boolean value from the variant. The cast to boolean is successful, so it seems to always return true, even if the Boolean variable is false. Not sure if a bug or a feature! :-)
```
Function Main()
	
	Local value := False
	
	Local v := Variant( value )
	
	Local castValue := Cast<Bool>( v )
	
	'This prints false
	Print ( "value: " + ( value? "true" Else "false" ) )
	
	'But this prints true
	Print ( "castValue: " + ( castValue? "true" Else "false" ) )
	
End
```

**Comment by blitz-research** [comment]
Nice find! Fixed in develop.
