### ISSUE TITLE
Can't handle german umlaute

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#248]
First added as IDE issue:
https://github.com/engor/Ted2Go/issues/59

To reproduce:
`SaveString( "test data","löss.txt" )`
note the filename `ö`.
I got `lГ¶ss.txt` saved on disk.

More info:
https://en.wikipedia.org/wiki/Germanic_umlaut

**Comment by blitz-research** [comment]
Working now?

**Comment by engor** [comment]
It works now.
