### ISSUE TITLE
Can't build current develop branch

### ISSUE THREAD

**Issue by TurkeyLurker** [blitz-research/monkey2#250]
I was wanting to test the new Music bananna, but I get the following errors when trying to build the current develop branch (from web clone):

C:\monkey2-develop\scripts>rebuildmods

C:\monkey2-develop\scripts>echo off

***** Rebuilding modules *****

Mx2cc version 1.1.08

***** Making module 'monkey' *****

Parsing...
Semanting...
Translating...
Compiling...
Build error: System command 'g++ -c -std=c++11 -m32 -D_WIN32_WINNT=0x0603 -O3 -DNDEBUG -I"C:/monkey2-develop/modules/" -I"C:/monkey2-develop/modules/monkey/native" -o "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/build/monkey_0monkey.cpp.o" "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/src/monkey_monkey.cpp"' failed.

g++ -c -std=c++11 -m32 -D_WIN32_WINNT=0x0603 -O3 -DNDEBUG -I"C:/monkey2-develop/modules/" -I"C:/monkey2-develop/modules/monkey/native" -o "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/build/monkey_0monkey.cpp.o" "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/src/monkey_monkey.cpp"

Assembler messages:
Fatal error: can't create C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/build/monkey_0monkey.cpp.o: Permission denied

***** Fatal mx2cc error *****

Internal mx2cc build error

**Comment by therevills** [comment]
Are you running any anti-virus/anti-malware? I havent tried building MX2 for ages, but I sometimes get that error when compiling MX2 apps and I found out it was Malwarebytes locking some files...

**Comment by TurkeyLurker** [comment]
I am running antimalware, but I have the same setup that I had before when I was able to build MX2 from scratch.  The only thing thats changed was the new code from the current build.

**Comment by TurkeyLurker** [comment]
Update:  I was able to get the modules to build when I disabled my antimalware, but now ted2go will not build because of a duplicate identifier with a button.  I will redownload the source files later and just assume that the develop branch is WIP.  Thanks therevills

**Comment by blitz-research** [comment]
Should be fixed now, try again please.

**Comment by TurkeyLurker** [comment]
Ok, tried again.  Now I'm back to the original error message when building in windows from a fresh download just now:

C:\monkey2-develop\scripts>rebuildmods

C:\monkey2-develop\scripts>echo off

***** Rebuilding modules *****


Mx2cc version 1.1.08

***** Making module 'monkey' *****

Parsing...
Semanting...
Translating...
Compiling...
Build error: System command 'g++ -c -std=c++11 -m32 -D_WIN32_WINNT=0x0603 -O3 -DNDEBUG -I"C:/monkey2-develop/modules/" -I"C:/monkey2-develop/modules/monkey/native" -o "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/build/monkey_0monkey.cpp.o" "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/src/monkey_monkey.cpp"' failed.

g++ -c -std=c++11 -m32 -D_WIN32_WINNT=0x0603 -O3 -DNDEBUG -I"C:/monkey2-develop/modules/" -I"C:/monkey2-develop/modules/monkey/native" -o "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/build/monkey_0monkey.cpp.o" "C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/src/monkey_monkey.cpp"

Assembler messages:
Fatal error: can't create C:/monkey2-develop/modules/monkey/monkey.buildv1.1.08/windows_release/build/monkey_0monkey.cpp.o: Permission denied


***** Fatal mx2cc error *****

Internal mx2cc build error

**Comment by blitz-research** [comment]
Have you disabled the anti-malware again?

I have no idea why you have to do this, but I cannot be expected to 'debug'
some random piece of anti-malware software and it's interaction with mingw.

If turning off the anti-malware software fixes the problem, that's a good
enough solution for me.

Of course, if you can suggest a better solution...?

**Comment by TurkeyLurker** [comment]
Hey Mark.  Yes, the antimalware is gone (uninstalled).  Now the modules will build, but the monkey module still errors out.  When this was happening before, I couldn't build ted2go after building the modules and received a similar error message to the monkey module.  So far, the only thing I seem to be able to build is mx2cc.  mx2cc, modules, and ted2go previously built just fine under the same setup for ages.  But no, the anti-malware is gone.

I appreciate your time and attention to this matter.  This sort of thing happened before, but I was able to wait until another update of the source tree and it just automagically worked.  Now, I can't build monkey.

**Comment by blitz-research** [comment]
> Now the modules will build, but the monkey module still errors out.

So, all modules *except* monkey build?

> So far, the only thing I seem to be able to build is mx2cc.

But how can you build this if you can't build the monkey module? Are you
using an old build of the monkey module?

Have you tried deleting everything monkey2 related and restarting from
scratch? Reboot liberally too.

**Comment by TurkeyLurker** [comment]
I disabled all of my antivirus.  Everything builds just fine, including MX2 projects in Ted2Go.  I reenable my antivirus (antimalware is uninstalled), and when I go to build a project that previously built fine, I begin getting "Internal mx2cc build error".  So MX2 is off the hook, as my antivirus is apparently causing the problem with mx2cc and mingw.

This sucks.  I was hoping it was a fixable problem with the changes you made to fix permissions for android not going through to windows builds, but its all on me I guess.

A word of Note:  My projects all build and run fine with the binary release of Monkey 1.1.07 and my antivirus. I only have issues with the developer branch build. (Just tested).

**Comment by arpie42** [comment]
I've also been hit with the ted2go duplicate button issue so glad to hear that's sorted. I'll try that again this evening.
I built all modules and monkey itself from sources yesterday. I was using version 1.1.06 to build with so had to hack around issues caused by the new ? Operator but once I got 1.1.08 to build the rest was no problem.

As for your issue... have you checked it's not something stupid like you're out of disk space? I'm on Linux and low disk space usually flags up as write permission errors. I don't know on windows though.

**Comment by TurkeyLurker** [comment]
A word of Note to Mark:  My projects all build and run fine with the binary release of Monkey 1.1.07.  I only have issues with the developer branch build.

**Comment by TurkeyLurker** [comment]
arpie42:  I can build ted2go now just fine if my antivirus is disabled, so hopefully the ted2go will work fine with you.  I checked my disk space, and I have over 700GB free, so I don't think that's an issue.

**Comment by therevills** [comment]
Malwarebytes is pretty big... I'm surprised with the issue, but I just put up with it and disable it when developing MX2 - not a big hassle really.

**Comment by TurkeyLurker** [comment]
I can disable my protection and internet to develop with MX2, but I do *not* like the idea of my computer being vulnerable to fileless scripting attacks while I'm trying to do it.

**Comment by blitz-research** [comment]
One google result for 'malwarebytes locking files':

https://forums.malwarebytes.com/topic/211718-malwarebytes-randomly-locking-files/

Perhaps ask the malwarebytes guys?
