### ISSUE TITLE
'Where' keyword in class declaration doesn't work

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#251]
`Class BehWrapper<T> Where T Extends Behaviour`

Error : Expecting end of line.

**Comment by engor** [comment]
What about case with more than one type?
`Class Test<T,R> Where T ... R ...`
What the syntax here if it works?

**Comment by engor** [comment]
As soon as C++ templates checks at compile time, I can easily work w/o `where`...

**Comment by blitz-research** [comment]
> What about case with more than one type?

Where expressions are effectively boolean expression, eg: '...Where T
Extends Actor And R Extends Whatever'.

> As soon as C++ templates checks at compile time

No idea what this means sorry.


On Fri, Nov 3, 2017 at 12:15 AM, Evgeniy Goroshkin <notifications@github.com

**Comment by blitz-research** [comment]
> Error : Expecting end of line.

Can you post a buildable demo? This works here:

```
Class B
End

Class C Extends B
End

Class D
End

Class E<T> Where T Extends B
End

Function Main()
   Local e:=New E<C>
End
```

**Comment by engor** [comment]
> Where expressions are effectively boolean expression, eg: '...Where T
> Extends Actor And R Extends Whatever'.

I have this code:
`Class DraggableViewListener<TItem,THolder> Where TItem Implements IContainer And THolder Implements IDraggableHolder`
and got error
`Error : Types can only be compared for equality`

**Comment by engor** [comment]
>>  As soon as C++ templates checks at compile time

> No idea what this means sorry.

In c++ and monkey2 templates "accepted" at compile time - and we can set any template types which have all members used by this template instance inside of class.

Look at example below, here we can set MyJsonParser as a type of ParseDelegate because it has Parse method with correct signature.
```
Function Test()
	
	Local parser:=New MyJsonParser
	Local delegate:=New ParseDelegate<MyJsonParser>( parser )
	Local result:JsonObject=delegate.Parse( "{~qnumber~q:777}")
	Print "result: "+result.ToJson()
End

Class MyJsonParser
	
	Method Parse:JsonObject( s:String )
	
		Return JsonObject.Parse( s )
	End
	
End

Class ParseDelegate<T>
	
	Method New( parser:T )
		
		_parser=parser
	End
	
	Method Parse<R>:R( s:String )
		
		Return Cast<R>( _parser.Parse( s ) )
	End
	
	Private
	
	Field _parser:T
End
```
In c++ (or just in monkey2?) we can call any methods of **T** (w/o parse errors etc) until we try to create concrete instance.

In Java and C# we can't do that - we must specify "what is T" before call it members.
Like this:
```
interface IParser{
    object Parse( string s );
}
class MyJsonParser : IParser { ... }
class ParseDelegate<T> where T : class, IParser { ... }
```
We need to use interface here, to let compiler to know "from where type T can get its Parse method".

**Comment by blitz-research** [comment]
Ok, can reproduce and will look into it.

In future, could you please post 'runnable' examples of problems, including
a Main(). This saves me time and greatly increases the chances of begin to
actually reproduce the bug.

**Comment by engor** [comment]
> In future, could you please post 'runnable' examples of problems, including
> a Main(). This saves me time and greatly increases the chances of begin to
> actually reproduce the bug.
> 

Of course, sorry.

**Comment by blitz-research** [comment]
> In c++ and monkey2 templates "accepted" at compile time

This will not be changing anytime soon, if ever.

**Comment by engor** [comment]
> This will not be changing anytime soon, if ever.

I said about that as a feature not a bug. :)
It allow me to "hack" generic types the way I can't do in java or c#.
It's a cool language feature! 
I have pretty big java/c# background and it looked strange for me for a first time.
But now I did understand its power! :)

**Comment by blitz-research** [comment]
> It's a cool language feature!

I think so. There are many 'code constraints' you can't express with just
'implements' style expressions so it's nice to just allow user to write
anything they want and let it fall over at compile time instead. C# adds a
bunch of special terminology for things like 'has default ctor' (or you
can't use new T() with it) but even then you can't capture *every* possible
constraint. Is this possible? Don't know and don't plan to find out...

Being from c++ I'm OK with monkey2's more relaxed approach, but I know many
others aren't and I had indeed assumed, wrongly, that you wouldn't be
either. Apologies!

Also note we can 'add' stuff to Where syntax over time, eg: things like
'has default ctor' etc, allowing generic instantiation to fail sooner, but
without limiting generics at all.

ps: looks like c++'s latest atttempt to add something like 'where' ends up
adding a whole new 'meta language':
http://en.cppreference.com/w/cpp/language/constraints although I guess
'where' expressions are sort of
a different language in a way too...comparing types etc.

**Comment by blitz-research** [comment]
Ok, turns out "and' and "or" weren't even in there - have added them now
and pushed to develop.

Did you find the original problem? There was no 'and' or 'or' in the
original bug report...

Here's the test code I've been using:

```
Interface I
End

Interface J
End

Class A
End

Class B
End

Class C Implements I
End

Class D Implements J
End

Class E<X,Y> Where X Implements I Or Y Implements J
End

Function Main()
Local test:=New E<A,D>
End
```

**Comment by engor** [comment]
Nice! But I think 'Or' is incorrect here. I've never see it for class conditions..
I would preffer comma-separated variant:
```
Class E<X,Y> Where X Implements I, Y Implements J
End
```
And / Or looks good inside one-type-declaration:
```
Class E<X,Y> Where X Implements (I Or J), Y Implements (J And X)
End
```
Or maybe split by comma types-for-each-template's types and use *only* AND keyword to combine conditions:
```
Class E<X,Y> Where X Extends BaseX Implements I, J And Y Implements J
End
```

**Comment by engor** [comment]
c# uses line breaks to do multi-conditions. I'm not sure is it good for monkey2.
```
class MyClass<T, U>
    where T : class
    where U : struct
{ }
```

**Comment by engor** [comment]
Or maybe simicolon for splitting conditions
```
Class E<X,Y> Where X Implements I,J ; Y Implements J,X
End
```
_Keyword Or seems to be incorrect at all._

**Comment by blitz-research** [comment]
But what does semicolon (or comma) mean? If it means 'And' why not just use
'And'? Why create new syntax for what is effectively just a boolean
expression?

I guess I just find 'Where X Extends C And Y Extends D' clearer and more
familiar than something with commas or semicolons or other 'new syntax' in
it (which starts looking a bit too c# to me), maybe because I'm not very
familiar with any of this in the first place, and in my mind where
expressions are really just a kind of boolean expression - which they are.

I haven't really though what 'Or' could be used for. Perhaps you have 2
classes both with an Update method (but that don't 'Implement' IUpdateable
etc) so your generic code can work with either. Dunno, but "or" was easy to
add once "and" was in there so why not? Another example: 'Where T=String Or
T Implements INumeric' is possibly a bit more useful. "Not" could be added too -
or of course you could change X Extends Y into Y Extends X but perhaps Not
would be clearer, eg: "Where Not (X Extends Y)"? Or maybe not...but again, would it hurt to add it?

Furthermore, it'd be nice to eventually see a 'StaticIf' that can conditionally compile code, eg:

StaticIf T Implements INumeric
    Print "T is numeric type!"  'never even compiled if Not T Implements INumeric!
Endif

I was thinking the same 'syntax' for where expressions could be used here, and we probably DO want "and" and "or" and "not" etc in StaticIf.

All in all, I think "and" is cool! It means Where expressions can potentially be as complex as 'real' bool expressions, and I think it'll make sense to newbies like me.

**Comment by blitz-research** [comment]
...another thing to note is you can already split Wheres over multiple lines, just end each line with an 'And' and it'll get split like a normal expression.

**Comment by engor** [comment]
Nice explanation for And/Or/Not! Looks even more powerful than in c#. :)
I understand use-cases now. Go to try it out!..
