### ISSUE TITLE
Can't use Monkey2 with external "projects"

### ISSUE THREAD

**Issue by XANOZOID** [blitz-research/monkey2#255]
I have attempted to run some Monkey2 examples outside of the directory, or subdirectories, monkey2 is located in. I downloaded an examples repository from [here](https://github.com/Pakz001/Monkey2examples) and unfortunately trying to run it from my github folder it  ran into some issues. Long story short, it seems I have run into the exact same issue posted on the forums [here](http://monkeycoder.co.nz/forums/topic/bug-compiling-from-some-folders/). I don't believe I found any ticket opened so I decided to make one!

Essentially, running monkey2 projects inside the bananas folder works. Doing it in an external location causes problems. 

Extra info:
- Admin rights does not fix it
- Running windows 10
- Lastest Monkey2 windows itch.io version 
- On a laptop
- Toyed around with write access

**Comment by blitz-research** [comment]
No idea what's happening herre sorry - I get reoprts of issues like this once  a year or so and have done for the last decade-ish!

I *assume* it's a permissions/admin/user thing, but without being able to play around a bit on your actual machine I'm stuck unless anyone else can help out - anyone?

Have you tried 'run as admin'? Installing to different dir? etc etc...

**Comment by abakobo** [comment]
if you have the same error than on the forum post. i.e. `fatal error: ../../../../../../../../../../../../Jungle Ide Framework/Monkey2/modules/mojo/mojo.buildv010/desktop_debug_windows/mojo_app_2window.h: No such file or directory`
It's probably that your path is too long. Try to put your folder nearer from root dir. Such "no such file or directory" has always been resolved by having a shorter path AFAIK.

**Comment by blitz-research** [comment]
Ugh, it shouldn't be doing that - it should defnitely be using absolute
paths in this case - will take a look.

**Comment by abakobo** [comment]
It could also be spaces in the file path? Depending on the platform I think spaces in filepathes can create problems too.
For the long file path names there is an issue on the repo: https://github.com/blitz-research/monkey2/issues/102
But I've never tried to "crash" the build with very long path since I know I should avoid them (and spaces in directory/files names)
