### ISSUE TITLE
JoystickDevice.GetAxis() documentation wrong?

### ISSUE THREAD

**Issue by Difference** [blitz-research/monkey2#256]
mojo/input/joystick.monkey2 says:

#rem monkeydoc Gets joystick axis value in the range -1 to 1.
	#end	
	Method GetAxis:Float( axis:Int )

but the https://github.com/blitz-research/monkey2/blob/master/bananas/joystick/joystick.monkey2 uses For Local axis:=0 Until 6

"..two men saying they're Jesus, one of them must be wrong..." :-)

**Comment by blitz-research** [comment]
Think it's right - the returned value is in the range -1 to +1, but the
'axis' param is one of 6 possible axes number 0 to 5, eg: 0 for left
joystick, 1 for right joystick etc. Maybe param should be renamed axisid?

**Comment by Difference** [comment]
I'd get it if it said something like:
Returns a value in the range -1 to 1, where axis is one of 6 possible axis in the range 0 to 5.

**Comment by blitz-research** [comment]
I thought'd be nice for people to be able to see the possible returned range of values in 'quick help'
without having to open entire docs page.

Would still like to do this - please provide you preferred one-line docs. Note that axis is in the range [0,NumAxes).
