### ISSUE TITLE
Should operator `To` works for func parameters?

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#257]
_I don't know is it correct, but seems to should work._

I want to simplify using functions which work with Transform and GameObject - to pass transform like gameObject and gameObject like transform.
* Transform always have gameObject reference.
* GameObject always have transform reference.

Example code.
```
Class Transform
	Field pos:Vec2f
	Field scale:Vec2f
	Field rot:Float
	Field gameObject:GameObject
	
	Operator To:GameObject( t:Transform )
		Return t?.gameObject
	End
End

Class GameObject
	Field transform:Transform
	
	Operator To:Transform( go:GameObject )
		Return go?.transform
	End
End

Function ProcessTransform( t:Transform )
	t.pos=t.pos*1.75
End
```
and my expected usage of operator To() :
```
Local go:=New GameObject
ProcessTransform( go )
```
but...
`Error : Can't find overload for 'ProcessTransform:Void(myapp.Transform)' with argument types (myapp.GameObject)`

**Comment by blitz-research** [comment]
Try:

```
Operator To:Transform()
Return Self.transform
End

```

Conversion operators must be invokable with no parameters.

**Comment by blitz-research** [comment]
...ditto you'll have to tweak the other conversion:

```
Operator To:GameObject()
Return Self.gameObject
End
```

**Comment by engor** [comment]
Oh! Really. Thanks!
