### ISSUE TITLE
'Model.Load', and related functions do not allow you to specify a parent entity.

### ISSUE THREAD

**Issue by ImmutableOctet** [blitz-research/monkey2#268]
The 'Model.Load' and 'Model.LoadBoned' methods, as well as the 'Mojo3dLoader' class's methods do not allow you to specify an optional parent entity for the loaded model.

For reference, the ['Mojo3dLoader' class](https://github.com/blitz-research/monkey2/blob/3392e1a141f5024058dcc21aeb90894116ea97d8/modules/mojo3d/geometry/loader.monkey2#L6) would look something like this:

```
Class Mojo3dLoader

	Const Instances:=New Stack<Mojo3dLoader>
	
	Method New()
		
		Instances.Push( Self )
	End
	
	Method LoadMesh:Mesh( path:String ) Virtual
		
		Return Null
	End
	
	Method LoadModel:Model( path:String, parent:Entity=Null ) Virtual
		
		Return Null
	End
	
	Method LoadBonedModel:Model( path:String, parent:Entity=Null ) Virtual
		
		Return Null
	End

End
```

To be honest, I couldn't find a way to assign a parent after loading, so that's why I think this may be required. If there's another way to assign a child/parent relationship after construction, then please let me know.

**Comment by blitz-research** [comment]
entity.Parent=parent

**Comment by ImmutableOctet** [comment]
I didn't realize that was assignable. Thanks, Mark.
