### ISSUE TITLE
sdl2 mixer decl 

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#27]
In SDL2.monkey2 the following  corrects last two arguments to be unsigned.

Function SDL_LoadWAV_RW:SDL_AudioSpec Ptr(src_:SDL_RWops Ptr,freesrc_:Int,spec_:SDL_AudioSpec Ptr,audio_buf_:UByte Ptr Ptr,audio_len_:UInt Ptr)

**Comment by blitz-research** [comment]
Fixed.
