### ISSUE TITLE
Test "morpher.monkey2" not rendering

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#279]
I get an empty screen with that example.

Adding a sphere at (0,0,0) renders correctly, so there seems to be something wrong with the Morpher object itself, but having never dealt with the Renderable class directly before I can't figure it out.

On MacOS High Sierra, V1.1.08 latest dev branch.
Thanks!

**Comment by blitz-research** [comment]
Oops, been playing around with Visible stuff - it just needs a
'Visible=True' added to end of Morpher ctor, or you can add
_morpher.Visible=True at end of Window ctor.

**Comment by DoctorWhoof** [comment]
Thanks!
