### ISSUE TITLE
Android Back Button

### ISSUE THREAD

**Issue by therevills** [blitz-research/monkey2#293]
SDL2 supports the Android Back Button via the SDLK_AC_BACK code. I've been trying to get it to work in Monkey2 but cant seem to get it on my own.

Could you please add support to MX2 to support the back button :)

Please see this thread:
http://monkeycoder.co.nz/forums/topic/diddy2-android-back-button/

**Comment by blitz-research** [comment]
Just pushed some fixes for this to develop - see thread above for more info.

**Comment by therevills** [comment]
Thanks Mark! :+1:
