### ISSUE TITLE
Emscripten debug fails with new timer

### ISSUE THREAD

**Issue by seankarol** [blitz-research/monkey2#297]
I'm using 1.1.08 from itch.io, compiling to Emscripten asmjs debug. I received this error:
`BBGC_VALIDATE failed: 0x65d84c t_std_timer_Timer 17`

It seems to fail at this line from what I can gather:
https://github.com/blitz-research/monkey2/blob/74168c5ee3ec018043b74fd87066147ded59ce4c/modules/std/time/timer_emscripten.monkey2#L29

Example:
```
#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

Class MyWindow Extends Window
	
	Method New()
		New Timer(30, Lambda()
			Print "YES" +Millisecs()
		End)	
	End

	Method OnRender( canvas:Canvas ) Override
	
		canvas.DrawText( "Hello World",Width/2,Height/2,.5,.5 )
		
	End

End

Function Main()

	New AppInstance
	
	New MyWindow
	
	App.Run()
End
```

**Comment by blitz-research** [comment]
This is, I believe, an emscripten bug to do with doubles. Here's another
report of what I think is the same issue from ages ago:

https://github.com/blitz-research/monkey2/issues/128

I've been unable to isolate the problem to date - as soon as I try and
produce sample c++ code for emscripten guys to look at it disappears! - but
this will hopefully help. In the meantime, I can fix this by using floats
instead of doubles in the emscripten Timer class which should be good
enough for now...

Note that wasm is really the recommended emscripten output format going
forward, so I suggest you use that if possible. Wasm does not seem to have
these problems and works pretty much everywhere now except for 'Edge'. And
it looks like that's changing too:
https://visualstudiomagazine.com/articles/2017/11/06/edge-webassembly.aspx

**Comment by seankarol** [comment]
Okay, thanks Mark.

I've tried compiling to wasm instead but I run into a host of other errors when compiling the same code above:

```
Traceback (most recent call last):
  File "/Users/sean/emsdk/emscripten/1.37.22/em++", line 16, in <module>
    emcc.run()
  File "/Users/sean/emsdk/emscripten/1.37.22/emcc.py", line 882, in run
    exec 'shared.Settings.' + key + ' = ' + value in globals(), locals()
  File "<string>", line 1, in <module>
NameError: name 'allow' is not defined
```

Any clue what this is about? I couldn't dig much up else where =/

**Comment by blitz-research** [comment]
You made need a more recent emscripten - I am running 1.37.9 here.
Unfortunately, emscripten can be tricky to install/update...might have
another shot at a 'standalone' installer.

But I may have found the problem with asm.js too - stay tuned.

**Comment by blitz-research** [comment]
Ok, fixes pushed to develop branch.

Note: you'll have to rebuildall2go with this version as there are some VERY
low level gc changes.

**Comment by seankarol** [comment]
Awesome, thanks!

I'm using emscripten 1.37.22. It appears the OpenGL module is breaking in the develop branch for emscripten?

```
***** Making module 'opengl' (emscripten release llvm gcc) *****

Parsing...
Semanting...
Translating...
Compiling...
Build error: System command failed:

emcc -c -std=gnu99 -s USE_SDL=2 -s TOTAL_MEMORY=268435456 -s DISABLE_EXCEPTION_CATCHING=1 -O3 -DNDEBUG -I"/Applications/monkey2/modules/" -I"/Applications/monkey2/modules/monkey/native" -o "/Applications/monkey2/modules/opengl/opengl.buildv1.1.09/emscripten_release/build/_1_1_1native_2bbopengl.c.o" "/Applications/monkey2/modules/opengl/native/bbopengl.c"

/Applications/monkey2/modules/opengl/native/bbopengl.c:41:20: error: implicit declaration of function 'SDL_GL_ExtensionSupported' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        BBGL_draw_buffers=SDL_GL_ExtensionSupported( "GL_WEBGL_draw_buffers" );
                          ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

and then if I skip the OpenGL Module and try to keep building the rest ...

```
***** Making module 'std' (emscripten release llvm gcc) *****

Parsing...
Semanting...
Translating...
Compiling...
Build error: System command failed:

em++ -c -std=c++14 -s USE_SDL=2 -s TOTAL_MEMORY=268435456 -s DISABLE_EXCEPTION_CATCHING=1 -O3 -DNDEBUG -I"/Applications/monkey2/modules/" -I"/Applications/monkey2/modules/monkey/native" -o "/Applications/monkey2/modules/std/std.buildv1.1.09/emscripten_release/build/std_0audio_02load_00vorbis.cpp.o" "/Applications/monkey2/modules/std/std.buildv1.1.09/emscripten_release/src/std_audio_2load_0vorbis.cpp"

/Applications/monkey2/modules/std/std.buildv1.1.09/emscripten_release/src/std_audio_2load_0vorbis.cpp:5:10: fatal error: 'stb-vorbis/stb-vorbis.buildv1.1.09/emscripten_release/include/stb_5vorbis_stb_5vorbis.h' file not found
#include "stb-vorbis/stb-vorbis.buildv1.1.09/emscripten_release/include/stb_5vorbis_stb_5vorbis.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

For the record it looks like the same problems are happening on emscripten 1.37.9: http://monkeycoder.co.nz/forums/topic/emscripten-em-is-not-recognized/page/3/#post-12338


I noticed the _pad:int temporary fix you had there and that seems to be working good on my itch version :)
