### ISSUE TITLE
GLTF materials not importing properly

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#299]
I don't know how far along is the material importing on GLTF files, but I'm not seeing accurate results right now.

This is how it looks in Qtek model viewer:
<img width="655" alt="screen shot 2017-12-27 at 11 00 46 pm" src="https://user-images.githubusercontent.com/6250116/34403321-72687222-eb5c-11e7-8d52-3589282ee457.png">

And this is what I'm getting in Mojo3D:
<img width="752" alt="screen shot 2017-12-27 at 11 05 30 pm" src="https://user-images.githubusercontent.com/6250116/34403337-7ee70752-eb5c-11e7-98af-caaecb42bb22.png">
Notice how there's no reflection on any of the airplane's materials, which seems to indicate high roughness? Also, no transparency.

If you want to play with the files, including the Monkey code, I've dropped them in a repository here:
https://github.com/DoctorWhoof/Plane-Demo

Eventually this will be a Mojo3D demo where you'll fly the airplane around a tiny island, so yes, you can use the models if you want! (the plane is not finished yet, though)

Cheers.

**Comment by DoctorWhoof** [comment]
Manually setting all materials to roughness = 0 kinda works ( "kinda" because the materials are supposed to have different values), so the file import is definitely ignoring the original values.

Maybe the default value for roughness is being used instead of the one from the file?

<img width="407" alt="screen shot 2017-12-27 at 11 38 07 pm" src="https://user-images.githubusercontent.com/6250116/34403814-642554ca-eb5f-11e7-88c9-a341b6a7a53d.png">

**Comment by blitz-research** [comment]
Looking good! Hope mojo3d is working OK for you - I accidentally pushed
some stuff that wasn't really well tested...mostly physics sutff though,
everything else should be OK-ish...collisions on the way!

I will have a look at the model. I should be able to get it looking much
better, although I did notice QTEK store a lot of stuff in a custom chunk
in the file. Still, even if I rip this chunk out so it's a 'pute' gltf
file, the QTEK viewer still produces very similar results.

If you want to try this yourself, just remove the "extras" object at the
end of the .gltf file, then drag/drop the folder into the viewer. Looks a
little different here, but much closer to the top image than current mojo3d
results so something's up.

**Comment by blitz-research** [comment]
'pute'='pure'!

**Comment by blitz-research** [comment]
Wow, just ran the demo, simple but looks very cool!

Did find one thing - roughnessFactor was being effectively ignored. Fixed
now and it looks much shinier. I think the QTEK env map gives the model a
bit of extra 'yellow' or something but they look pretty similar now IMO.

The other issue is our old friend linear colors. I hadn't thought about it
but gltf2 probably assumes Iinear material colors (whether gltf exporters
do is another story!) but PbrMaterial defaults to sRGB colors now. So I've
changed the gltf material loader to compensate for this so it treats gltf
(only) material 'factors' as being linear instead of sRGB.

This doesn't result in a lot of difference as the colors are very primary
anyway, but I *think* it looks more correct, the colors are just a little
bit warmer or something..

**Comment by blitz-research** [comment]
Infinite water (just before _scene.Render):

_water.Position=New Vec3f( Round(_camera.Position.x/2000)
*2000,0,Round(_camera.Position.z/2000)*2000 )

**Comment by DoctorWhoof** [comment]
Yes, latest updates are working fine, thanks! Material looks good now.

Thanks for the infinite water tip! Once I have the island I'll make it "loop" - if you fly far enough, the island shows up again, as if you're in a tiny, self contained universe! :-)

I want to create a "Material Editor" at some point. Even Unity and Unreal rely on some sort of material editor in engine to ensure things look like what you want.

My plan is a MojoX tool that saves a material library as a json file. Textures will need to be referred to by name, which I have as a Texture extension (extensions are cool!). Once a material library is loaded, all materials in it are created and can be retrieved by their names (once again using an extension). This of course requires people who want to use the material editor to import those extensions, I wonder if there's a simpler way.

Cheers!
Thanks!
