### ISSUE TITLE
Can't run any fresh code from latest dev

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#301]
Hi,

Whenever I build a "fresh" app (no pre-existing build and product folders), I get this error on MacOS High Sierra:

```
Mx2cc version 1.1.09
***** Making app '/Users/leo/GoogleDrive/Code/Monkey2/matlab/editor/editor.monkey2' (macos debug x64 gcc) *****
Parsing...
Semanting...
Translating...
Compiling...
Linking /Users/leo/GoogleDrive/Code/Monkey2/matlab/editor/editor.buildv1.1.09/macos_debug/editor.app/Contents/MacOS/editor...
Running /Users/leo/GoogleDrive/Code/Monkey2/matlab/editor/editor.buildv1.1.09/macos_debug/editor.app/Contents/MacOS/editor
Build error: System command failed:
"/Users/leo/GoogleDrive/Code/Monkey2/matlab/editor/editor.buildv1.1.09/macos_debug/editor.app/Contents/MacOS/editor"
dyld: Library not loaded: @executable_path/libopenal.dylib
  Referenced from: /Users/leo/GoogleDrive/Code/Monkey2/matlab/editor/editor.buildv1.1.09/macos_debug/editor.app/Contents/MacOS/editor
  Reason: image not found
***** Fatal mx2cc error *****
Internal mx2cc build error

Build stopped.
```
Compiling and running pre-existing projects works, but as soon as I clean their build folders they stop working as well.

I tried manually copying "libopenal.dylib" into Contents/MacOS in the app bundle, and it works!

Looks like a comment in M2's code somewhere became part of the file path, and it's creating a folder called "'ie/ dylibs go in app Contents" where it copies the "libopenal.dylib" file.

Thanks!

**Comment by DoctorWhoof** [comment]
Interestingly enough, Ted2Go did not show me the error, it simply silently failed. I got the error by compiling it in Mollusk.

**Comment by blitz-research** [comment]
Fix pushed to develop.

**Comment by DoctorWhoof** [comment]
Thanks!
