### ISSUE TITLE
Some gLTF models do not load

### ISSUE THREAD

**Issue by Hezkore** [blitz-research/monkey2#302]
Here's a simple cylinder made in Blender and exported with the gLTF 2.0 exporter addon that Monkey 2 Mojo3D cannot load: [test.zip](https://github.com/blitz-research/monkey2/files/1592872/test.zip)

The exported file passes validation and renders fine in Babylon and three.js:
![bild](https://user-images.githubusercontent.com/1727541/34433993-5c593a98-ec83-11e7-9601-dfd62b99ccc4.png)

![bild](https://user-images.githubusercontent.com/1727541/34433996-5fa53954-ec83-11e7-8b19-b22be3a6adc2.png)

It also works in this online gLTF viewer: https://gltf-viewer.donmccurdy.com/
(drag both gltf and bin file into the view at the same time)

**Comment by DoctorWhoof** [comment]
Model also fails in Qtek viewer. I wonder if there's something not 100% standard about it.

**Comment by blitz-research** [comment]
Fix pushed to develop - had to add support for ubyte indices.
