### ISSUE TITLE
Fog should have option to not affect SkyTexture

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#304]
Hi,

It would be great to have a switch to prevent the fog color from mixing with the sky texture.
![fogrequest](https://user-images.githubusercontent.com/6250116/34457239-9b970514-ed5f-11e7-9aa3-938e9f2afcf9.gif)
Thanks!

**Comment by blitz-research** [comment]
I've changed this so fog never affects skybox. If you want fog to be applyig to back ground too, just set ClearColor to same as FogColor.
