### ISSUE TITLE
[Suggestion] Model.CreateBox specify faces

### ISSUE THREAD

**Issue by Hezkore** [blitz-research/monkey2#306]
I'd really like it if we were able to specify which faces were created with Model.CreateBox.
Something like CreateBox( box:Boxf, faces:Axis, material:Material, parent:Entity=Null )
Where we could specify Axis.X|Axis.Y and skip out on Axis.Z for example.

I'd make it myself but as someone who's quite inept when it comes to numbers in general, and also 3D, it's proven to be quite hard and confusing.
I think the Axis enumerator would have to be updated as well.

But it's something I really think should be part of Mojo3D from the start.

**Comment by blitz-research** [comment]
This is a highly specialize request - I can't even think would you'd use it for - that I think would be better suited to an 'extension' or utility style module. Post a request on the forums and someone should be able to help out.
