### ISSUE TITLE
[Suggestion] Scale materials

### ISSUE THREAD

**Issue by Hezkore** [blitz-research/monkey2#309]
There doesn't seem to be an easy way to set the exact scale of materials.
You can use _Material.ScaleTextureMatrix_ but that multiplies the texture coords, it doesn't set them directly.

I suggest something like _Material.SetTextureMatrix_ where we can set it directly.
Same for _Mesh.ScaleTexCoords_ I think _Mesh.SetTexCoords_ would be good.

So _SetTextureMatrix( New Vec2f( 1, 1 ) )_ would be its default size, while _SetTextureMatrix( New Vec2f( 2, 2 ) )_ would be twice as big, even if we call the function twice.

**Comment by blitz-research** [comment]
Material.TextureMatrix is a r/w  property so you can go:

material.TextureMatrix=new Vec2f( 1 )
