### ISSUE TITLE
MSVC mojo apps failing -- SDL_CreateWindow

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#329]
Checking out latest develop branch and rebuilding modules with MSVC, all goes fine.

Applications build no problem, and copy correct DLLs, but on running in Debug or Release, they give:

`FATAL ERROR: SDL_CreateWindow failed`

Tried both 32- and 64-bit builds.

Basic `Print "Hello"` works fine.

Oddly, Release builds say:

```
FATAL ERROR: SDL_CreateWindow failed
{{!DEBUG!}}
```

(Adding the DEBUG! thing.)

**Comment by blitz-research** [comment]
ALL msvc apps fail? Anyone else? MSVC is fine here.

**Comment by DruggedBunny** [comment]
Yeah, it builds fine, but nothing graphical runs. I'll try a reboot!

**Comment by blitz-research** [comment]
Just did a clean clone/rebuildall2go and all appears to work fine. Have
tried mojo3d bouncyboxes and room tests and promptinvasion banana.

Note: I changed env_windows.txt to msvc=1, arch=x64 immediately after clone
before rebuilding anything.

**Comment by DruggedBunny** [comment]
I'll try that, still failing here after a reboot.

Take it you no longer need to build in MinGW first then?

Are you able to upload a built example so I can run here?

Will go checkout and try change to MSVC before building...

**Comment by DruggedBunny** [comment]
Nope, same result here -- clone, change to MSVC/x64, rebuildall2go and it fails -- yet previous version works fine in MSVC!

If you can upload a built example, I'll see what happens with that...

**Comment by DruggedBunny** [comment]
Slight debug progress...

It happens in app.monkey2, under __DESKTOP_TARGET__ and I've modified it to print the SDL error:

```
		'create dummy window/context
		Local _sdlWindow:=SDL_CreateWindow( "<dummy>",0,0,0,0,SDL_WINDOW_HIDDEN|SDL_WINDOW_OPENGL )
		
		Print "SDL_GetError="+String.FromCString( SDL_GetError() )

		Assert( _sdlWindow,"FATAL ERROR: SDL_CreateWindow failed" )

```

This says...

```
SDL_GetError=Failed loading OPENGL32.DLL: The specified module could not be found.

FATAL ERROR: SDL_CreateWindow failed
{{!DEBUG!}}

```
I've looked for references to SDL_CreateWindow in *.monkey files, and compared directly -- they appear not to have changed, at least in their local contexts (can't tell if anything wider has).

I guess somehow opengl32 isn't being brought in for my MSVC builds -- switching to MinGW is fine still, so it's being picked up there...

Some sort of Angle weirdness, or DLLs incompatible between the compilers?

This is the contents of plane.products\Windows after an MSVC build:

```
26/01/2018  15:25    <DIR>          assets
26/01/2018  13:31         3,466,856 d3dcompiler_47.dll
26/01/2018  13:31           294,912 libEGL.dll
26/01/2018  13:31         3,031,552 libGLESv2.dll
26/01/2018  13:31           666,112 OpenAL32.dll
26/01/2018  15:25         3,061,760 Plane.exe
```
Exactly the same, other than Plane.exe, after a MinGW build:

```
26/01/2018  15:29    <DIR>          assets
26/01/2018  13:31         3,466,856 d3dcompiler_47.dll
26/01/2018  13:31           294,912 libEGL.dll
26/01/2018  13:31         3,031,552 libGLESv2.dll
26/01/2018  13:31           666,112 OpenAL32.dll
26/01/2018  15:29         8,099,328 Plane.exe

```

**Comment by DruggedBunny** [comment]
(BTW toy_plane looks fantastic now.)

**Comment by blitz-research** [comment]
I have no idea what's up - opengl32.dll is 'built in' to the OS so it's
kind of like receiving "can't open user32.dll", ie: it should never happen.

Some things to try investigating:

Did you recently upgrade graphics driver? Did you accidentally install 32
bit driver? What grahics driver version are you running? I recently updated
to 390.65 without any problems.

Does it only happen with 64 bit builds? How about with USE_MSVC=1,
ARCH=x86? Is it OK with mingw?

Does it happen with v1.1.09? v1.1.08 etc?






Is it

**Comment by DruggedBunny** [comment]
Treat this one as closed. I decided to try reinstalling MSVC, and it mentioned something about a Win10SDK error in the shitty, buggy "beautiful design" setup program. Reinstalling this and then installing latest 'develop' seems to have sorted it.

Why Win10SDK would have broken itself (yet still worked for older mx2 versions), I've no idea.
