### ISSUE TITLE
json save in ted2 needs correcting

### ISSUE THREAD

**Issue by StrangeIsMyName** [blitz-research/monkey2#33]
the son save saves as one long line of text, thus breaking the reason to use son - ease of reading

here is a very dirty replacement that adds tabs and new lines:

`		local k:Int
		local out:string = ""
		local str:string = ""
		local chr:string
		local tab:string = ""
		local length:int
		for k = 0 to obj.ToJson().Length
      chr = obj.ToJson().Mid(k,1)
      select chr
        case "{", "["
          str = str + chr
          out = out + str + "~n"
          tab = tab + "  "
          str = tab
        case "}", "]"
          out = out + str + "~n"
          length = tab.Length
          tab = tab.Left( length - 2 )
          str = tab + chr
        case ","
          str = str + chr
          out = out + str + "~n"
          str = tab
        default
          str = str + chr
      end
    next
    out = out + str + "~n"
    
		SaveString( out,"bin/ted2.state.json" )
`

**Comment by blitz-research** [comment]
Fixed - JsonValue.ToJson now pretty prints.
