### ISSUE TITLE
error using Stack.Add with struct containing Image

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#330]
this very strange error has not been consitent in it's compilation behaviour, ~~and I abandonned the stack to an array to stop getting the error.~~ EDIT: I changed from struct to Class and the problem is gone

It happens when calling stack.Add() where stack is a collection of structs containing an Image as field. But the error doesn't always show. As the code could run sometimes!
Maybe we are not supposed to set Resource as struct field?

Sorry not to try to make a small example, could try later.
You can reproduce this way though
modify https://github.com/abakobo/Box2D/blob/mx2/mx2_box2d/b2dJsonBodyImage.monkey2#L126
     (line 126 change Class to Struct)
run the tank example here https://github.com/abakobo/Box2D/tree/mx2/bananas/04-mojo_b2json_b2manager(images_and_names)

here's the cpp error I had (mingw)

			C:/Users/user/Desktop/Box2Dgit/bananas/04-mojo_b2json_b2manager(images_and_names)/e5-tankjointcontrol.buildv1.1.09/windows_debug/include/e5_5tankjointcontrol__1_1mx2_0box2d_2b2dJsonBodyImage.h:100:8:   required from here
			
			C:/Users/user/Desktop/monkey2/modules/monkey/native/bbobject.h:103:18: error: cannot dynamic_cast '((bbGCVar<t_mojo_graphics_Image>*)this)->bbGCVar<t_mojo_graphics_Image>::_ptr' (of type 'struct t_mojo_graphics_Image*') to type 'struct bbGCNode*' (source is a pointer to incomplete type)
			
			   bbGC::enqueue( dynamic_cast<bbGCNode*>( _ptr ) );

**Comment by blitz-research** [comment]
> Sorry not to try to make a small example, could try later.

If I can't reproduce it, I can't fix it.

**Comment by abakobo** [comment]
Sorry! I made an edit to the first post but you were too fast!
I'll try to make a smaller example when I'll have been sleeping a bit. I suppose the full code is not convenient for error seeking..

**Comment by abakobo** [comment]
I could not track it down to a simpler example.... (making a stack of struct called through map and other tryouts but without success)
You can download a more or less cleaned project here: http://turdus.be/monkey2docs/somebug.zip
There is a .txt included in the zip with the code line number to change in order to get it compiling fine. Sorry I can't spend more time on this.
This is probably heavy and ugly code too look thru. However, it is showing the problem.

**Comment by abakobo** [comment]
This has been fixed! (with Feb 19, 2018  commits I think)
