### ISSUE TITLE
Images using TextureFlags.None forces images to be drawn in integers positions not floats.

### ISSUE THREAD

**Issue by RichardBetson** [blitz-research/monkey2#336]
Hi,
I have noticed that images that are loaded with LoadBump() or Load() using TextureFlags.None will appear to draw these images in integer positions. Passing a Null parameter for TextureFlags in LoadBump() and Load() will also cause the same effect. Bump-maped images using TextureFlags.FilterMipmap also appear to be oddly stepping in position as well, as if one texture is out of position in relation to the other textures used by lighting.

I have included a modified version of the simplelight demo to illustrate the issue. It offsets the position of the floor images by .05 (x axis) each frame. Visually you should see the images being drawn in integer positions, which they are not supposed to do. 

```
Namespace myapp

#Import "<std>"
#Import "<mojo>"
#Import "<mojo3d>"

#Import "Slate Tiles II_D.png"
#Import "Slate Tiles II_N.png"
#Import "Slate Tiles II_S.png"
#Import "cone_orange.png"
#Import "Monkey2-logo-48.png"

Using std..
Using mojo..
Using mojo3d..

Class MyWindow Extends Window

	Field _floor:Image
	
	Field _light:Image
	
	Field _logo:Image
	
	Field offset_x:Float
	
	Method New()
		Super.New( "Test Window",640,480,WindowFlags.Resizable )
	
		ClearColor=Color.Black
	
		_floor=Image.LoadBump( "asset::Slate Tiles II_D.png","asset::Slate Tiles II_N.png","asset::Slate Tiles II_S.png",.75,False,Null,TextureFlags.None)
		
		_floor.Handle=New Vec2f( 0.1,0.1 )
		
		_light=Image.LoadLight( "asset::cone_orange.png" )
		
		_light.Handle=New Vec2f( .5,0 )
		
		_light.Scale=New Vec2f( .5,.5 )
	
		_logo=Image.Load( "asset::Monkey2-logo-48.png" )
		
		_logo.Handle=New Vec2f( .5 )
		
		_logo.ShadowCaster=New ShadowCaster( _logo.Width/2,20 )

	End
	
	Method OnRender( canvas:Canvas ) Override
	
		Global viewRot:=0.0
		
		viewRot+=.001
		
		Local rmouse:=-canvas.Matrix * Mouse.Location
		
		Global lightRot:=0.0
		lightRot+=.02
	
		
		
		canvas.AmbientLight=New Color(.7,.7,.7)
		
		canvas.BeginLighting()
		
		canvas.AddLight( _light,rmouse.X,rmouse.Y,lightRot )
		canvas.AddLight( _light,rmouse.X,rmouse.Y,lightRot+Pi )
		canvas.AddLight( _light,rmouse.X,rmouse.Y,lightRot+Pi/2 )
		canvas.AddLight( _light,rmouse.X,rmouse.Y,lightRot+Pi+Pi/2 )
		
		offset_x+=.05
		
		For Local x:=0 Until Width Step _floor.Width

			For Local y:=0 Until Height Step _floor.Height

				canvas.DrawImage( _floor,Float(x)-offset_x,y )

			Next

		Next
		
		For Local an:=0.0 Until TwoPi Step TwoPi/8.0
		
			canvas.DrawImage( _logo,Width/2+Cos( an ) * Width/4, Height/2 + Sin( an ) * Height/4)
		
		Next
		
		canvas.EndLighting()
		
		canvas.DrawText(Floor( App.FPS+.5 ),10,10)
		canvas.DrawText("Offset_X_Step: "+( offset_x ),10,30)

		App.RequestRender()
	End
	
End

Function Main()

	New AppInstance
	
	New MyWindow
	
	App.Run()
End

```

**Comment by RichardBetson** [comment]
Using any TextureFlag other then Filter or FilterMipmap will cause the issue. I think Filter and FilterMipmap are also effected as well at some level but are slightly masking the issues effect. 

Edit: Maybe it's supposed to step position in integers? I'm getting odd results related to image positioning and looking for the issue. It's seems like images moved smoother and less blurry (Filter) before the change to support wide-screen multiple monitor setups.

**Comment by blitz-research** [comment]
This looks right to me.

When you draw a triangle/quad or whatever, you can only really draw it at
integer coords, there is no such things as 'half' a pixel, it's all just a
bitmap after all and you can't have half a bit!

However, if you enable filtering, you can get the illusion of sub pixel
smoothness as the rasterizer is generating 'in between' colors that fool
your eye into thinking things are smoother than they really are. But even
these in between colors are still being drawn at integer positions, It's
just they are kind of 'fading out' from one pixel position and 'fading
into' another.

I threw this together to allow you to look at the effect in close up too
(space too toggle filtering) and it's actually kinda crude. And yes,
TextureFlags.Mipmap is doing some sort of filtering too, but all this stuff
is really down to how the HW works:

```
Namespace myapp

#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

#Import "Slate Tiles II_D.png"

Class MyWindow Extends Window
Field target:Image
Field tcanvas:Canvas
Field image1:Image
Field image2:Image
Field scroll:Float
Field image:Image

Method New( title:String="Simple mojo
app",width:Int=640,height:Int=480,flags:WindowFlags=Null )

Super.New( title,width,height,flags )
image1=Image.Load( "asset::Slate Tiles II_D.png",Null,TextureFlags.Filter )
image2=Image.Load( "asset::Slate Tiles II_D.png",Null,Null )
image=image1
target=New Image( 64,64,PixelFormat.RGBA8,Null,Null )
tcanvas=New Canvas( target )
End

Method OnRender( canvas:Canvas ) Override
App.RequestRender()
If Keyboard.KeyHit( Key.Space )
If image=image1 image=image2 Else image=image1
Endif
scroll+=.01
If scroll>=16 scroll=0
tcanvas.DrawImage( image,scroll-16,0 )
tcanvas.Flush()
canvas.DrawImage( target,0,0,0,Width/64,Height/64 )
canvas.DrawText( "Hello World!",Width/2,Height/2,.5,.5 )
End
End

Function Main()

New AppInstance
New MyWindow
App.Run()
End
```

**Comment by RichardBetson** [comment]
Right on.. thanks.

Where this all comes from (issue) is I was using a filter textureflag and would get odd results in bump-mapped images with high specular shine. Doing things like moving out of position slightly and rapid on/off of specular shine. I ended up using something like this to convert my Float position to integer.

new_pos_x:Int=Floor(player_pos_x)   

Converting the float to an integer stabilized image positioning.  Perhaps a case of DrawImage() (or abstract of) converting to integers using just Int() or maybe something else. At any rate I think I am on track now and thanks for the example.

Thanks.

**Comment by blitz-research** [comment]
If you can post an example of the exact issue you're experiencing, there
may be something else I can do.

(ps: reproducing via an existing banana is a nice approach!)

**Comment by RichardBetson** [comment]
> If you can post an example of the exact issue you're experiencing, there may be something else I can do.

Will do. I'd say I could do it with a simplelight modification. ;)
