### ISSUE TITLE
void variant can't be checked with =false

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#338]
```
	Local va:Variant
	
	If va=True
		Print "va is true"
	Else
		Print "va is false" 'will print
	End
	
	If Not va=True Then Print "va is false again" 'will print
	
	If va=False Then Print "va is false again and again" 'here it is not printing
```

**Comment by blitz-research** [comment]
Please provide a descripription of the problem - am I meant to guess what
you want me to do here?

An unitialize variant is always false - see language docs.

**Comment by abakobo** [comment]
sorry thought the title was clear enough..

> An unitialize variant is always false - see language docs. 

That's the point, it is not behaving as described in docs. i.e. checking the expression 'voidVariant=False' is NOT returning True AND 'voidVariant=True' is not returning True neither (so it's not behaving like a Bool)! Checking for nonvoid variant with 'nonVoidVariant=True' works though.

The following runnable code is showing the boolean nonsense maybe more clearly.
I get this ouput:
```
v is not void (checking with =False)
v is void (checking with =True)

Finished debugging app.
```

```
Namespace myapp

#Import "<std>"

Using std..

Function Main()

	Local v:Variant
	
	If v=False
		Print "v is void (checking with =False)"
	Else
		Print "v is not void (checking with =False)"
	End
	
	If v=True
		Print "v is not void (checking with =True)"
	Else
		Print "v is void (checking with =True)"
	End
	
End
```

Hope it describes it correctly now..

**Comment by abakobo** [comment]
Just realised that we can print Bools..!
So this very short runnable code is showing the problem (voidVariant=False is not working):
```
Function Main()

	Local v:Variant
	
	Print v=False
	Print v=True
	
End
```
console output:
```
False
False
```

Sorry, it sometimes take me time to get clear. ;)

**Comment by abakobo** [comment]
now working fine.
