### ISSUE TITLE
Interface extends Interface

### ISSUE THREAD

**Issue by Mac767** [blitz-research/monkey2#343]
Hi,

with this sample I got this error:
Value of type 'default.B' has no member named 'FieldOfA'
I think this behavior is not correct.

Sample:
`
Interface A
	Field FieldOfA:Bool
	Method FuncOfA:Void()
End Interface 

Interface B Extends A
	Field FieldOfB:Bool
	Method FuncOfB:Void()
End Interface

Class CA Implements A
	Field FieldOfA:Bool

	Method FuncOfA:Void()
		Print "A"
	End Method 
End Class 

Class CB Extends CA Implements B
	Field FieldOfB:Bool
	
	Method FuncOfB:Void()
		Print "B"
	End Method 
End Class 
	
Function Main()

	Local iB:B = New CB()
	
	iB.FuncOfB()
	iB.FieldOfB = True
	
	' Method of Interface A works
	iB.FuncOfA()
	
	' but Field or Property of Interface A fails:
	' Error : Value of type 'default.B' has no member named 'FieldOfA'
	iB.FieldOfA = True
	
	' Cast to Interface A -> works
	Local iA:A = Cast<A>(iB)
	iA.FieldOfA = True

End Function 
`

**Comment by blitz-research** [comment]
The core problem here is that interfaces cannot have fields, but mx2cc is apparently not picking this up which is eventually leading to other errors.

I have modified mx2cc so the correct error is now generated.
