### ISSUE TITLE
Loading some WAV files causes a hard crash

### ISSUE THREAD

**Issue by Hezkore** [blitz-research/monkey2#344]
Some WAV files makes Monkey2 crash, without any error.

Example: [soundcrash.zip](https://github.com/blitz-research/monkey2/files/1768031/soundcrash.zip)

**Comment by blitz-research** [comment]
Fix pushed to develop.

There was a bug with the handling of odd length sample data.

**Comment by Hezkore** [comment]
Yep, this has been fixed.
