### ISSUE TITLE
PbrMaterial.Load should support JPG files

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#345]
Hi,
I've been baking some 4K Pbr textures and, oh boy, file sizes go up pretty fast.

It would be nice if PbrMaterial.Load allowed us to load jpg files, even though we wouldn't be able to load alpha channels. It probably would dramatically speed up initial asset loading times as well.

Thanks!

**Comment by blitz-research** [comment]
It doesn't?!?

Will fix ASAP!

**Comment by blitz-research** [comment]
Simple fix pushed to develop, but untested.

Can you give it a try and let me know if it works?

**Comment by DoctorWhoof** [comment]
Works, thanks!
:-)
