### ISSUE TITLE
TextView - Invisible chars if font not support them

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#347]
If we use font that not support typed char - we see nothing in textview but chars are here! 
If you typed 10 invisible chars then you need to press arrow left 10 times to be at the beginning of line.

Solution is to render rect meaning 'unknown char'.

How to reproduce:
* Run latest dev version of ted2go
* Choose any of Prime theme 
* Create new document
* Insert russian chars, for example "Привет" (with quotes or not).

Fonts in ted2go:  
v1.10 - "MesloLGSDZ-Bold.ttf,18"
dev - "SourceCodePro-Medium.ttf,19"

**Comment by engor** [comment]
Replacement character:

https://www.fileformat.info/info/unicode/char/fffd/index.htm

**Comment by blitz-research** [comment]
This  appears to be an issue with the SourceCodePro font. According to the truetype tutorial/docs:

https://www.freetype.org/freetype2/docs/tutorial/step1.html

"when a given character code has no glyph image in the face, value 0 is returned. By convention, it always corresponds to a special glyph image called the missing glyph, which is commonly displayed as a box or a space."

So you're meant to use glyph 0 to render 'missing' chars, and in all fonts I've tested so far, this is the common 'empty box' glyph - except for source code pro where it's width is 0 so it's 'nothing'.

The only way I can think of to fix this is to fudge around the 0 width - say, using the width of a space char or something?

Not this has nothing to do with the unicode 'replacement' char - it's a glyph level thing. Indeed, testing indicates char $fffd maps to glyph 0 too, as it should. But glyph 0 is broken in source code pro.

**Comment by blitz-research** [comment]
Grab a better source code pro font from here:

https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it

It has an otf version (prefer otf due to license), includes a hidden glyph AND has russian chars.

My job here is done...
