### ISSUE TITLE
joysticks reporting differently under Windows and Linux

### ISSUE THREAD

**Issue by wiebow** [blitz-research/monkey2#35]
Hello Mark,

Can you look at this issue [https://github.com/mutatedmonkey/game2d/issues/10] and tell me if this is intended behaviour?
If all sticks and pads under Windows are reported as Xinput then I'll start looking at the GUID maybe or some other ways of detecting to which device I need to map.

**Comment by wiebow** [comment]
Apparantly, this is just the way it is. All sticks from different manufacturers report different names, although to me this does not make sense :) Closing this issue.

**Comment by blitz-research** [comment]
SDL actually has a bunch of stuff for dealing with this, including a big
file that maps device GUIDs to buttons etc. Haven't had the time to do
anything with it yet though.

**Comment by wiebow** [comment]
Sounds interesting! For now I've created my own mapping definitions for the 3 joysticks I support.
