### ISSUE TITLE
Entity extensions need a way to access component stack...

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#357]
...or some other solution that would allow implementing custom "OnStuff()" events.

Explanation: What I'm doing is extending the "Behaviour" class with a "GameComponent" class that has all the other OnStuff methods I need.

My first gut instinct was to check for all components in an entity, and if the component extends GameComponent I can call those methods at the appropriate moments. But the components stack is private, and inaccessible from an Entity Extension.

Alternatively, I'm open to other solutions that would give me the same result!
Thanks!

**Comment by blitz-research** [comment]
Hmmm, I thought there was a Components"Component[] property in there but it
looks like I've removed it! Would this be enough?

**Comment by DoctorWhoof** [comment]
Yup, a property returning a component array would be perfect. Thanks!

**Comment by blitz-research** [comment]
Just looking into this - are you using any of the NumComponents methods
currently?

**Comment by blitz-research** [comment]
Entity.Components:Component[] property is back in now, see develop branch.

**Comment by DoctorWhoof** [comment]
Great, thanks!
Not using the NumComponents methods currently.

By the way, in order to avoid casting the components on every frame, I'm caching just the ones I need (the ones that extend the GameComponent class that has all the OnStuff() virtual methods) at the start of the game.

I'm caching those components in a Map<Entity, Stack<GameComponent> > global...
Kinda ugly, but works. Will think of something better later.

Were you thinking of any particular approach for when people want to extend Mojo3D?
Thanks!
