### ISSUE TITLE
"Caught signal:Memory access violation" with new Monkey version

### ISSUE THREAD

**Issue by Mac767** [blitz-research/monkey2#361]
Hi,

I used the Dev branch from (2018-03-29) and try to compile my project.
I tried with MSVC x64 and mingw32/x86.
I got this error:
`....
Semanting C:/dev/svn/monkey2/lahnbyte/framework/ScreenEx.monkey2
Semanting C:/dev/svn/monkey2/lahnbyte/framework/ScreenManagerEx.monkey2
Semanting C:/dev/svn/monkey2/lahnbyte/framework/ImageSoundLib.monkey2
Caught signal:Memory access violation

Building cancelled.`

The same project builds with Monkey version1.1.0.8.

The file "ImageSoundLib.monkey2" is the last file for "Semanting" after this in 1.1.0.8 the "Translating" starts.

Any ideas to track down the reason for this error?

kind regards

**Comment by abakobo** [comment]
it's a mx2cc crash
to find the line generating the crash you'll have to comment out stuff till the crash is gone for example.
If you share the code I can have a look (if it's not too big).
Then you'll have to post an issue with a simple example code generating the crash.

**Comment by Mac767** [comment]
Hi  abakobo,
thanks for your answer.
Unfortunately it is a big project with more than 70 monkey file imports (own code).
I will try to play with it and find the origin of the crash.

May be this info could helpful: It is no mojo 3d code only 2d.

**Comment by blitz-research** [comment]
If you send me the project I will take a look at it.

I wont need the data (hopefully) just the the source files.

**Comment by Mac767** [comment]
Hi Mark,
I sent the whole project via mail (approx. 5MB).

**Comment by blitz-research** [comment]
I haven't received anything as yet...

**Comment by Mac767** [comment]
I sent to your blitzmunter@ mail address.

**Comment by blitz-research** [comment]
Ok, google had stuck the attachmentt in spam due to some authentication
issue?

Anyway, the problem is due to code like this...

[button + 10]

...where button is an enum. You must now convert enums to ints for this to
work, eg:

[Int(button) + 10]

The crashing bug will be fixed for next release.

**Comment by Mac767** [comment]
Thanks for the answer Mark.
At this time its realy hard to find all effected lines of code.

That means in the next release I will get a compiler error with the effected lines?
In this case I will stay at the moment at version 1.1.0.8 and wait for the next release.

**Comment by blitz-research** [comment]
Yeah, sorry about that, but you were never meant to be able to add ints to
enums, it just kinda slipped in there!

I should have a fix for this pushed to the develop branch later today or
tomorrow sometime.

**Comment by Mac767** [comment]
Hi Mark,
I just build the April release.
Now I got a compile error for the effect lines of code ('Error : Types must be numeric'), so I can fix the code.

Thanks
