### ISSUE TITLE
Documentation for Entity class does not contain rotation properties or methods.

### ISSUE THREAD

**Issue by JaviCervera** [blitz-research/monkey2#362]
I was checking the docs to see how to manipulate rotation in an Entity, and I have realized that there is no information about that in the documentation. I see properties like Position and Scale, but no Rotation. The method Rotate does not appear either.

**Comment by nitrologic** [comment]
I think the property you may be looking for is Entity.Basis.

The issue here is possibly the definition for Basis is "Worlds space basis matrix" which is not exactly informative as it neither includes the term Orientation or Rotation.

**Comment by blitz-research** [comment]
There are a bunch of entity methods, including euelr rotation, implemented
via class extensions. These can be hard to find in the docs however, as
they are listed under the namespace along with classes, globals etc. I will
be making an honest attempt in the next month to sort out the doccing of
extension types.

**Comment by JaviCervera** [comment]
Thank you both! Ok, I found the Extensions part... it would help if next to the extended class a descriptive name for the extension was provided, since all I see now is a lot of "Entity" entries but I have to check all of them if I want something in particular...

Also, the offline docs contain module information, but I can't find the user's guide or all the other stuff that appear on the online docs.

**Comment by seyhajin** [comment]
Maybe you can close this issue.
