### ISSUE TITLE
no link from KeyEvent.Modifiers to input.Modifier

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#366]
I am guessing this may improve docs in number of places.

As pictured there is no link from KeyEvent.Modifiers help to the rather more useful input.Modifier help

Could the mojo.input.Modifier be made clickable?

<img width="270" alt="modifierlink" src="https://user-images.githubusercontent.com/3953439/38482871-191937d2-3c25-11e8-8b46-5b0ac573fecf.png">

**Comment by arpie42** [comment]
Thanks nitrologic,
Please report docs-related issues here https://github.com/mx2DocsCommunity/monkey2
This one seems related to https://github.com/mx2DocsCommunity/monkey2/issues/129

**Comment by blitz-research** [comment]
This would appear to be a makedocs bug when creating links to enums as
there's also no links for Texture.Flags:TextureFlags or
Canvas.BlendMode:BlendMode. Will look into it soon.

**Comment by nitrologic** [comment]
Thanks for fixing.
