### ISSUE TITLE
Spotlights don't work as expected + light improvements

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#374]
Hi,

Spotlights are currently giving the same results as a direction light - placement doesn't matter, only orientation, and there's no spot "angle". In addition to that, I'd like to suggest a few light improvements.

Spot lights:
1. "Range" property has no effect
2. Needs "Cone Angle", or "Spot Angle" property
3. Could use a "Radial Falloff", from the edges of the cone to the center. This could be set via a "Start Angle" - intensity multiplier is 1 below this angle, and interpolates between 1 and 0 from the start angle to the spot angle.

Lights in general:
1. An option for "Inverse Square" attenuation would be nice for realistic lighting (overrides Range)
2. For non-realistic lighting, Replacing "Range" with "Far" and "Near" wold be great!

Bonus! :-)
The Ability to use a "Gobo" (projector) texture in a spot light - the light value would be multiplied by a texture. Point lights would project the texture six times, in all orientations, and directional lights would either not support this, or use some sort of tiling size.

Here's a test scene with a little "flashlight" geometry and a light parented to it. You can change the light type to see its effect as the flashlight spins around.

```
Namespace myapp3d

#Import "<std>"
#Import "<mojo>"
#Import "<mojo3d>"

Using std..
Using mojo..
Using mojo3d..

Class MyWindow Extends Window
	
	Field _scene:Scene
	Field _camera:Camera
	Field _light:Light
	Field _ground:Model
	Field _flashlight:Model
	Field _pivot:Entity
	
	Method New( title:String="Light test",width:Int=640,height:Int=480,flags:WindowFlags=WindowFlags.Resizable )
		Super.New( title,width,height,flags )
	End
	
	Method OnCreateWindow() Override
		
		'create (current) scene
		_scene=New Scene
		_scene.ClearColor = Color.Black
		_scene.EnvColor = Color.Black
		
		'create camera
		_camera=New Camera( Self )
		_camera.AddComponent<FlyBehaviour>()
		_camera.Move( 0,2.5,-5 )
		_camera.PointAt( New Vec3f )
		
		'create ground
		Local groundBox:=New Boxf( -100,-1,-100,100,0,100 )
		Local groundMaterial:=New PbrMaterial( Color.Lime, 0.1, 0.5 )
		_ground=Model.CreateBox( groundBox,1,1,1,groundMaterial )
		_ground.CastsShadow=False
		
		'Create spinning pivot
		_pivot = New Entity
		_pivot.Move( 0,2.5,0 )
		_pivot.Visible = True
		
		'create flashlight
		Local mat:=New PbrMaterial( Color.Red, 0.05, 0.2 )
		_flashlight = Model.CreateCylinder( 0.1, 0.5, Axis.Z, 16, mat )
		_flashlight.CastsShadow = False
		_flashlight.Rotate(45, 45, 0)
		_flashlight.Parent = _pivot

		'create light
		_light=New Light
		_light.CastsShadow=False
		_light.Type = LightType.Spot
		_light.Range = 5
		_light.Parent = _flashlight
		_light.Move( 0, 0, 0.3 )
		
		'Add a "lightbulb" to the flashlight, so we know which direction it's pointing 
		Local _lightbulb := Model.CreateSphere( .1, 12, 12, New PbrMaterial( Color.White), _light )
		_lightbulb.Mesh.FlipTriangles()
		_lightbulb.Mesh.UpdateNormals()

	End
	
	Method OnRender( canvas:Canvas ) Override
		RequestRender()
		_pivot.RotateZ( 3.0 )
		_scene.Update()
		_camera.Render( canvas )
		canvas.DrawText( "FPS="+App.FPS,0,0 )
	End
	
End


Function Main()
	New AppInstance
	New MyWindow
	App.Run()
End
```

**Comment by blitz-research** [comment]
There is no spot light support at all as yet - forgot it was an enum!

**Comment by DoctorWhoof** [comment]
Works now.
Also thanks for implementing the bonus features!
