### ISSUE TITLE
Runtime issue

### ISSUE THREAD

**Issue by Mac767** [blitz-research/monkey2#377]
Hi Mark,

I just sent you a email with a (large) sample and assets (~ 5 MB).
This sample compiles find but I got a program freeze on runtime.

The same code runs fine in previous versions (1.1.08).

Kind regards
Mac767

**Comment by blitz-research** [comment]
What version does it freeze on?

**Comment by Mac767** [comment]
Dev-Branch: build 14h ago.

**Comment by blitz-research** [comment]
Did it work previous to that on develop?

**Comment by blitz-research** [comment]
There have been a lot of changes since v1.1.08, anything you can do to help
narrow down when it started freezing would be greatly appreciated.

**Comment by blitz-research** [comment]
Ok, seems to work in 2018-04 which helps...any idea where it might be
freezing?

**Comment by Mac767** [comment]
In the LoadScreen files at line 283 mostly after the second loop.
If you using the debuger and stepps through you will see in the stack trace on a sub item a memory access error. I am not sure if it always the same object

**Comment by blitz-research** [comment]
Ok, getting there! It's somewhere in CreateButtonImages...

**Comment by Mac767** [comment]
Yes but the first time it works.

**Comment by blitz-research** [comment]
Whew, fixed!

There was actually a pretty major bug in there, and it was really only luck
that meant it hadn't caused any problems earlier so thanks for bringing
this to my attention and providing a crashing example!

To test the fix, you'll need to download the latest from the github develop
branch and rebuildall2go etc.

The fix will also be in the next patreon release which should be out next
week-ish.

The game is looking very nice too!

**Comment by Mac767** [comment]
I just rebuild the latest version and it runs fine.
So thanks a lot for the fast fix!
