### ISSUE TITLE
Some primitive meshes have upside down UVs

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#387]
While playing with textures containing text, I noticed some meshes have upside down uvs:

Box: All side faces are rotated 180degrees
Box: Top face is inverted vertically
Cylinder: top face is inverted horizontally. Or maybe vertically... depends on where you're looking from... :-P

<img width="1552" alt="screen shot 2018-05-29 at 11 01 40 pm" src="https://user-images.githubusercontent.com/6250116/40702109-659f6d96-6395-11e8-95d5-45b6a4722cc1.png">
<img width="1552" alt="screen shot 2018-05-29 at 11 10 39 pm" src="https://user-images.githubusercontent.com/6250116/40702144-862ec8cc-6395-11e8-9900-49b976e68af2.png">
Thanks!

**Comment by blitz-research** [comment]
Sheesh, yer right, why did I not notice that?!?
