### ISSUE TITLE
Suggestion: OnStart() virtual method

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#390]
Hi!

While I appreciate the desire to keep Mojo3D's component system as simple as possible, there's one virtual method I feel could be incredibly helpful: Component.OnStart() ( or maybe Component.Init() ), called on all entities a single time after the Scene has finished loading, and before the first frame update. 

It could be used for all sorts of initialization things, like searching for another entity by name and then caching it into a field, procedurally applying materials, procedurally generating children entities via a component, etc.

Thanks!

**Comment by blitz-research** [comment]
I am OK with this and not particularly against quite a few useful methods
like this, but I would rather see them as component methods, not entity
methods, as that is where OnUpdate etc already happen.

Also, there should probably be a way to start a scene manually as scenes
aren't necessarily always loaded, so perhaps add a Scene.Start method too
that is automatically called the first time a scene is updated if it hasn't
been called already? Or should it always be called after loading? Just
thinking it may be useful to do some other stuff between loading a scene
and starting it...

**Comment by DoctorWhoof** [comment]
Yes, I initially wrote Entity.OnStart(), but later edited to Component.OnStart(), which is what I actually meant.

I didn't know you could load scenes but not have them "active", sounds very useful... I like the idea that the scene is auto-started if it's the only scene loaded (i.e. the first one), but any scene loaded after that would require a manual Start().

Thanks!

**Comment by blitz-research** [comment]
I would kind of like to remove 'current scene' altogether.

Instead of New Camera( parent ), New Light( parent ) etc we could have
Scene.AddCamera( parent ), Scene.AddLight( parent ) etc, similar to
Entity.AddComponent<Blah>().

Scene.GetCurrent() could remain for a while I guess but I think it'd all be
cleaner without it and only a little less convenient.

**Comment by blitz-research** [comment]
Note: just thinking out loud!

**Comment by DoctorWhoof** [comment]
If you don't want to change things too much, you could just change the constructor to "New Entity( scene, parent )", etc, where scene is required, but parent isn't.

Another way is just a broad Scene.Add( entity ), where entity can be a new Light, Model, etc, since they all extend entity anyway.

Either way, how would you create entities that "live" across multiple scenes, i.e. The main character, which has persistent attributes as he goes through different levels (scenes)? Can you just add an entity to more than one scene?

**Comment by blitz-research** [comment]
Ok, first attempt at Method Component.OnStart() Virtual pushed to develop.

I also added Scene.Start() which calls Comonent.OnStart() for every component in the scene. Scene.Load() calls this for you (is this a good idea though?) and it will also be called by first update.

Scene.Start() also starts the internal 'time/elapsed timer used by update+physics. Not sure if it should though, or if first update should start timer instead. Thoughts? Perhaps there should be 2 methods here - OnLoad and OnStart, I guess they're kind of different things?

Also, components added after scene has started will not currently have OnStart invoked. This could be added if desired though?

I was also thinking of adding Scene.Suspend() and Scene.Resume() to handling pausing the update timer when window becomes inactive or whatever - plus I guess Component.OnSuspend etc - and Scene.Stop().
