### ISSUE TITLE
request: Extension is not compatible with external classes/struct with private/no default constructor

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#392]
Wrapping the box2d lib, which is factory based, I had met a problem with 'Extension' for external classes/structs.
The 'Extension' thing is absolutely awesome for adding methods for wrapping externals (or customizing things) but the class/struct must have a public default constructor for mx2 to accept it.
Factory based libs often hide constructors so people do things the right way.. But then I had to make default constructors public, or create a default constructor c++ side in order to be able to use Extension on several classes/structs.

So if it was possible to make mx2 accept Extensions for externals without the need to have a public default constructor it would be great!

A small "Date" class to illustrate the issue
**Comment the second 'private:' line in date.h to stop compiling error.**

Thx!

date.h:
```
#ifndef DATE_H
#define DATE_H
 
class Date
{
private:
    int m_year;
    int m_month;
    int m_day;
 
public:

	~Date();
	Date(int year, int month, int day);

    void SetDate(int year, int month, int day);
 
    int getYear() { return m_year; }
    int getMonth() { return m_month; }
    int getDay()  { return m_day; }

private: //COMMENT THIS TO STOP ERROR
	   Date(); //COMMENT THIS TO GENERATE ANOTHER ERROR (default constructor needed)
	
};
 
#endif
```

date.cpp:
```
#include "date.h"
 
// default constructor
Date::Date()
	{
		SetDate(1985, 1, 1);
	}
 
// Date constructor
Date::Date(int year, int month, int day)
{
    SetDate(year, month, day);
}

Date::~Date()
{
	// nothing to do in this simple example
}
 
// Date member function
void Date::SetDate(int year, int month, int day)
{
    m_month = month;
    m_day = day;
    m_year = year;
}
```

date.monkey2:
```
#Import "<std>"

#Import "date.h"
#Import "date.cpp"

Extern 

Class Date Extends Void
	Field foo:Int
	
	Method New() 'UNCOMMENT HERE TO STOP ERROR
	
	Method New(year:Int,month:Int,day:Int)
	Method getYear:Int()
	Method getDay:Int()
	Method getMonth:Int()
End

Public

Class Date Extension
	Method sayHi()
		Print "Hi it's "+getYear()
	End
End

Function Main()

	Print "monkey2 extern class extension test"
	Print " "
	
	Local date:=New Date(2018,06,18)
	date.sayHi()

End
```

**Comment by blitz-research** [comment]
Hmm, I'm not getting an error here just running the above code 'as is'. What exactly do I have to do to generate an error?

Note that monkey2 simply uses inheritance to implement extensions currently - if you are trying to do this with an extern class with no public default ctor, it'll fail. There is no easy fix for this, but long term a different mechanism could potentially be used to implement extensions.

**Comment by blitz-research** [comment]
Hmm, nevermind, can see the error now...

**Comment by blitz-research** [comment]
OK, just pushed a fix to develop - please test!

**Comment by abakobo** [comment]
Looks like it's working now!
Thx for the quick response! With extern aliases being functional too, mx2 shapes better and better for externals, this is awesome. Thanks again!
