### ISSUE TITLE
console output bug with some MS Windows style eols

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#394]
When a string contains ~q or ~t it is sometimes wrongly shown on the console using the "Print" command, if it's eols is of mswin style (\~r\~n).

The joined zip file contains a .txt and a .monkey2 to show the problem

[mswin_eols_output_bug.zip](https://github.com/blitz-research/monkey2/files/2108510/mswin_eols_output_bug.zip)

**Comment by blitz-research** [comment]
I think this could actually be an issue with ted2go's new fancy \r handling because if I run the app from I console I get the expected output.

Can you post a bug at ted2go repos?

**Comment by abakobo** [comment]
referenced the issue on engor's ted2go repo..
