### ISSUE TITLE
Documentation stops on quotes

### ISSUE THREAD

**Issue by seankarol** [blitz-research/monkey2#395]
Hello,

I've been noticing random documentations that suddenly end mid-sentence and I believe I've narrowed it down to line being truncated whenever an `'` is encountered.

I've attached a few examples.

https://github.com/blitz-research/monkey2/blob/862ec4e7bea1e72658c8c7eca4c31c0db5caa7cb/modules/mojo/app/window.monkey2#L139

https://github.com/blitz-research/monkey2/blob/862ec4e7bea1e72658c8c7eca4c31c0db5caa7cb/modules/std/collections/deque.monkey2#L18

https://github.com/blitz-research/monkey2/blob/862ec4e7bea1e72658c8c7eca4c31c0db5caa7cb/modules/std/collections/map.monkey2#L24

When I look at these in my docs I see:

`Switches to `

`A deque is a `

`Maps can handle inserting, removing and finding keys in `

This doesn't seem to affect the initial summary line found immediately after `#Rem monkeydoc ...`, only subsequent lines.

**Comment by blitz-research** [comment]
Eeek, well spotted, docs were being 'commented out'!

A fix has been pushed to develop branch.

**Comment by seankarol** [comment]
Awesome, it's working here. Thank you.
