### ISSUE TITLE
Public/Private access: Is this meant to be a runtime error?

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#397]
/not a big deal, mainly out of interest...

Only just noticed this, but I thought access to a private member would throw up a compiler error (actually thought it did until now)...

```

#Import "<std>"

Using std..

Class Test
	Private
	Field x:Int
	Method TestX:Int ()
		Return x
	End
	Public
	Field y:Int
	Method TestY:Int ()
		Return y
	End
End

Function Main ()
	Local t:Test
	t.x = 1
	t.y = 2
	Print t.x
	Print t.y
	Print t.TestX ()
	Print t.TestY ()
End

```
Even in debug, this just throws up an illegal access.

It seems like something the compiler ought to mention instead of running... or is there a reason it works this way?

C++ flags it:
```

// ConsoleApplication1.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <iostream>

class Test
{
private:
		int test1;
public:
		int test2;
};

int main()
{
	Test t;
	t.test1 = 1; // "member "Test::test1" (declared at line 10) is inaccessible"
	t.test2 = 1; // OK
	return 0;
}

```

Brucey's (mx1-based) bmx-ng picks it up (though, interestingly, mx1 and BRL BlitzMax don't).

![private](https://user-images.githubusercontent.com/1781537/41820219-d70f7afe-77c5-11e8-9fe2-cbc6a5731fd3.jpg)

I'd obviously hallucinated that BRL languages picked up on illegal member accesses, but it feels like something the compiler should be flagging -- I'd imagine most mainstream languages would do this, surely, I mean besides C++?

**Comment by blitz-research** [comment]
Code in the same file can access private members.

**Comment by DruggedBunny** [comment]
Ohhhhhh... succinct! Apologies!
