### ISSUE TITLE
TED2 OSX user finetuning

### ISSUE THREAD

**Issue by gcmartijn** [blitz-research/monkey2#40]
The default copy/past keys for osx users are CMD+C and CMD+V
Its a small thing, but maybe its easy to add this extra shortcut :)

Same for CMD+S (save) and maybe other keys
CMD+F (search)

Double press mouse on text to highlight the word

**Comment by DoctorWhoof** [comment]
Some more super helpful MacOS shortcuts...
Cmd+W to close current file
Cmd+N for new file
Cmd+O for open file
Alt+left, Alt+right to jump to previous/next word (shift to select while jumping)
Cmd+left, Cmd+Right to jump to Beginning/End of line (same as Home and End on a full keyboard)
Cmd+Q to quit.

Is custom shortcuts somewhere on the roadmap? I'd love things like Cmd+B to build, etc.
Thanks!

**Comment by blitz-research** [comment]
New ted2 should now have correct shortcut keys for Mac.
