### ISSUE TITLE
Spaces in OS X source path cause Ted 2 to fail to run app

### ISSUE THREAD

**Issue by Arjailer** [blitz-research/monkey2#41]
On OS X when the source path contains spaces Ted 2 builds the code okay, but it doesn’t actually run the built code. The built applications are in the expected output folders and if I run them manually they work fine, but Ted 2 doesn’t seem to want to run them.

Using a source path without spaces everything works as expected.

**Comment by blitz-research** [comment]
Seems to be fixed.
