### ISSUE TITLE
g++: error trying to exec 'cc1plus': execvp: No such file or directory

### ISSUE THREAD

**Issue by fabiuz** [blitz-research/monkey2#414]
I use linux fedora, version 28.
Obs.: I already compile a source  before, but, now, when try compile a new project this error show:

Build error: System command failed:

g++ -c  -std=c++11 -O3 -DNDEBUG -I"/opt/monkey2/modules/" -I"/opt/monkey2/modules/monkey/native" -I"/opt/monkey2/modules/portmidi/pm_common/" -I"/opt/monkey2/modules/portmidi/porttime/" -o "/opt/monkey2/modules/portmidi/portmidi.buildv1.1.09/linux_release/build/portmidi_0portmidi.cpp.o" "/opt/monkey2/modules/portmidi/portmidi.buildv1.1.09/linux_release/src/portmidi_portmidi.cpp"

g++: error trying to exec 'cc1plus': execvp: No such file or directory

**Comment by blitz-research** [comment]
You may need to update/rebuild mx2cc, v1,1.09 is kind of old.

Have you tried a './rebuildall2go.sh' o9r even just an './updatemx2cc.sh'
for the monkey2/scripts dir?

**Comment by fabiuz** [comment]
Hi, I try './rebuildall2go.sh',
Now, I tryed an another option './updatemx2cc.sh', there is an error too.

**Comment by fabiuz** [comment]
Hi, I detect the problem.
There were 2 gcc-c++, 1 in /usr/bin/gcc-c++ and other in /opt/gps/bin.
Because, I recently there were installed an ide for language ADA.
I uninstalled ide for language Ada and I deleted the path /opt/gps and subdirectories.
Then, I executed ./rebuildall.sh, this compiled correctly.

**Comment by blitz-research** [comment]
Yikes, good to know!
