### ISSUE TITLE
Time.Now formatting

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#421]
Time.Now returns (eg.) "Tue 28 Aug 2018 0:48:**3**" instead of "Tue 28 Aug 2018 0:48:**03**".

Perhaps the hours should be **0**x as well?

Guessing minutes will follow same 1-digit format too...

**Comment by blitz-research** [comment]
Ok I've padded all the number including 'day'.

**Comment by DruggedBunny** [comment]
Cool, thanks, Mark.
