### ISSUE TITLE
Adding check-up to mx2cc

### ISSUE THREAD

**Issue by StrangeIsMyName** [blitz-research/monkey2#43]
ok, this is a small amendment to add checking to mx2cc
in function main:
line 55 = 
`		Print "Usage: mx2cc makeapp|makemods|makedocs|checkapp [-run] [-clean] [-verbose] [-target=desktop|emscripten] [-config=debug|release] source|modules..."
`
add line 71,72=
`		Case "makeapp"
			MakeApp( args )
`
add new function:
`Function CheckApp( args:String[] )

	Local opts:=New BuildOpts
	opts.productType="app"
	opts.appType="gui"
	opts.target="desktop"
	opts.config="debug"
	opts.clean=False
	opts.fast=True
	opts.run=true
	opts.verbose=0
	
	args=ParseOpts( opts,args )
	
	If args.Length<>1 Fail( "Invalid app source file" )
	
	Local cd:=CurrentDir()
	ChangeDir( StartDir )
	Local srcPath:=RealPath( args[0].Replace( "\","/" ) )
	ChangeDir( cd )
	
	opts.mainSource=srcPath
	
	Print ""
	Print "***** Checking app '"+opts.mainSource+"' *****"
	Print ""

	Local builder:=New Builder( opts )
	
	builder.Parse()
	If builder.errors.Length Return
	
	builder.Semant()
	If builder.errors.Length Return
	
	Print "Application Checked"
End
`

**Comment by blitz-research** [comment]
Checking will happen but later.
