### ISSUE TITLE
Linker error with RequestDir

### ISSUE THREAD

**Issue by D-a-n-i-l-o** [blitz-research/monkey2#449]
The following code produces a linker error "missing symbols" on macOS using the Desktop target.

```
#Import "<std>"

Function Main()
    
    Local directory:String = std.requesters.RequestDir( "Select directory", "/" )

    Print directory

End
```

Adding the following line to the code above fixes the linker error:

`#Import "<mojo>"`

The error message:

```
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      bbRequesters::OpenUrl(bbString) in std.a(macos623863f4.mm.o)
  "_CFURLCreateWithBytes", referenced from:
      bbRequesters::OpenUrl(bbString) in std.a(macos623863f4.mm.o)
  "_LSOpenCFURLRef", referenced from:
      bbRequesters::OpenUrl(bbString) in std.a(macos623863f4.mm.o)
  "_NSApp", referenced from:
      (anonymous namespace)::beginPanel() in std.a(macos623863f4.mm.o)
```

**Comment by blitz-research** [comment]
Ok, I've pushed a fix for this.

I recommend #importing mojo anyway (and adding New AppInstance at the top
of main) otherwise the directory requester won't have initial focus (well
it doesn't here, I'm guessing because a std app is not a gui app, it's just
a console app).

**Comment by D-a-n-i-l-o** [comment]
Thanks, no linker error anymore. :thumbsup:
