### ISSUE TITLE
memory access violation with vec2f

### ISSUE THREAD

**Issue by StrangeIsMyName** [blitz-research/monkey2#46]
tested in ted21 and ted2

Mark, this was brought to me and confirmed with both ted21 and ted2, so I am assuming it is a proper bug:

`Namespace myapp
 
#Import "<std>"
#Import "<mojo>"
 
Using std..
Using mojo..
 
Class MyWindow Extends Window
 
	Method New()
		Local FrameSetCollection:StringMap<FrameSet> = New StringMap<FrameSet>()
	
		Local player:Player =  New Player(FrameSetCollection, "Bla", 200, 300)
	End
	
	Method OnRender( canvas:Canvas ) Override
		canvas.DrawText( "Hello World",Width/2,Height/2,.5,.5 )
	End
End
 
Function Main()
	New AppInstance
	New MyWindow
	App.Run()
End
 
 
Class FrameSet
 
	Field Position:= New Vec2f
	Field Vector:= New Vector()
	
	Method Move:Void(_mx:Float, _my:Float)
	'	Print _mx
	'	Print _my
	
	' HERE IS THE ERROR,  CREATING NEW VEC2F
	'
	'
		Position=New Vec2f
	'	Vector.x =  2
	'	Vector.Set(3)
	'	Position =  New Vec2f(_mx,_my)
	End
End Class
 
Class Sprite
	Field FrameSetCollection:StringMap<FrameSet>
	Field FrameSetColKey:String
 
	Method New(_FrameSetCollection:StringMap<FrameSet>,_FrameSetColKey:String)
		FrameSetCollection = _FrameSetCollection
		FrameSetColKey = _FrameSetColKey
		
	'	FrameSetCollection.Add(FrameSetColKey, New FrameSet)
	End
End Class
 
Class Vector
	Field x:Float
	
	Method Set(_x:Float)
		x= _x
	End
End Class
 
Class Player Extends Sprite
 
	Method New(_FrameSetCollection:StringMap<FrameSet>,
		_FrameSetColKey:String,
		_initX:Float,
		_initY:Float)
		Super.New(_FrameSetCollection,_FrameSetColKey)
	
		_FrameSetCollection.Get(_FrameSetColKey).Move(_initX,_initY)
	End
End Class`
The offending line is found in Frameset:

Position=New Vec2f

**Comment by gcmartijn** [comment]
no, you can close this ticket.
solved in a other topic ;) miscommunication.

**Comment by StrangeIsMyName** [comment]
solved by sender
