### ISSUE TITLE
TED2 crashes

### ISSUE THREAD

**Issue by gcmartijn** [blitz-research/monkey2#47]
I have this on osx in Ted2 latest version

Ted21 crashes the second time when I run (in debug mode) a “error generated script” or using DebugStop() after not stopping the debug process (red button, in debug view) first.

so here is the full process.
1. start a error generated script OR a good script using DebugStop() in debug mode
2. ted2 keeps alive and opens the debug view
3. on the osx background I kill the program manual (force kill) (not in ted2)
4. I re run in debug mode (or change some lines first) - ted2 crashes (goes away)
5. repeat 3.

To solve this, I guess you must clear / invoke that debug stop button (in the debug window) before every start in debug mode

**Comment by gcmartijn** [comment]
with the new version, it crashes when I do this
1. start monkey2
2. choose new
3. choose save as

and 
2. choose new..
3. choose new app.
4. choose save

Din't check if the others things are fixed yet.

**Comment by blitz-research** [comment]
Neither of these cause a crash for me!

What OS are you on?

**Comment by gcmartijn** [comment]
latest osx
Model: MacBookAir6,2, BootROM MBA61.0099.B22, 2 processors, Intel Core i5, 1,4 GHz, 4 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In

I can test another later this week.

At ./rebuildall.sh I only had this one, maybe its related ?
***** Doccing module 'mojo' *****

Parsing...
Semanting...
MarkdownBuffer: unrecognized directive @see in @see [[ActiveWindow]], [[MouseX]], [[MouseY]]

**Comment by gcmartijn** [comment]
Other Imac with latest osx the same problem.

The problem is bigger then I thought.
- if I open a document
- then save as... crash

- if I open a document
- change something
- then save, no crash

I don't have a third osx maybe someone else have the same problem ?

**Comment by gcmartijn** [comment]
I don't know if you are going to fix it ?
I was hoping to give you more info, but the only thing what I did try was hoping to get more info for you.

What I did now was opening src/ted2/fileactions.monkey2
Then I uncomment line by line till the Ted2 crashes

It crashes at the line / method RequestFile

Method OnSaveAs()
		Local doc:=_docs.CurrentDocument
		If Not doc Return
			
		Local path:=RequestFile( "Save As","",True )
	'	If Not path Return
