### ISSUE TITLE
MX2 Import error

### ISSUE THREAD

**Issue by Endrem** [blitz-research/monkey2#48]
With the new build (1.0.3) whenever I import SDL2, I get an error.

lnkFiles1:
`"C:/Users/Admin/Desktop/Substruct/Substruct.buildv1.0.3/build_cache/desktop_debug_windows/Substruct_0Substruct.cpp.o" "C:/Workbench/Monkey2/modules/sld2/sld2.buildv1.0.3/desktop_debug_windows/sld2.a" "C:/Workbench/Monkey2/modules/mojo/mojo.buildv1.0.3/desktop_debug_windows/mojo.a" "C:/Workbench/Monkey2/modules/std/std.buildv1.0.3/desktop_debug_windows/std.a" "C:/Workbench/Monkey2/modules/stb-vorbis/stb-vorbis.buildv1.0.3/desktop_debug_windows/stb-vorbis.a" "C:/Workbench/Monkey2/modules/stb-image-write/stb-image-write.buildv1.0.3/desktop_debug_windows/stb-image-write.a" "C:/Workbench/Monkey2/modules/stb-image/stb-image.buildv1.0.3/desktop_debug_windows/stb-image.a" "C:/Workbench/Monkey2/modules/miniz/miniz.buildv1.0.3/desktop_debug_windows/miniz.a" "C:/Workbench/Monkey2/modules/sdl2/sdl2.buildv1.0.3/desktop_debug_windows/sdl2.a" "C:/Workbench/Monkey2/modules/openal/openal.buildv1.0.3/desktop_debug_windows/openal.a" "C:/Workbench/Monkey2/modules/gles20/gles20.buildv1.0.3/desktop_debug_windows/gles20.a" "C:/Workbench/Monkey2/modules/libc/libc.buildv1.0.3/desktop_debug_windows/libc.a" "C:/Workbench/Monkey2/modules/freetype/freetype.buildv1.0.3/desktop_debug_windows/freetype.a" "C:/Workbench/Monkey2/modules/emscripten/emscripten.buildv1.0.3/desktop_debug_windows/emscripten.a" "C:/Workbench/Monkey2/modules/monkey/monkey.buildv1.0.3/desktop_debug_windows/monkey.a" -lcomdlg32 "C:/Workbench/Monkey2/modules/openal/openal-soft/lib/OpenAL32.lib" "C:/Workbench/Monkey2/modules/gles20/angle/lib/libEGL.lib" "C:/Workbench/Monkey2/modules/gles20/angle/lib/libGLESv2.lib" -ldsound -lxinput -ldinput -lole32 -loleaut32 -limm32 -lwinmm -lgdi32 -luser32 -lkernel32 -lversion`

stderr1:
`C:/Workbench/Monkey2/devtools/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find C:/Workbench/Monkey2/modules/sld2/sld2.buildv1.0.3/desktop_debug_windows/sld2.a: No such file or directory
collect2.exe: error: ld returned 1 exit status`

I turns out I mistyped SDL for SLD but MX2 did not catch it

**Comment by blitz-research** [comment]
#Import "<sld>" now generates error: can't find module 'sld'
