### ISSUE TITLE
Building a module fails if module is a symlink

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#5]
Hi,

I used symlinks a lot to organize my modules outside the monkey1 folder. A simple shell command file recreates all symlinks inside the modules folder (for my own modules and other 3rd party modules) after I download a new Monkey release. But this approach is not working in monkey2. 

This is the error. I'm on OS X EL Capitan, using release V008.

****\* Making module 'renderwindow' *****

Parsing...
Semanting...
Translating...
Compiling....
Build error: System command 'g++ -std=c++11 -Wno-deprecated-declarations -Wno-tautological-pointer-compare -Wno-undefined-bool-conversion -Wno-int-to-void-pointer-cast -Wno-inconsistent-missing-override -Wno-logical-op-parentheses -Wno-parentheses-equality -O0 -I"/Applications/Leo/Blitz/monkey2/modules/freetype/freetype-2.6.3/include/" -I"/Applications/Leo/Blitz/monkey2/modules/sdl2-mixer/SDL_mixer/" -I"/Applications/Leo/Blitz/monkey2/modules/sdl2/SDL/include/" -I"/Applications/Leo/Blitz/monkey2/modules/monkey/native" -c -o "/Applications/Leo/Blitz/monkey2/modules/renderwindow/renderwindow.buildv008/build_cache/desktop_debug_macos/renderwindow_0renderwindow.cpp.o" "/Applications/Leo/Blitz/monkey2/modules/renderwindow/renderwindow.buildv008/build_cache/desktop_debug_macos/renderwindow_renderwindow.cpp"' failed.

g++ -std=c++11 -Wno-deprecated-declarations -Wno-tautological-pointer-compare -Wno-undefined-bool-conversion -Wno-int-to-void-pointer-cast -Wno-inconsistent-missing-override -Wno-logical-op-parentheses -Wno-parentheses-equality -O0 -I"/Applications/Leo/Blitz/monkey2/modules/freetype/freetype-2.6.3/include/" -I"/Applications/Leo/Blitz/monkey2/modules/sdl2-mixer/SDL_mixer/" -I"/Applications/Leo/Blitz/monkey2/modules/sdl2/SDL/include/" -I"/Applications/Leo/Blitz/monkey2/modules/monkey/native" -c -o "/Applications/Leo/Blitz/monkey2/modules/renderwindow/renderwindow.buildv008/build_cache/desktop_debug_macos/renderwindow_0renderwindow.cpp.o" "/Applications/Leo/Blitz/monkey2/modules/renderwindow/renderwindow.buildv008/build_cache/desktop_debug_macos/renderwindow_renderwindow.cpp"

/Applications/Leo/Blitz/monkey2/modules/renderwindow/renderwindow.buildv008/build_cache/desktop_debug_macos/renderwindow_renderwindow.cpp:6:10: fatal error: '../../../../mojo/mojo.buildv008/desktop_debug_macos/mojo_app_2app.h' file not found
# include "../../../../mojo/mojo.buildv008/desktop_debug_macos/mojo_app_2app.h"

```
     ^
```

1 error generated.

****\* Fatal mx2cc error *****

**Comment by blitz-research** [comment]
Hqve you got a *simple* way for me to reproduce this?

**Comment by DoctorWhoof** [comment]
Sure:
1. Create a module in a folder **outside** Monkey2/modules
2. In a command shell, go to the modules folder and run:
`ln -s /pathtomodule/testmodule`
3. This will create a symlink to that folder that acts as if it's the real thing.
4. Go to the  bin folder, run `./mx2cc_macos makemods testmodule`
5. That will fail, even though the symlink should have behaved just as if the folder is there.

Thanks!

**Comment by nitrologic** [comment]
I suspect the fix will be to remove the use of ../../../.. by mx2cc. One of the problems with softlinks is they don't play friendly with .. (you end up in the real parents folder not the softlink locations parent)

using %monkey2%/modules/ instead of ../../.. based paths could be a possible solution

**Comment by wiebow** [comment]
It would be great if this could be fixed because it will remove the need to move/reposition custom module folders during monkey updates.

**Comment by DoctorWhoof** [comment]
I believe this is fixed now on 1.1.06, at least on MacOS!
