### ISSUE TITLE
Compiler Error - Problem with forward referencing.

### ISSUE THREAD

**Issue by legionnairex2** [blitz-research/monkey2#52]
I got a program that gives me an error when I try to pass a pointer to a method but only when I pass one of its fields:

	Method InitLevel1()
		ufoManager = New UfoManager(playerManager.player.pos) '************
		
	End Method
to this method on another Class:

	Method New(playerPos:PVector2D) '******************
		Super.New()
		state = State.ENTERING
		Self.playerPos = playerPos '****************
	End Method
and I get this error:

/Users/ayoitseve/Desktop/monkeypatrol/monkeypatrol.buildv1.0.3/build_cache/desktop_debug_macos/monkeypatrol_src_2entity.h:11:8: note: forward declaration of 't_default_PVector2D'
struct t_default_PVector2D;
^
1 error generated.
***** Fatal mx2cc error *****

Internal mx2cc build error

If I pass the object  I don't get the error only if I pass the field:

	Method InitLevel1()
		ufoManager = New UfoManager(playerManager.player) '**********
		
	End Method
		
	Method New(player:Vehicle) '********************************************
		Super.New()
		state = State.ENTERING
		Self.playerPos = player.pos  '*************************************
	End Method
this does not give me an error and works fine.

**Comment by AmonUK** [comment]
Is the field you are passing from the Class public, private etc?

**Comment by blitz-research** [comment]
I *may* have fixed this, but I can't really test your code 'as is'.

You'll need to post some 'runnable' code, ie: code I can just copy, paste and run without having to 'guess' all the missing bits.
