### ISSUE TITLE
Ted2 on Linux cannot open any file, causes system lockdown

### ISSUE THREAD

**Issue by wiebow** [blitz-research/monkey2#57]
When I try to open a file using File / Open, the requester appears and then the ted2 process is locking up my machine. I am running Linux Mint 18.  I can only close ted by opening a terminal and entering the command  **kill -KILL ted2processid**

This prevents me from using the debugger on Linux.

**Comment by abakobo** [comment]
Had the same issue but it's only the mouse that won't click on anything.

I can still escape the file requester with esc key, use tab, arrows, return to chose a file. The same happens for "project open" and "save as". So it's not a total lockdown on my systems (mint 17.1 and 18)

**Comment by blitz-research** [comment]
It seems to be intermitent - if I repeatedly Esc/Open/Esc/Open it
eventually works here.

Think I'll replace the linux native dialogs with custom mojox one's soon...

**Comment by wiebow** [comment]
OK, I'll battle on until this has changed then. I tried again today and it's locking up here each and every time.

**Comment by blitz-research** [comment]
For a quick 'n' dirty fix, try manually adding "/" (or any dir) to the
"openProjects" section in bin/ted2.state.json, and then using the filetree
to open stuff.

**Comment by wiebow** [comment]
Thank.  Let me close this issue for now then!
