### ISSUE TITLE
Caseless Select makes C++ cry

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#6]
Function Main()
	Local a:=0
	Select a
	Default
		Print "yeh"
	End
End

Causes following output:

> /Users/simon/test1.buildv011/build_cache/desktop_release_macos/test1_test1.cpp:16:1: error: extraneous closing brace ('}')
}
^
2 errors generated.

**Comment by blitz-research** [comment]
Fixed - Select statements must now have at least one case.
