### ISSUE TITLE
Enumerator bug.

### ISSUE THREAD

**Issue by legionnairex3** [blitz-research/monkey2#65]
I was using  a global enumeration created in a file that contained common code so I could use the enumerator as a common variable. but for some reason I keep getting an error at the compiler level.
it creates the error with the case select commands.
I get this error:
Build error system g++ -std=c++11 -Wno-deprecated-declaration -Wno-tautological-pointer-compare -Who-undefined-bool-conversion -Wno-int-to-void-pointer-cast -Wno-inconsistent-missing-override -Wno-logical-op-parentheses -Wno parentheses-equality-OO

this is the code:
in common.monkey2 I have this:

Enum EntityState
	ENTERING
	UPDATING
	EXPLODING
	ENDING
	DONE
End Enum

and in another file I have this:

		Select state
			Case   EntityState.ENTERING '*************** error is here *********** ???????
				If pos.y < 200+offsetY
					pos.Add(0,1)
				Else
				'	state = EntityState.UPDATING
				Endif

**Comment by legionnairex3** [comment]
Interesting, I added this:
`Global this:= EntityState.ENTERING
`
at the beginning of the file and all of the errors disappear.

**Comment by blitz-research** [comment]
Can't reproduce this - can you post a runnable sample, ie: something with a 'Main' in it not just a code fragment?

**Comment by legionnairex3** [comment]
here is the source code with the error. The error is in ufoManager. remove the comment mark from line 30 to fix error.

https://www.dropbox.com/s/wjgt5kjzounjwzb/MissionPatrol.zip?dl=0

**Comment by legionnairex3** [comment]
no it’s not solved. with the latest update:
here is the code with the error:

**Comment by blitz-research** [comment]
Missing files alienamanager and spidermanager...

Have you done an 'updatemx2cc' with the latest mx2 code?

**Comment by legionnairex3** [comment]
Ups, compressed the wrong zip file
here is the file:


here is the link if the attachment does not work:
https://www.dropbox.com/s/u2a6c05sxzt7jb8/MissionPatrol%20.zip?dl=0 <https://www.dropbox.com/s/u2a6c05sxzt7jb8/MissionPatrol%20.zip?dl=0>

**Comment by legionnairex3** [comment]
uncomment line 30 in ufoManager to make it work.

**Comment by blitz-research** [comment]
It's working here, with or without the global in ufomanager commented out.

If updatemx2cc with the latest code isn't solving it, then wait a few days
until I get a new mx2cc binary up and try again.

The game's looking good too!

**Comment by legionnairex3** [comment]
that is crazy, I have the latest tools for OS X, (are you trying it on a Mac? ) including the compiler. so I don’t know what could be wrong.

about a month ago  my computer battery failed and it interrupted the Macbook while I was using it. after replacing the battery it got a bunch of system errors I had to repair the system. after reinstalling and updating some system files I got it to finally use it. I checked for updates and tried to compile with monkey2 and got some weird errors. so I reinstalled the system tools including the compiler and everything seems to be ok. except for that error. I am going go post the code in the forums and find out if somebody else has the same problem otherwise it is probably on my macbook only.

>The game's looking good too!

Thanks. I have 3 more stages that are a complete twist from the original.   I am going to eventually post it in Github for everybody who want’s to look at the source code can grab it. but it’s going to be a while for that. I am trying  to make everything procedural even sounds but I might eventually leave it with pre-made  sounds like I have it right now if I can’t figure out how to do that.

…And thanks for looking into it

           Jesse

**Comment by blitz-research** [comment]
Can you confirm you have run ./updatemx2cc.sh from the dev/monkey2/scripts
dir?

**Comment by legionnairex3** [comment]
after you emailed me the first time, I downloaded the latest update from Github and it’s where I am running it from.

**Comment by legionnairex3** [comment]
here:

**Comment by blitz-research** [comment]
Try again!

**Comment by legionnairex3** [comment]
No, It keeps on giving me the same error.
.

**Comment by legionnairex3** [comment]
Finally solved,  you were right I updated the mx2cc and it worked.

Thanks a million.
