### ISSUE TITLE
Ted2 fails to repaint window from minimized state.

### ISSUE THREAD

**Issue by RichardBetson** [blitz-research/monkey2#66]
Hi,

Ted2 will fail to repaint (draw window contents) the window when restored or maximized from a minimized sate. The window border and title bar are present but the contents of the window are are not draw. The effect is a see through window. Moving the mouse or resizing after leaving the minimized state will get the Ted2 window to redraw.

I'm using Linux Mint 17.2 KDE. Nvidia GTX 950.
MX2: v1.04

**Comment by RichardBetson** [comment]
This issue persists on Mint 18 Mate and 17.2, 17.3 KDE. FYI.

Ted2 also seems to have a similar repaint issue when a window is on top of Ted2.

**Comment by Rumphiz** [comment]
This issue also affects Windows 7 Pro with Intel(R) HD integrated graphics, since ted2 1.0.

**Comment by RichardBetson** [comment]
This issue looks to be solved on Linux Mint with the latest commit.
