### ISSUE TITLE
Ted2 has erratic redraw of both the console and side pannel.

### ISSUE THREAD

**Issue by RichardBetson** [blitz-research/monkey2#67]
Hi,

When I resize the console window or side panel in Ted2 they will wildly jump around in width or height. This issue has been present at least from v1.0.

I am using Linux Mint 17.2 KDE. Nvidia GTX 950.
MX2 v1.04

**Comment by blitz-research** [comment]
Probably not much I can do about this - the linux window manager is messy
and complex, and this is an ongoing issue with most SDL2 apps.

**Comment by RichardBetson** [comment]
I will test Ted2 on Mint 18 Mate and 17.3 KDE to see if the issue is persist on various versions of Mint. Aside from that lets hope a solution is found at some point. ;)

**Comment by RichardBetson** [comment]
OK, this issue persists on Mint 18 Mate and 17.2, 17.3 KDE. FYI.

**Comment by wiebow** [comment]
If you move the mouse REALLY slowly, it is fine!!!  :+1:
