### ISSUE TITLE
Parser misses "If Struct" when compiling modules

### ISSUE THREAD

**Issue by peterigz** [blitz-research/monkey2#7]
I noticed that if I'm checking to see if a struct exists (which you can't do like you can with objects) within a module it misses it in the parser/semanting stage and only throws the error when it tries compiling with c++.

Example:

```
Struct Test
	Field x:Int
	Field y:Int
End

Function Main()

	Local s:=New Test
	
	If s
		Print "s doesn't exist"
	End

End
```

Edit: Does actually throw the error making an app as well.

**Comment by blitz-research** [comment]
Fixed.
