### ISSUE TITLE
OSX ted2/monkey not working anymore

### ISSUE THREAD

**Issue by gcmartijn** [blitz-research/monkey2#80]
The September 5th, 2016 worked oke, but the today version I download don't work.
It does create a Monkey2 (Macos) file, but don't execute a thing.
The compile output with some errors.

./rebuildall.sh

***** Rebuilding modules *****

mx2cc version 1.0.5

***** Making module 'monkey' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/monkey/monkey.buildv1.0.5/macos_release/monkey.a...

***** Making module 'emscripten' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/emscripten/emscripten.buildv1.0.5/macos_release/emscripten.a...

***** Making module 'freetype' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/freetype/freetype.buildv1.0.5/macos_release/freetype.a...

***** Making module 'libc' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/libc/libc.buildv1.0.5/macos_release/libc.a...

***** Making module 'gles20' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/gles20/gles20.buildv1.0.5/macos_release/gles20.a...

***** Making module 'hoedown' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/hoedown/hoedown.buildv1.0.5/macos_release/hoedown.a...

***** Making module 'litehtml' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/litehtml/litehtml.buildv1.0.5/macos_release/litehtml.a...

***** Making module 'miniz' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/miniz/miniz.buildv1.0.5/macos_release/miniz.a...

***** Making module 'stb-image' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-image/stb-image.buildv1.0.5/macos_release/stb-image.a...

***** Making module 'stb-image-write' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-image-write/stb-image-write.buildv1.0.5/macos_release/stb-image-write.a...

***** Making module 'stb-vorbis' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-vorbis/stb-vorbis.buildv1.0.5/macos_release/stb-vorbis.a...

***** Making module 'std' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/std/std.buildv1.0.5/macos_release/std.a...

***** Making module 'sdl2' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/sdl2/sdl2.buildv1.0.5/macos_release/sdl2.a...

***** Making module 'openal' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/openal/openal.buildv1.0.5/macos_release/openal.a...

***** Making module 'mojo' *****

Parsing...
Semanting...
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [283] : Error : Identifier 'dw' not found
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [284] : Error : Identifier 'dw' not found

***** Making module 'mojox' *****

Parsing...
Semanting...
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [283] : Error : Identifier 'dw' not found
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [284] : Error : Identifier 'dw' not found

***** Making module 'sdl2-mixer' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/sdl2-mixer/sdl2-mixer.buildv1.0.5/macos_release/sdl2-mixer.a...

***** Making module 'stb-truetype' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-truetype/stb-truetype.buildv1.0.5/macos_release/stb-truetype.a...
mx2cc version 1.0.5

***** Making module 'monkey' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/monkey/monkey.buildv1.0.5/macos_debug/monkey.a...

***** Making module 'emscripten' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/emscripten/emscripten.buildv1.0.5/macos_debug/emscripten.a...

***** Making module 'freetype' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/freetype/freetype.buildv1.0.5/macos_debug/freetype.a...

***** Making module 'libc' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/libc/libc.buildv1.0.5/macos_debug/libc.a...

***** Making module 'gles20' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/gles20/gles20.buildv1.0.5/macos_debug/gles20.a...

***** Making module 'hoedown' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/hoedown/hoedown.buildv1.0.5/macos_debug/hoedown.a...

***** Making module 'litehtml' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/litehtml/litehtml.buildv1.0.5/macos_debug/litehtml.a...

***** Making module 'miniz' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/miniz/miniz.buildv1.0.5/macos_debug/miniz.a...

***** Making module 'stb-image' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-image/stb-image.buildv1.0.5/macos_debug/stb-image.a...

***** Making module 'stb-image-write' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-image-write/stb-image-write.buildv1.0.5/macos_debug/stb-image-write.a...

***** Making module 'stb-vorbis' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-vorbis/stb-vorbis.buildv1.0.5/macos_debug/stb-vorbis.a...

***** Making module 'std' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/std/std.buildv1.0.5/macos_debug/std.a...

***** Making module 'sdl2' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/sdl2/sdl2.buildv1.0.5/macos_debug/sdl2.a...

***** Making module 'openal' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/openal/openal.buildv1.0.5/macos_debug/openal.a...

***** Making module 'mojo' *****

Parsing...
Semanting...
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [283] : Error : Identifier 'dw' not found
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [284] : Error : Identifier 'dw' not found

***** Making module 'mojox' *****

Parsing...
Semanting...
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [283] : Error : Identifier 'dw' not found
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [284] : Error : Identifier 'dw' not found

***** Making module 'sdl2-mixer' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/sdl2-mixer/sdl2-mixer.buildv1.0.5/macos_debug/sdl2-mixer.a...

***** Making module 'stb-truetype' *****

Parsing...
Semanting...
Translating...
Compiling...
Archiving /Users/gcmartijn/Downloads/monkey2-master/modules/stb-truetype/stb-truetype.buildv1.0.5/macos_debug/stb-truetype.a...

***** Rebuilding ted2 *****

mx2cc version 1.0.5

***** Building app '/Users/gcmartijn/Downloads/monkey2-master/src/ted2/ted2.monkey2' *****

Parsing...
Semanting...
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [283] : Error : Identifier 'dw' not found
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [284] : Error : Identifier 'dw' not found
mx2cc version 1.0.5

***** Building app '/Users/gcmartijn/Downloads/monkey2-master/src/launcher/launcher.monkey2' *****

Parsing...
Semanting...
Translating...
Compiling...
Linking /Users/gcmartijn/Downloads/monkey2-master/src/launcher/launcher.buildv1.0.5/macos_release/launcher.app/Contents/MacOS/launcher...
Application built:/Users/gcmartijn/Downloads/monkey2-master/src/launcher/launcher.buildv1.0.5/macos_release/launcher.app/Contents/MacOS/launcher
cp: ../src/ted2/ted2.buildv1.0.5/macos_release/ted2.app: No such file or directory
mx2cc version 1.0.5

***** Doccing module 'monkey' *****

Parsing...
Semanting...

***** Doccing module 'emscripten' *****

Parsing...
Semanting...

***** Doccing module 'freetype' *****

Parsing...
Semanting...

***** Doccing module 'libc' *****

Parsing...
Semanting...

***** Doccing module 'gles20' *****

Parsing...
Semanting...

***** Doccing module 'hoedown' *****

Parsing...
Semanting...

***** Doccing module 'litehtml' *****

Parsing...
Semanting...

***** Doccing module 'miniz' *****

Parsing...
Semanting...

***** Doccing module 'stb-image' *****

Parsing...
Semanting...

***** Doccing module 'stb-image-write' *****

Parsing...
Semanting...

***** Doccing module 'stb-vorbis' *****

Parsing...
Semanting...

***** Doccing module 'std' *****

Parsing...
Semanting...

***** Doccing module 'sdl2' *****

Parsing...
Semanting...

***** Doccing module 'openal' *****

Parsing...
Semanting...

***** Doccing module 'mojo' *****

Parsing...
Semanting...
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [283] : Error : Identifier 'dw' not found
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [284] : Error : Identifier 'dw' not found

***** Doccing module 'mojox' *****

Parsing...
Semanting...
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [283] : Error : Identifier 'dw' not found
/Users/gcmartijn/Downloads/monkey2-master/modules/mojo/app/window.monkey2 [284] : Error : Identifier 'dw' not found

***** Doccing module 'sdl2-mixer' *****

Parsing...
Semanting...

***** Doccing module 'stb-truetype' *****

Parsing...
Semanting...
gcmartijn:scripts gcmartijn$

**Comment by RichardBetson** [comment]
It's the same for Linux Mint as well. Same errors.

**Comment by blitz-research** [comment]
Have you rebuilt al?

**Comment by blitz-research** [comment]
Just pushed some new binaries which should sort this too (although the above should also work).

**Comment by gcmartijn** [comment]
yep working again, so I close this issue.
@RichardBetson if you still have a issue please create a new issue
