### ISSUE TITLE
macOS Sierra - rendering bugs

### ISSUE THREAD

**Issue by gcmartijn** [blitz-research/monkey2#82]
Rendering bugs after upgrading to macOS Sierra for a macbook air 2014
mx2cc version 1.0.6

Before everything was rendering smooth, and it still runs smooth but now I get weird artefacts.
Like green strips through the png files inside the game.

I did a search for a demo but all the demo's don't use more then > 15 png files on screen.
the only banana demo that may give some flickering (the blue inside the yellow circles) is vgrid 

You can see it if you use this code:
http://monkey2.monkey-x.com/forums/topic/fps-delta-fixedfps-timing-animation-topic-almost-done/page/2/

The assets
http://monkey2.monkey-x.com/wp-content/uploads/2016/08/animation.zip

This code only use only '3' images on screen, so flickering is less then 15+

**Comment by gcmartijn** [comment]
I did some tests , but don't have a demo code yet.
But then I thought maybe the fix is inside SDL

So first I found this:
http://hg.libsdl.org/SDL/log/618662dc9e82

Then I check the latests SDL version here
http://hg.libsdl.org/SDL

And see a lot of fixes for IOS and still counting.
Maybe @blitz-research can add the latest SDL 'Mercurial' version with every version

**Comment by blitz-research** [comment]
Absolutely no problems with sierra here with anything I've tried so far, including your app.

My guess would be it's a 'new driver version' glitch, that may be sorted in a future update. Can you email me a screenshot anyway?

It's incredibly unlikely to be SDL, as I only use that to open a window and create a GL context. After that, it's pure GL all the way for graphics. 

Anyone else having this problem? What model mac?

**Comment by Difference** [comment]
I get  the Random flicker too on gcmartijns code. Looks a bit like what I posted in this link, but not permanent like on the pyro demo. http://www.monkey-x.com/Community/posts.php?topic=12629&post=124043&view=all#124043

System: Mac Mini latest gen, MacOS Sierra 

Here is code, that has a flickering button:

`
#Import "<std>"
#Import "<mojo>"
#import "<mojox>"
#Import "Lingonberry"
 



Using std..
Using mojo..
Using mojox..

 
 
Class Lingon Extends View

 	Field _berries:=New Stack<View>
	


 	Method AddView( view:View )
		_berries.Add(view)
		AddChildView( view )
	End 	


	Method OnLayout() Override


		
		For Local ber:=Eachin _berries

			ber.Layout="fill"
			
			Local r:= New Recti(Self.Frame.min,Self.Frame.max) 
			
			r.Right /=2
			
			ber.Frame = r
			
		Next
 
	End


 	Method OnRender( canvas:Canvas ) Override
 		canvas.Clear( Color.Red )
	End
	
 
 

End Class



 

 

Class LingonBerryTest Extends Window

 	Field ost:Lingon

	Method New()
		 ost = New Lingon
		 
		 
		 ost.AddView(New Button("Hej"))
		 
		 ContentView = ost
		 ContentView.MakeKeyView()
	
	End
	
 
 
	
	
	Method OnRender( canvas:Canvas ) Override
	
		App.RequestRender()
	
 
		canvas.Clear( Color.Green )
		
	 
 
	End
End

Function Main()

	New AppInstance
	
	New LingonBerryTest
	
	App.Run()

End

`

**Comment by gcmartijn** [comment]
@Difference 
Can you confirm that using the latest version (today) that its working now ?
If you have problems than you can re-open this.

@blitz-research 
With the latest version I don't have any glitch at the moment !
So I close this.

**Comment by Difference** [comment]
@gcmartijn 
Yes, it seems fixed 👍 
It will be interesting to see if the rendering bug on Playniax's web example has gone away too.
