### ISSUE TITLE
MojoX - Does not show extended chars (e.g. æøåÆØÅ)

### ISSUE THREAD

**Issue by Difference** [blitz-research/monkey2#83]
In both Ted2 and mojox controls in general, extended chars are missing.
It seems that text (at least in some cases) are truncated when an extended char is met.

**Comment by blitz-research** [comment]
> In both Ted2 and mojox controls in general, extended chars are missing.

Does it happen with text entered by the user, loaded from file, or both?

If from file, can you email me a demo text file?

**Comment by Difference** [comment]
Forgot to say I'm on MacOS Sierra!
Both when entering text in the edit window and loading from file.
This example shows up fine in Textedit, but Ted2 does not show the extended chars (before the equals sign):

`Test of extended chars.

æ = &aelig;
ø = &oslash;
å = &aring;
Æ = &AElig;
Ø = &Oslash;
Å = &Aring;`

**Comment by blitz-research** [comment]
Should be fixed now.

**Comment by Difference** [comment]
Ted2 is now ok, but this example shows that MojoX, is not handling the extenden chars, it truncates the text, when an extended char is met.

`#Import "<std>"
#Import "<mojo>"
#import "<mojox>"
#Import "<tinyxml2>"
 
Using std..
Using mojo..
Using mojox..
Using tinyxml2..
 
Function Main()
 
	New AppInstance
	
	New MyWindow()
	
	App.Run()
End
 
Class MyWindow Extends Window
 
	Field _tree:TreeView
 
	Method New()
	
		Super.New("XML TreeView Test", 640, 480, WindowFlags.Resizable)
 
		Local xml := LoadEmbeddedXMLString()
		
		Local doc := New XMLDocument()
		
		If doc.Parse(xml) <> XMLError.XML_SUCCESS
			Print "Failed to parse embedded XML!"
			Return
		Endif
				
		Local _tree := New TreeView
 
		_tree.RootNode.Text = "XML document"
 
		AddXMLNodeToTree(doc, _tree.RootNode)
		
		ContentView = _tree
		
		doc.Destroy()
	End
 
	Method AddXMLNodeToTree(xmlNode:XMLNode, parent:TreeView.Node)
	
		Local str := ""
	
		Local xmlElement := xmlNode.ToElement()
		
		If xmlElement
		
			str += "<" + xmlNode.Value()
			
			Local attrib := xmlElement.FirstAttribute()
			While attrib 
				str += " " + attrib.Name() + "=~q" + attrib.Value() + "~q "
				attrib=attrib.NextAttribute()
			wend
			
			str += ">"
		Else
			str += xmlNode.Value()
		Endif
 
		Local treeNode:TreeView.Node
	
		If str
			treeNode = New TreeView.Node(str, parent)
		Endif
		
		Local xmlChild := xmlNode.FirstChild()
	
		While xmlChild
		
			If Not xmlChild.NoChildren()
				If treeNode Then parent = treeNode
			Endif
		
			AddXMLNodeToTree(xmlChild, parent)
			
			xmlChild = xmlChild.NextSibling()
	
		Wend
	
	End
 
End
 
Function LoadEmbeddedXMLString:string()
	
	Local str := "
	<?xml version=~q1.0~q encoding=~qUTF-8~q?>
	
	<extended>
	
	  <one>
	    <name>TEæøåST1TEST1æøå</name>
	    <two>
	        <item name=~qTEST2æøåTEST2æøå~q />
	    </two>
 
	  </one>
 
	</extended>"
 
	Return str
 
End
 `

**Comment by blitz-research** [comment]
The problem was in the tinyxml2 wrapper, fixed now.

**Comment by Difference** [comment]
I should have checket if the error was in tinyxml, thanks for fixing :-)

**Comment by Difference** [comment]
The might stille be room for improvement in the console, as suggested here :  [http://monkey2.monkey-x.com/forums/topic/extended-ascii-chars/](http://monkey2.monkey-x.com/forums/topic/extended-ascii-chars/)
