### ISSUE TITLE
std/graphics/color.monkey2 color additions

### ISSUE THREAD

**Issue by StrangeIsMyName** [blitz-research/monkey2#84]
Hi Mark,
Here are the color additions for std/graphics/color
basically added some new base colors and 5 separate color groups:
UI which has a lot of the microsoft UI colors
Pico which has the pico-8 colors
Xam which has the popular xamarin colors
Vic which has the commodore base colors
and Ex which are the extended colors.
Note the new order for the base colors which groups them in proper color pattern

These are the total final colours I added to support Ted21. No more will be added or removed.

There is also a small function addition to allow integer color definitions

`'new jl added function
#rem monkeydoc Allows a colors to be defined using integer values 0..255 instead of 0..1
#end
Function ColorI:Color( red:Float, green:Float, blue:Float, alpha:float = 255 )
	Return New Color( red / 255, green / 255, blue / 255, alpha / 255)
End`

`#-
'begin of jl added colors.
'NOTE. The colors have also been merged into the original colors and now flow correctly together.
'E.G. blacks to whites, reds to brown to green to blue. so it's best to keep them like this
	
	#rem monkeydoc Transparent black.
	#end
	Const None := New Color( 0,0,0,0 )
	
	#rem monkeydoc Black.
	#end
	Const Black := New Color( 0,0,0 )

	#rem monkeydoc Grey.
	#end
	Const Grey := New Color( .5,.5,.5 )

	#rem monkeydoc Light Grey.
	#end
	Const LightGrey := New Color( .75,.75,.75 )

	#rem monkeydoc Dark Grey.
	#end
	Const DarkGrey := New Color( .25,.25,.25 )

	#rem monkeydoc White.
	#end
	Const White := New Color( 1,1,1 )

	#rem monkeydoc Red.
	#end
	Const Red := New Color( 1,0,0 )
	
	#rem monkeydoc Green.
	#end
	Const Green := New Color( 0,1,0 )

	#rem monkeydoc Blue.
	#end
	Const Blue := New Color( 0,0,1 )

	#rem monkeydoc Brown.
	#end
	Const Brown := New Color( .7,.4,.1 )

	#rem monkeydoc Orange.
	#end
	Const Orange := New Color( 1,.5,0 )

	#rem monkeydoc Yellow.
	#end
	Const Yellow := New Color( 1,1,0 )

	#rem monkeydoc Lime.
	#end
	Const Lime := New Color( .7,1,0 )

	#rem monkeydoc Pine.
	#end
	Const Pine := New Color( 0,.5,0 )

	#rem monkeydoc Aqua.
	#end
	Const Aqua := New Color( 0,.9,.4 )

	#rem monkeydoc Cyan.
	#end
	Const Cyan := New Color( 0,1,1 )

	#rem monkeydoc Sky.
	#end
	Const Sky := New Color( 0,.5,1 )

	#rem monkeydoc Steel.
	#end
	Const Steel := New Color( .2,.2,.7 )

	#rem monkeydoc Violet.
	#end
	Const Violet := New Color( .7,0,1 )

	#rem monkeydoc Magenta.
	#end
	Const Magenta := New Color( 1,0,1 )

	#rem monkeydoc Puce.
	#end
	Const Puce := New Color( 1,0,.4 )

	#rem monkeydoc Skin.
	#end
	Const Skin := New Color( .8,.5,.6 )

	#rem monkeydoc UIDarkGrey.
	#end
	Const UIDarkGrey := New Color( .15,.15,.15 )

	#rem monkeydoc UICharcoal.
	#end
	Const UICharcoal := New Color( .24,.23,.23 )

	#rem monkeydoc UISilver.
	#end
	Const UISilver := New Color( .74,.73,.73 )

	#rem monkeydoc UIBlue.
	#end
	Const UIBlue := New Color( .0,.4,.9 )

	#rem monkeydoc UIPaleBlue.
	#end
	Const UIPaleBlue := New Color( .56,.78,.85 )

	#rem monkeydoc UIDarkBlue.
	#end
	Const UIDarkBlue := New Color( .24,.35,.58 )

	#rem monkeydoc UIOrange.
	#end
	Const UIOrange := New Color( .86,.61,.13 )

	#rem monkeydoc UIBurntOrange.
	#end
	Const UIBurntOrange := New Color( .79,.31,0 )

	#rem monkeydoc UIDarkOrange.
	#end
	Const UIDarkOrange := New Color( .52,.26,.09 )

	#rem monkeydoc UIPurple.
	#end
	Const UIPurple := New Color( .61,.36,.72 )

	#rem monkeydoc UICyan.
	#end
	Const UICyan := New Color( .25,.60,.82 )

	#rem monkeydoc UILightGreen.
	#end
	Const UILightGreen := New Color( .32,.80,.31 )

	#rem monkeydoc UILavender.
	#end
	Const UILavender := New Color( .51,.58,.93 )

	#rem monkeydoc UIVibrantGreen.
	#end
	Const UIVibrantGreen := New Color( .09,.87,.07 )

	#rem monkeydoc UIFontBlue.
	#end
	Const UIFontBlue := New Color( .11,.57,.96 )

	#rem monkeydoc UIBrown.
	#end
	Const UIBrown := New Color( .62,.31,.01 )

	#rem monkeydoc UIGreen.
	#end
	Const UIGreen := New Color( .2,.6,.19 )

	#rem monkeydoc UILeaf.
	#end
	Const UILeaf := New Color( .21,.43,.17 )

	#rem monkeydoc UILime.
	#end
	Const UILime := New Color( .54,.74,.14 )

	#rem monkeydoc UIMagenta.
	#end
	Const UIMagenta := New Color( .99,.01,.59 )

	#rem monkeydoc UIMango.
	#end
	Const UIMango := New Color( .94,.58,.03 )

	#rem monkeydoc UIPink.
	#end
	Const UIPink := New Color( .90,.44,.72 )

	#rem monkeydoc UIRed.
	#end
	Const UIRed := New Color( .89,.07,.01 )

	#rem monkeydoc UIYellow.
	#end
	Const UIYellow := New Color( .89,.87,.01 )

	#rem monkeydoc UITeal.
	#end
	Const UITeal := New Color( .18,.65,.52 )

	#rem monkeydoc PicoBlack.
	#end
	Const PicoBlack := New Color( .1,.1,.1 )

	#rem monkeydoc PicoBrown.
	#end
	Const PicoBrown := New Color( .67,.32,.21 )

	#rem monkeydoc PicoRed.
	#end
	Const PicoRed := New Color( .92,.1,.31 )

	#rem monkeydoc PicoCyan.
	#end
	Const PicoCyan := New Color( .31,.65,.86 )

	#rem monkeydoc PicoBlue.
	#end
	Const PicoBlue := New Color( .1,.16,.32 )

	#rem monkeydoc PicoDirt.
	#end
	Const PicoDirt := New Color( .37,.34,.3 )

	#rem monkeydoc PicoOrange.
	#end
	Const PicoOrange := New Color( .98,.63,.1 )

	#rem monkeydoc PicoPurple.
	#end
	Const PicoPurple := New Color( .51,.46,.61 )

	#rem monkeydoc PicoMaroon.
	#end
	Const PicoMaroon := New Color( .49,.14,.32 )

	#rem monkeydoc PicoSilver.
	#end
	Const PicoSilver := New Color( .76,.76,.77 )

	#rem monkeydoc PicoYellow.
	#end
	Const PicoYellow := New Color( .96,.92,.18 )

	#rem monkeydoc PicoPink.
	#end
	Const PicoPink := New Color( .94,.46,.65 )

	#rem monkeydoc PicoGreen.
	#end
	Const PicoGreen := New Color( 0,.52,.31 )

	#rem monkeydoc PicoWhite.
	#end
	Const PicoWhite := New Color( .99,.94,.91 )

	#rem monkeydoc PicoLime.
	#end
	Const PicoLime := New Color( .36,.73,.3 )

	#rem monkeydoc PicoSkin.
	#end
	Const PicoSkin := New Color( .98,.8,.87 )

	#rem monkeydoc XamCoral.
	#end
	Const XamCoral := New Color( .95,.26,.21 )

	#rem monkeydoc XamPink.
	#end
	Const XamPink := New Color( .91,.11,.38 )

	#rem monkeydoc XamPurple.
	#end
	Const XamPurple := New Color( .61,.15,.69 )

	#rem monkeydoc XamViolet.
	#end
	Const XamViolet := New Color( .4,.22,.71 )

	#rem monkeydoc XamBlue.
	#end
	Const XamBlue := New Color( .24,.17,.7 )

	#rem monkeydoc XamSky.
	#end
	Const XamSky := New Color( .12,.58,.95 )

	#rem monkeydoc XamWater.
	#end
	Const XamWater := New Color( .01,.66,.95 )

	#rem monkeydoc XamAqua.
	#end
	Const XamAqua := New Color( 0,.73,.83 )

	#rem monkeydoc XamPine.
	#end
	Const XamPine := New Color( 0,.58,.53 )

	#rem monkeydoc XamMint.
	#end
	Const XamMint := New Color( .54,.76,.29 )

	#rem monkeydoc XamGreen.
	#end
	Const XamGreen := New Color( .29,.68,.31 )

	#rem monkeydoc XamLime.
	#end
	Const XamLime := New Color( .8,.86,.22 )

	#rem monkeydoc XamYellow.
	#end
	Const XamYellow := New Color( 1,.92,.23 )

	#rem monkeydoc XamPeach.
	#end
	Const XamPeach := New Color( 1,.75,.03 )

	#rem monkeydoc XamOrange.
	#end
	Const XamOrange := New Color( 1,.59,.01 )

	#rem monkeydoc XamEmber.
	#end
	Const XamEmber := New Color( 1,.38,.13 )

	#rem monkeydoc XamBrown.
	#end
	Const XamBrown := New Color( .47,.33,.28 )

	#rem monkeydoc XamSilver.
	#end
	Const XamSilver := New Color( .61,.61,.61 )

	#rem monkeydoc XamSteel.
	#end
	Const XamSteel := New Color( .37,.49,.54 )

	#rem monkeydoc VicBlack.
	#end
	Const VicBlack := New Color( .1,.1,.1 )

	#rem monkeydoc VicGrey.
	#end
	Const VicGrey := New Color( .61,.61,.61 )

	#rem monkeydoc VicWhite.
	#end
	Const VicWhite := New Color( .96,.96,.96 )

	#rem monkeydoc VicRed.
	#end
	Const VicRed := New Color( .74,.14,.2 )

	#rem monkeydoc VicLiver.
	#end
	Const VicLiver := New Color( .45,.16,.18 )

	#rem monkeydoc VicBlush.
	#end
	Const VicBlush := New Color( .87,.43,.54 )

	#rem monkeydoc VicPink.
	#end
	Const VicPink := New Color( .79,.26,.65 )

	#rem monkeydoc VicDirt.
	#end
	Const VicDirt := New Color( .28,.23,.16 )

	#rem monkeydoc VicBrown.
	#end
	Const VicBrown := New Color( .64,.39,.13 )

	#rem monkeydoc VicKhaki.
	#end
	Const VicKhaki := New Color( .67,.61,.2 )

	#rem monkeydoc VicOrange.
	#end
	Const VicOrange := New Color( .92,.53,.19 )

	#rem monkeydoc VicFire.
	#end
	Const VicFire := New Color( .92,.27,0 )

	#rem monkeydoc VicLemon.
	#end
	Const VicLemon := New Color( .96,.88,.41 )

	#rem monkeydoc VicPeach.
	#end
	Const VicPeach := New Color( .98,.70,.4 )

	#rem monkeydoc VicPine.
	#end
	Const VicPine := New Color( .06,.36,.2 )

	#rem monkeydoc VicGreen.
	#end
	Const VicGreen := New Color( .26,.36,.1 )

	#rem monkeydoc VicLime.
	#end
	Const VicLime := New Color( .63,.80,.15 )

	#rem monkeydoc VicOil.
	#end
	Const VicOil := New Color( .18,.28,.3 )

	#rem monkeydoc VicSea.
	#end
	Const VicSea := New Color( .07,.5,.49 )

	#rem monkeydoc VicAqua.
	#end
	Const VicAqua := New Color( .08,.76,.64 )

	#rem monkeydoc VicRoyal.
	#end
	Const VicRoyal := New Color( .13,.35,.96 )

	#rem monkeydoc VicBlue.
	#end
	Const VicBue := New Color( 0,.34,.52 )

	#rem monkeydoc VicSky.
	#end
	Const VicSky := New Color( .19,.63,.94 )

	#rem monkeydoc VicSteel.
	#end
	Const VicSteel := New Color( .69,.86,.92 )

	#rem monkeydoc VicPurple.
	#end
	Const VicPurple := New Color( .2,.16,.59 )

	#rem monkeydoc VicViolet.
	#end
	Const VicViolet := New Color( .6,.39,.97 )

	#rem monkeydoc VicCandy.
	#end
	Const VicCandy := New Color( .96,.55,.97 )

	#rem monkeydoc VicSkin.
	#end
	Const VicSkin := New Color( .95,.72,.56 )

	#rem monkeydoc ExLightGrey.
	#end
	Const ExLightGrey := New Color( .75,.75,.75 )

	#rem monkeydoc ExDarkGrey.
	#end
	Const ExDarkGrey := New Color( .25,.25,.25 )

	#rem monkeydoc ExBrown.
	#end
	Const ExBrown := New Color( .62,.31,0 )

	#rem monkeydoc ExTreeTrunk.
	#end
	Const ExTreeTrunk := New Color( .31,.23,.17 )

	#rem monkeydoc ExLime.
	#end
	Const ExLime := New Color( .54,.74,.14 )

	#rem monkeydoc ExMango.
	#end
	Const ExMango := New Color( .94,.58,.03 )

	#rem monkeydoc ExOrange.
	#end
	Const ExOrange := New Color( .79,.32,0 )

	#rem monkeydoc ExPink.
	#end
	Const ExPink := New Color( .79,.44,.72 )

	#rem monkeydoc ExPurple.
	#end
	Const ExPurple := New Color( .41,.13,.48 )

	#rem monkeydoc ExLeaf.
	#end
	Const ExLeaf := New Color( .2,.6,.2 )

	#rem monkeydoc ExYolk.
	#end
	Const ExYolk := New Color( 1,.65,0 )

	#rem monkeydoc ExPeach.
	#end
	Const ExPeach := New Color( 1,.8,.01 )

	#rem monkeydoc ExSand.
	#end
	Const ExSand := New Color( .94,.87,.7 )

	#rem monkeydoc ExWetSand.
	#end
	Const ExWetSand := New Color( .73,.66,.48 )

	#rem monkeydoc ExNavy.
	#end
	Const ExNavy := New Color( .09,.15,.44 )

	#rem monkeydoc ExMorello.
	#end
	Const ExMorello := New Color( .6,.34,.71 )

	#rem monkeydoc ExTeal.
	#end
	Const ExTeal := New Color( .22,.43,.5 )

	#rem monkeydoc ExSky.
	#end
	Const ExSky := New Color( .2,.59,.85 )

	#rem monkeydoc ExSlime.
	#end
	Const ExSlime := New Color( .18,.8,.44 )

	#rem monkeydoc ExMint.
	#end
	Const ExMint := New Color( .08,.62,.52 )

	#rem monkeydoc ExSilver.
	#end
	Const ExSilver := New Color( .74,.76,.76 )

	#rem monkeydoc ExGold.
	#end
	Const ExGold := New Color( .83,.66,.29 )

	#rem monkeydoc ExForest.
	#end
	Const ExForest := New Color( .17,.31,.21 )

	#rem monkeydoc ExPlum.
	#end
	Const ExPlum := New Color( .36,.2,.36 )

	#rem monkeydoc ExWatermellon.
	#end
	Const ExWatermellon := New Color( .85,.32,.32 )

	#rem monkeydoc ExAvocado.
	#end
	Const ExAvocado := New Color( .55,.69,.12 )

	#rem monkeydoc ExBubblegum.
	#end
	Const ExBubblegum := New Color( .83,.36,.61 )

	#rem monkeydoc ExMaroon.
	#end
	Const ExMaroon := New Color( .47,.18,.16 )

	#rem monkeydoc ExCoffee.
	#end
	Const ExCoffee := New Color( .55,.44,.36 )

	#rem monkeydoc ExLavender.
	#end
	Const ExLavender := New Color( .6,.67,.83 )

	#rem monkeydoc ExPowder.
	#end
	Const ExPowder := New Color( .72,.78,.94 )

	#rem monkeydoc ExPigeon.
	#end
	Const ExPigeon := New Color( .22,.29,.5 )

	#rem monkeydoc ExUmber.
	#end
	Const ExUmber := New Color( .7,.53,0 )

  #rem monkeydoc ExBuff.
	#end
	Const ExBuff := New Color( .84,.77,.64 )

	#rem monkeydoc ExCobble.
	#end
	Const ExCobble := New Color( .47,.38,.33 )

	#rem monkeydoc ExAqua.
	#end
	Const ExAqua := New Color( .59,.67,.68 )

	#rem monkeydoc ExSewer.
	#end
	Const ExSewer := New Color( .78,.78,.59 )

	#rem monkeydoc ExDragon.
	#end
	Const ExDragon := New Color( .8,.38,.5 )

	#rem monkeydoc ExEmber.
	#end
	Const ExEmber := New Color( .74,.47,.34 )

	#rem monkeydoc ExOlive.
	#end
	Const ExOlive := New Color( .52,.6,.1 )

	#rem monkeydoc ExCorn.
	#end
	Const ExCorn := New Color( .91,.8,.32 )

	#rem monkeydoc ExHoney.
	#end
	Const ExHoney := New Color( .95,.48,.59 )

	#rem monkeydoc ExPhlox.
	#end
	Const ExPhlox := New Color( .52,.25,.51 )

	#rem monkeydoc ExKhaki.
	#end
	Const ExKhaki := New Color( .59,.56,.39 )

	#rem monkeydoc ExNougat.
	#end
	Const ExNougat := New Color( .83,.73,.62 )

'end of JL added colors
#-

	`

**Comment by StrangeIsMyName** [comment]
small addition of missing color.
put it directly after VicRoyal:
`
	#rem monkeydoc VicBlue.
	#end
	Const VicBlue := New Color( .15,.49,.66 )

`

**Comment by blitz-research** [comment]
Ok, I've added the first set - thanks! - but not the UI, Pico, Ex etc ones as I think these are more suitable for extension modules.

**Comment by StrangeIsMyName** [comment]
Hi Mark,
Partial thanks
I think you're wrong not using the full set, they cover all the colors and I am still going to have users whith missing color errors.
The next step was finding some way of you using the color selector, but again this is now broken.

I'm not trying to work against you here, I'm really trying to work with you on this.

Jean-Luc

**Comment by blitz-research** [comment]
> I am still going to have users whith missing color errors

Umm, why? Why not just include *your* colors with *your* code? They're just
a bunch of consts, they don't *have* to be in 'Color' (although with class
extensions, you can make it appear as if they are). I really don't
understand this and feel like you're making a big deal out of something
pretty minor.

The bottom line is I don't want 100001 'custom' colors in std.color.Color,
just a simple set of useful stock colors. And I definitely don't want to be
adding more colors each time someone needs them for *their* project!

I don't even think your approach is all that sound for what you're doing -
why not stick the colors in a JSON file or something and load them at
runtime? Much for flexible, as nothing's hardcoded in so you can have as
many palettes/colors as you want, people can add/edit/save palletes etc.
And likely easier to code - what have you got in there anyway, a huge array
of "name/color" structs? Or a massive sequence of 'AddColorGadget(...)'
statements?!? Without reflection, it must be something pretty gnarly!

**Comment by StrangeIsMyName** [comment]
ok,
quiet time for 10...

You are (of course) right with the 'your code' 'your colors' and they don't' have to be in color'. it was just that seemed the best place for them to be consistent with the code and be more helpful to users.

You are also right in talking about extensions. But these are an additions which was not there at the time, were not signposted as was coming, etc. So far (in this respect) Monkey2 is a moving target. You start coding and on a whim everything changes...

I'm not going to comment on the last paragraph - I think that's best ;)

OK. It seems that for whatever reason you think I'm working against you? I'm not.

All I wanted was to have a more productive editor for monkey that all users could benefit from.

I can't see what is so wrong with having a pop-up panel that has all the available colors shown in one simple way with color variations

Do you want me to continue and submit the other stuff like the parsing code for mx2cc and the opengl additions for canvas?

Jean-Luc

**Comment by blitz-research** [comment]
No, I don't think you're working against me, I just think the idea of
adding a bunch of color consts to the standard library for the sake of one
app is a really bad one.

Feel free to post more issues or submit changes etc, but to be honest
unless it's something super simple that looks like it'll be zero hassle to
integrate/maintain, there's little chance it''ll be added as I've just got
too much other stuff to do.

**Comment by StrangeIsMyName** [comment]
mmm

I would totally agree about the "one app". Except the one app is an editor for monkey2: Ted21. which was forked from ted2. 

In this case it is not a standard 'app'. It's meant as a replacement/augment to ted2. So there are lots of things added to make any devs life just abit more pleasant. Having a standard set of colors being one of them.
You mentioned user palettes - already done and fully integrated (visually) into ted21. custom color mixing done and integrated. Icons strips from bitmap done and integrated into ted21. code overview with custom locations done.

This is not an "app" it should be something that everyone can rely on if they want.

I am now working on the prototype vector editor (just doing final debugging), which will allow for complete libriaries of vector objects, which will make stuff like asteriods a very simple process of just drawing the shapes not trying to work out what the numbers are, etc.

As part of that the next step will be the sprite editor. Which directly integrates into the full color systems already developed.

Ted21 can be considered the visual companion to ted2. If you want to use photoshop and ted2 then that's great. but if you just want to draw a sprite and get it working without anything else, then ted21 is where you go...

I'm trying not to add anything to the modules if possible, but something like the colors, parsing and some core graphic stuff really needs to be in the core itself. As said before the colors (bar any minor corrections) are complete and will not be added to.

**Comment by blitz-research** [comment]
> Except the one app is an editor for monkey2

So what?

I strongly disagree with the notion that Ted2 should have any influence over the design of the modules - Ted2 should indeed be 'just an app'. The trick is in making the modules cool enough the Ted2 is a very good app.



IMO, Ted2 should be 'just an app'

I'm glad Ted21 coming along well, but I am not adding any more const colors. Locking this becasue it's going nowhere.
