### ISSUE TITLE
[request] add ability to set textview.cursor size

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#89]
I think, it will be enough to replace BlockCursor flag with enum type variable CursorType {Block, Line, EditLine}.
EditLine = current cursor for "not block" state.
Line = simple vertical line, 1 or 2 px width.

This time I can't override blinked cursor via OnRenderContent() method because blinkOn state is private.

**Comment by blitz-research** [comment]
Ok, added CursorType.Block, CursorType.Line and CursorType.IBeam.
