### ISSUE TITLE
Mark: mx2cc check app addition

### ISSUE THREAD

**Issue by StrangeIsMyName** [blitz-research/monkey2#91]
This is a modification to add the ability to just 'check' an app without compiling. this is useful to see if there are any error in an app, etc

basically it is done in a couple of places so here goes

first add a new rem to the initial rem block:
`'Const TestArgs:="mx2cc checkapp -clean src/ted2/ted2"`

in the Main() function we need to change the help text:
`'JL old		Print "Usage: mx2cc makeapp|makemods|makedocs [-build|-run] [-clean] [-verbose[=1|2|3]] [-target=desktop|emscripten] [-config=debug|release] [-apptype=gui|console] source|modules..."
		Print "Usage: mx2cc makeapp|makemods|makedocs|checkapp [-build|-run] [-clean] [-verbose[=1|2|3]] [-target=desktop|emscripten] [-config=debug|release] [-apptype=gui|console] source|modules..."
`

further on we need to add 'check-up' to the cmd select:
`		Select cmd
		Case "checkapp"
			ok=CheckApp( args )
`

finally we need to add the new function checkapp. this is just the normal makeapp without the last compile bits:
`Function CheckApp:Bool( args:String[] )

	Local opts:=New BuildOpts
	opts.productType="app"
	opts.appType="gui"
	opts.target="desktop"
	opts.config="debug"
	opts.clean=False
	opts.fast=True
	opts.verbose=0
	opts.passes=5
	
	args=ParseOpts( opts,args )
	
	If args.Length<>1 Fail( "Invalid app source file" )
	
	Local cd:=CurrentDir()
	ChangeDir( StartDir )
	Local srcPath:=RealPath( args[0].Replace( "\","/" ) )
	ChangeDir( cd )
	
	opts.mainSource=srcPath
	
	Print ""
	Print "***** Checking app '"+opts.mainSource+"' *****"
	Print ""

	New BuilderInstance( opts )
	
	Builder.Parse()
	If Builder.errors.Length Return False
	If opts.passes=1 Return True
	
	Builder.Semant()
	If Builder.errors.Length Return False
	If opts.passes=2 Return True
	
	Print "Application Checked"
	Return True
End

`

this is for V1.07 the latest release.

Check-up is also now being referenced on the monkey2 forum as the right way to do things by some other developers instead of them creating a new parse function, so it is best for this to be included
asap

I can provide the entire source if needed, but this is just the needed changes?

let me know :)

**Comment by blitz-research** [comment]
You can use -semant switch with mx2cc now to perform a 'check'.

The are now several options to control how much mx2cc does:

-parse (just parse)
-semant (parse and semant, ie: 'check')
-translate (parse, semant, translate)
-build (parse, semant, translate, build)
-run (the works)
