### ISSUE TITLE
Lambdas Silently Ignore Default Arguments

### ISSUE THREAD

**Issue by ImmutableOctet** [blitz-research/monkey2#92]
Lambda expressions don’t seem to work properly with default arguments. They’re treated as if they weren’t assigned. This would be fine if it’s the intended behavior, but an error message is not provided. Assuming default arguments are intended to work, then this is a bug, rather than a missing error.

**_Testing was performed with mx2cc version 1.0.7.**_

_Example:_

```
Function Main:Void()
    Local f:= Lambda(msg:String="Hello world.")
        Print(msg)
    End

    For Local i:= 0 Until 200
        f()
    Next

    f("Done.")

    Return
End
```

Presuming the rules for lambdas are the same as functions, this should output "Hello world." 200 times, then output "Done.".

MX2CC currently produces an error claiming that no arguments were given, ignoring the default assignment, for better or worse.

> monkey2/tmp/untitled1.monkey2 [7] : Error : Wrong number of arguments - expecting 1 not 0

<[Original forum thread](http://monkey2.monkey-x.com/forums/topic/lambdas-silently-ignore-default-arguments/)>

**Comment by blitz-research** [comment]
Ok, have prohibited default params for lambdas for now.
