### ISSUE TITLE
Mx2 2 is Limited to 127 ANSI Char Set

### ISSUE THREAD

**Issue by abakobo** [blitz-research/monkey2#93]
having the 16bit extended ASCII Char set would be very better..

some code to show the problem

#Import "<std>"
#Import "<mojo>"
 
Using std..
Using mojo..
 
Class MyWindow Extends Window
	Field theFont:Font
 
	Method OnRender( canvas:Canvas ) Override
		canvas.Font = Font.Load( "C:\Windows/Fonts/comic.ttf", 10 )
		Local s:String
		For Local i:=0 To  255
			Local j:=i
			Local k:=15
			Repeat
				If j>620/10
					j=j-620/10
					k=k+30
				End
			Until j<=620/10
			s=String.FromChar(i)
			Print  s[0]+" "+s
			canvas.DrawText( s,j*10,k )
		Next
		s="elegant" 
		For Local i:=0 To 6
		 Print s[i]+" -->  "+String.FromChar(s[i])
		Next
		Print "--------"
		s="élégant" 'this contains 2 special "e" for elegant in french
		For Local i:=0 To 10 'it will take 10 chars though "élégant" is only 7 16bit chars
		 Print s[i]+" -->  "+String.FromChar(s[i])
		Next
	End
End
Function Main()
	New AppInstance
	New MyWindow
	App.Run()
End

**Comment by abakobo** [comment]
8bit 256chars not 16bit....

**Comment by blitz-research** [comment]
Should be fixed now, although élégant *is* only 7 chars long since strings store 16bit chars.
