### ISSUE TITLE
bug mac osx Cmd+Q and menu quit not quitting

### ISSUE THREAD

**Issue by StrangeIsMyName** [blitz-research/monkey2#94]
on any OSX created app. cmd+q is quit -but doesn’t. The same is true for the OS X menu item 'quit' for the app. it just sits there...

Quit is listed in the menu for the app, it is registered as being recieved, but the app stays open. looks like mojo.app or something along the way isn’t passing the menu click on.

Catching cmd+q is fine for keyboard catching, but won't catch the menu.

Should be added to the mojo core?

**Comment by blitz-research** [comment]
Should finally be fixed now that I know what menu you mean! Sorry for being a bit slow on this...
