### ISSUE TITLE
Virtual Class giving error on constructors

### ISSUE THREAD

**Issue by peterigz** [blitz-research/monkey2#95]
Was just updating TimelineFX to work with 1.08 and getting an error in the c compiler “constructors cannot be declared virtual [-fpermissive]”. So what I was doing was putting Virtual after the class name which as a result is now complaining that the “New” method cannot be declared virtual (worked ok before). Is there something I can do to make the New method not virtual or will I have to just start putting virtual after individual methods instead?

This code replicates the error:

    Class Test Virtual
    	Field test:Int
    	Method New()
    		test = 1
    	End
    End
 
    Function Main()
    	Local t:=New Test
    End

(Still happening with your new potential fix)

**Comment by blitz-research** [comment]
Hmm, the above is working for me now - have you done a 'rebuildmx2cc' in scripts dir?

**Comment by peterigz** [comment]
Yep, sorry works fine. I thought I read rebuildall not rebuildmx2cc :)
