### ISSUE TITLE
Request : emit mojox.button.triggered() on mouseup (click), not on mousedown

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#96]

**Comment by blitz-research** [comment]
Have you seen mojox.Button.PushButtonMode property?

**Comment by engor** [comment]
I need to use that behaviour with ToolBarButton.
Thanks for PushButtonMode.
Now I use my extended class ToolButtonExt and set PushButtonMode=True inside of it.

Also: for ToolBar - it can be useful to add method AddButton along with AddAction. Params can be the same but return value is ToolBarButton or Button.

**Comment by blitz-research** [comment]
Should PushButtonMode=True be the default for ToolButton? I'm OK with
that...





On Sun, Oct 23, 2016 at 5:53 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
Yes. :)
