### ISSUE TITLE
Jagged arrays syntax reversed

### ISSUE THREAD

**Issue by Difference** [blitz-research/monkey2#98]
I'm entering this as a bug, so that it will not be forgotten.
( In reference to http://monkey2.monkey-x.com/forums/topic/syntax-for-array-of-arrays-jagged-array/ )

I think the syntax should be changed to the way it's done in Monkey 1 and C# to ease "language transition" for the coder and porting of mx1 code.

Better do it now, before too much mx2 code relies on the current syntax.

**Comment by blitz-research** [comment]
Fixed a while back.

**Comment by Difference** [comment]
Oh, I haven't noticed, and it seems to be down to the fact that mx2 now seems to allow both syntaxes. Is this on purpose? This still works:

`Function Main()
 
 Local w:=5,h:=10
 
 Local t:=New Int[w][]
 
 For Local x:=0 Until w
  t[x]=New Int[h]
  
  For Local y:Int = 0 Until h
  	t[x][y] = x + y * 100
  Next 
  
  
 Next
 
 For Local y:=0 Until h
  For Local x:=0 Until w
   Print t[x][y]
  Next
  Print "---"
 Next
 
End`

**Comment by blitz-research** [comment]
Done about a month ago!

**Comment by Difference** [comment]
Yes, Cool, but is both syntax variations supposed to work? Because as får as I can tell the do.

**Comment by blitz-research** [comment]
Not sure what you mean by both syntaxes - that looks right to me and should
be the same as c#, java style?

**Comment by Difference** [comment]
I mean that both 
Local t:=New Int[][w]
and 
Local t:=New Int[w][]
compiles, and gives the same result.

**Comment by blitz-research** [comment]
I think mx2 still allows new int[][10], which I'll fix - is this what you
mean.

This is very messy stuff! Quite a good write up here...

https://blogs.msdn.microsoft.com/ericlippert/2009/08/17/arrays-of-arrays/

Basically, jagged arrays types need to be evaluated 'left to right',
whereas other types are evaluated 'right to left', eg:

Local t:Int Ptr

...is a pointer (ie: reading right to left), but...

Local p:int[,][]

...is a 2d array - it's 'inside out'!

It would be more consistent if arrays were declared like this:

Local p:[,][]int

...but I wont be doing that!

**Comment by Difference** [comment]
> I think mx2 still allows new int[][10], which I'll fix - is this what you
mean.

Exactly! :-) 

I do realize, as that  what Eric Lippert is stating seems logical, but in this case, I think you're right to go with the flow and do it the c#/monkey1 way.

**Comment by blitz-research** [comment]
He agrees!
